"""Railroad expected-reachability planner for DeepSym.

This version keeps the learned probabilistic effect branches instead of turning
all actions into nominal deterministic success branches. It computes a finite-
horizon expected reachability value:

    V(s, h) = 1                                      if goal(s)
            = 0                                      if h == 0
            = max_a sum_{s'} P(s' | s, a) V(s', h-1) otherwise

Important execution note
------------------------
This is a policy/value planner. DeepSym's current execute_plan.py still expects
one fixed plan.txt. Therefore this script writes a representative rollout of the
policy by following the outcome branch that contributes most to expected value.
That plan.txt is useful for debugging and for approximate open-loop execution,
but the full benefit of expected-reachability planning requires a closed-loop
executor:

    observe -> build symbolic state -> choose one action -> execute -> observe -> replan

Usage:
    python make_plan_railroad.py -opts opts.yaml -goal "(H3)" --debug-actions
"""

import argparse
import json
import math
import heapq
import os
import re
import sys
from functools import lru_cache
from typing import Dict, Iterable, List, Optional, Sequence, Tuple

import yaml

from railroad._bindings import (
    AndGoal,
    Fluent as F,
    LiteralGoal,
    NumericCompareOp,
    NumericCondition,
    NumericGoal,
    NumericUpdate,
    NumericUpdateOp,
    State,
)
from railroad.core import Effect, Operator, transition
from railroad.planner import get_usable_actions


# Full learned effect distribution by original stack operator name.
OPERATOR_EFFECT_DISTS: Dict[str, Dict[str, float]] = {}


# ---------------------------------------------------------------------------
# Probability helpers
# ---------------------------------------------------------------------------

def _normalize_effect_distribution(prob_effects: Sequence[Dict], *, op_name: str) -> List[Dict]:
    """Merge duplicate effects and normalize probabilities.

    A true probabilistic transition needs a valid distribution. Learned JSON
    generated by learn_rules_railroad.py should already sum to 1; this function
    also protects against manual edits during debugging.
    """
    merged: Dict[str, float] = {}
    for pe in prob_effects:
        name = str(pe["effect_name"])
        p = float(pe["probability"])
        if p <= 0.0:
            continue
        merged[name] = merged.get(name, 0.0) + p

    total = sum(merged.values())
    if total <= 0.0:
        raise ValueError(f"Operator {op_name} has an empty effect distribution")

    if abs(total - 1.0) > 1e-6:
        print(
            f"WARNING: probabilities for {op_name} sum to {total:.6f}; normalizing.",
            file=sys.stderr,
        )

    return [
        {"probability": p / total, "effect_name": name}
        for name, p in sorted(merged.items())
    ]


# ---------------------------------------------------------------------------
# Railroad operator reconstruction
# ---------------------------------------------------------------------------

def _effect_fluents(effect_name: str) -> set:
    """Map a DeepSym outcome to structural Railroad fluents.

    H/S progress is represented directly by numeric updates.
    """
    effect_name = str(effect_name)

    if effect_name in {"stacked", "inserted"}:
        return {
            F("instack", "?above"),
            F("stackloc", "?above"),
            ~F("stackloc", "?below"),
        }

    if effect_name in {
        "roll1",
        "roll2",
        "tumble1",
        "tumble2",
    }:
        return {F(effect_name)}

    return {F(effect_name)}


def _effect_numeric_updates(effect_name: str):
    """Map DeepSym progress outcomes to native H/S updates."""
    effect_name = str(effect_name)

    if effect_name == "stacked":
        return [
            NumericUpdate(
                "H",
                NumericUpdateOp.INCREASE,
                1,
            ),
            NumericUpdate(
                "S",
                NumericUpdateOp.INCREASE,
                1,
            ),
        ]

    if effect_name == "inserted":
        return [
            NumericUpdate(
                "S",
                NumericUpdateOp.INCREASE,
                1,
            ),
        ]

    return []


def build_probabilistic_stack_operator(
    spec: Dict,
) -> Operator:
    """Build one probabilistic learned stack operator."""

    below_type = spec.get(
        "below_type",
        spec.get("obj1_type"),
    )

    above_type = spec.get(
        "above_type",
        spec.get("obj2_type"),
    )

    if below_type is None or above_type is None:
        raise ValueError(
            f"Malformed stack operator spec: {spec}"
        )

    op_name = str(spec["name"])

    normalized_effects = (
        _normalize_effect_distribution(
            spec["prob_effects"],
            op_name=op_name,
        )
    )

    OPERATOR_EFFECT_DISTS[op_name] = {
        str(pe["effect_name"]): float(
            pe["probability"]
        )
        for pe in normalized_effects
    }

    preconditions = [
        F("pickloc", "?above"),
        F("stackloc", "?below"),
        F(below_type, "?below"),
        F(above_type, "?above"),
        F(
            spec["relation"],
            "?below",
            "?above",
        ),
    ]

    prob_branches = []

    for pe in normalized_effects:
        p = float(pe["probability"])
        effect_name = str(pe["effect_name"])

        branch_effect = Effect(
            time=0,
            resulting_fluents=_effect_fluents(
                effect_name
            ),
            numeric_updates=_effect_numeric_updates(
                effect_name
            ),
        )

        prob_branches.append(
            (
                p,
                [branch_effect],
            )
        )

    probabilistic_effect = Effect(
        time=0,
        resulting_fluents=set(),
        prob_effects=prob_branches,
    )

    # Preserve original DeepSym semantics: the placed object is consumed
    # regardless of which probabilistic outcome occurs.
    pickloc_removal = Effect(
        time=0,
        resulting_fluents={
            ~F("pickloc", "?above")
        },
    )

    return Operator(
        name=op_name,
        parameters=[
            ("?below", "object"),
            ("?above", "object"),
        ],
        preconditions=preconditions,
        effects=[
            probabilistic_effect,
            pickloc_removal,
        ],
    )


def build_auxiliary_operator(
    spec: Dict,
) -> Optional[Operator]:
    """Build the remaining non-learned operator.

    Legacy numbered bookkeeping specs are ignored.
    """

    operator_type = spec["type"]

    if operator_type in {
        "increase_height",
        "increase_stack",
    }:
        return None

    if operator_type == "makebase":
        return Operator(
            name="makebase",
            parameters=[
                ("?obj", "object")
            ],
            preconditions=[
                ~F("base")
            ],
            effects=[
                Effect(
                    time=0,
                    resulting_fluents={
                        F("base"),
                        ~F("pickloc", "?obj"),
                        F("stackloc", "?obj"),
                    },
                    numeric_updates=[
                        NumericUpdate(
                            "H",
                            NumericUpdateOp.INCREASE,
                            1,
                        ),
                        NumericUpdate(
                            "S",
                            NumericUpdateOp.INCREASE,
                            1,
                        ),
                    ],
                )
            ],
        )

    raise ValueError(
        f"Unknown auxiliary operator type: "
        f"{operator_type}"
    )


def load_operators_from_json(
    json_path: str,
) -> List[Operator]:
    """Reconstruct learned and auxiliary Railroad operators."""

    with open(json_path, "r") as f:
        all_specs = json.load(f)

    OPERATOR_EFFECT_DISTS.clear()

    operators: List[Operator] = []

    for spec in all_specs["stack_operators"]:
        operators.append(
            build_probabilistic_stack_operator(
                spec
            )
        )

    for spec in all_specs.get(
        "auxiliary_operators",
        [],
    ):
        operator = build_auxiliary_operator(
            spec
        )

        if operator is not None:
            operators.append(operator)

    return operators


def parse_deepsym_goal(goal_str: str):
    """Parse H/S tokens as exact numeric goals."""

    negative_tokens = set(
        re.findall(
            r"\(not\s*\((\w+)\)\)",
            goal_str,
        )
    )

    without_not_clauses = re.sub(
        r"\(not\s*\(\w+\)\)",
        " ",
        goal_str,
    )

    positive_tokens = [
        token
        for token in re.findall(
            r"\((\w+)\)",
            without_not_clauses,
        )
        if token.lower()
        not in {"and", "goal"}
    ]

    def token_goal(
        token: str,
        *,
        negated: bool = False,
    ):
        match = re.fullmatch(
            r"([HS])(\d+)",
            token,
            flags=re.IGNORECASE,
        )

        if match:
            variable = match.group(1).upper()
            value = int(match.group(2))

            op = (
                NumericCompareOp.NE
                if negated
                else NumericCompareOp.EQ
            )

            return NumericGoal(
                NumericCondition(
                    variable,
                    op,
                    value,
                )
            )

        return LiteralGoal(
            ~F(token)
            if negated
            else F(token)
        )

    goals = [
        token_goal(token)
        for token in positive_tokens
    ]

    goals.extend(
        token_goal(
            token,
            negated=True,
        )
        for token in sorted(
            negative_tokens
        )
    )

    if not goals:
        raise ValueError(
            f"No goal conditions found in: "
            f"{goal_str}"
        )

    if len(goals) == 1:
        return goals[0]

    return AndGoal(goals)


# Backward-compatible name used by older diagnostic scripts.
parse_pddl_goal = parse_deepsym_goal


def _extract_parenthesized_section(content: str, start_token: str, end_token: str) -> str:
    start = content.find(start_token)
    if start < 0:
        return ""
    start += len(start_token)
    end = content.find(end_token, start)
    if end < 0:
        end = len(content)
    return content[start:end]


def parse_objects_txt(objects_path: str) -> Dict[str, Dict[str, float]]:
    """Parse DeepSym objects.txt/plan header.

    Format:
        5
        O1 x y size
        ...
    """
    infos: Dict[str, Dict[str, float]] = {}
    if not os.path.exists(objects_path):
        return infos

    with open(objects_path, "r") as f:
        lines = [line.strip() for line in f if line.strip()]
    if not lines:
        return infos

    try:
        n = int(lines[0].split()[0])
    except Exception:
        return infos

    for line in lines[1:1 + n]:
        parts = line.split()
        if len(parts) < 4:
            continue
        infos[parts[0]] = {
            "x": float(parts[1]),
            "y": float(parts[2]),
            "size": float(parts[3]),
        }
    return infos


def parse_problem_railroad(scene_path: str, objects_path: Optional[str] = None):
    """Parse DeepSym/Railroad scene JSON for objects, types, relations, counters.

    This replaces the previous use of problem.pddl in the Railroad path.  The
    JSON is written by recognize.py as save_dir/railroad_problem.json.

    Expected format:
        {
          "objects": [
             {"name": "O1", "type": "objtype3", "loc": [x, y], "size": s}, ...
          ],
          "relations": [
             {"name": "relation0", "below": "O1", "above": "O2"}, ...
          ],
          "counters": {"H": "H0", "S": "S0"}
        }
    """
    if not os.path.exists(scene_path):
        raise FileNotFoundError(
            f"Missing {scene_path}. Run recognize.py first; it should write railroad_problem.json."
        )

    with open(scene_path, "r") as f:
        data = json.load(f)

    raw_objects = data.get("objects", [])
    if not raw_objects:
        raise ValueError(f"{scene_path} has no objects")

    objects: List[str] = []
    obj_types: Dict[str, str] = {}
    object_infos: Dict[str, Dict[str, float]] = {}

    for obj in raw_objects:
        name = str(obj["name"]).upper()
        typ = str(obj["type"])
        loc = obj.get("loc", obj.get("location", [0.0, 0.0]))
        size = float(obj.get("size", 0.1))
        objects.append(name)
        obj_types[name] = typ
        object_infos[name] = {"x": float(loc[0]), "y": float(loc[1]), "size": size}

    # objects.txt is still allowed only as execution geometry fallback.  It is
    # not a symbolic planning input and can be removed once plan writing uses
    # railroad_problem.json directly everywhere.
    if objects_path and os.path.exists(objects_path):
        txt_infos = parse_objects_txt(objects_path)
        if txt_infos:
            object_infos.update({k.upper(): v for k, v in txt_infos.items()})

    relations: List[Tuple[str, str, str]] = []
    for rel in data.get("relations", []):
        if isinstance(rel, dict):
            r = str(rel.get("name", rel.get("relation")))
            below = str(rel.get("below", rel.get("obj1"))).upper()
            above = str(rel.get("above", rel.get("obj2"))).upper()
        else:
            r, below, above = rel
            r = str(r)
            below = str(below).upper()
            above = str(above).upper()
        relations.append((r, below, above))

    def parse_counter_value(
        variable: str,
        raw,
    ) -> int:
        if raw is None:
            return 0

        if isinstance(raw, bool):
            raise ValueError(
                f"Invalid {variable} counter value: "
                f"{raw!r}"
            )

        if isinstance(raw, int):
            return int(raw)

        value = str(raw).strip().upper()

        match = re.fullmatch(
            rf"{variable}(\d+)",
            value,
        )

        if match:
            return int(match.group(1))

        if re.fullmatch(
            r"[+-]?\d+",
            value,
        ):
            return int(value)

        raise ValueError(
            f"Invalid {variable} counter value: "
            f"{raw!r}"
        )

    numeric_data = data.get(
        "numeric_state"
    )

    if isinstance(
        numeric_data,
        dict,
    ):
        counters = {
            "H": parse_counter_value(
                "H",
                numeric_data.get("H", 0),
            ),
            "S": parse_counter_value(
                "S",
                numeric_data.get("S", 0),
            ),
        }

    else:
        legacy_data = data.get(
            "counters",
            {},
        )

        if isinstance(
            legacy_data,
            dict,
        ):
            counters = {
                "H": parse_counter_value(
                    "H",
                    legacy_data.get("H", 0),
                ),
                "S": parse_counter_value(
                    "S",
                    legacy_data.get("S", 0),
                ),
            }

        else:
            tokens = [
                str(v).strip().upper()
                for v in legacy_data
            ]

            h_token = next(
                (
                    v
                    for v in tokens
                    if re.fullmatch(
                        r"H\d+",
                        v,
                    )
                ),
                "H0",
            )

            s_token = next(
                (
                    v
                    for v in tokens
                    if re.fullmatch(
                        r"S\d+",
                        v,
                    )
                ),
                "S0",
            )

            counters = {
                "H": parse_counter_value(
                    "H",
                    h_token,
                ),
                "S": parse_counter_value(
                    "S",
                    s_token,
                ),
            }

    missing_types = [obj for obj in objects if obj not in obj_types]
    if missing_types:
        raise ValueError(f"Objects missing types in railroad_problem.json: {missing_types}")

    return objects, obj_types, relations, counters, object_infos


# Backward-compatible name for older imports.  In the Railroad path this no
# longer parses PDDL; it expects railroad_problem.json.
def parse_problem_pddl(problem_path: str, objects_path: Optional[str] = None):
    return parse_problem_railroad(problem_path, objects_path)


def build_initial_state(
    objects: Sequence[str],
    obj_types: Dict[str, str],
    relations: Sequence[
        Tuple[str, str, str]
    ],
    counters: Dict[str, int],
):
    """Build native numeric DeepSym state."""

    fluents = set()

    for obj in objects:
        fluents.add(
            F("pickloc", obj)
        )

    for obj, typ in obj_types.items():
        fluents.add(
            F(typ, obj)
        )

    for rel, obj1, obj2 in relations:
        fluents.add(
            F(rel, obj1, obj2)
        )

    numeric_values = {
        "H": int(
            counters.get("H", 0)
        ),
        "S": int(
            counters.get("S", 0)
        ),
    }

    return (
        State(
            fluents=fluents,
            numeric_values=numeric_values,
        ),
        {
            "object": set(objects),
        },
    )


def state_key(
    state: State,
) -> Tuple[str, ...]:
    """Hashable key including fluent and numeric state."""

    parts = [
        f"F:{fluent}"
        for fluent in state.fluents
    ]

    parts.extend(
        f"N:{name}={value}"
        for name, value
        in state.numeric_values.items()
    )

    return tuple(
        sorted(parts)
    )


def action_base_name(
    action_name: str,
) -> str:
    return action_name.split()[0]


def is_stack_action(
    action_name: str,
) -> bool:
    return action_base_name(
        action_name
    ).startswith("stack")


def is_progress_state(
    state: State,
    previous_state: State,
) -> bool:
    """Whether H or S increased."""

    before = dict(
        previous_state.numeric_values
    )

    after = dict(
        state.numeric_values
    )

    return (
        after.get("H", 0)
        > before.get("H", 0)
        or
        after.get("S", 0)
        > before.get("S", 0)
    )


def progress_outcomes_for_plan(
    action_name: str,
    current_state: State,
    outcomes: Sequence[
        Tuple[State, float]
    ],
) -> List[Tuple[State, float]]:
    """Keep only progress branches for fixed stack plans."""

    if not is_stack_action(
        action_name
    ):
        return list(outcomes)

    return [
        (state, probability)
        for state, probability in outcomes
        if is_progress_state(
            state,
            current_state,
        )
    ]


def transition_safe(state: State, action) -> List[Tuple[State, float]]:
    """Call Railroad transition and normalize/merge identical states.

    `get_usable_actions` can be permissive with generated operators and negated
    fluents. Treat Railroad transition() as the final precondition check. If an
    action is rejected by transition(), skip it in the expected-reachability DP
    instead of crashing.
    """
    try:
        outcomes = transition(state, action)
    except Exception as exc:  # Railroad may raise bindings-side RuntimeError.
        msg = str(exc)
        if "Precondition not satisfied" in msg or "precondition" in msg.lower():
            return []
        raise

    merged: Dict[Tuple[str, ...], Tuple[State, float]] = {}

    for next_state, p in outcomes:
        p = float(p)
        if p <= 0.0:
            continue
        key = state_key(next_state)
        if key in merged:
            old_state, old_p = merged[key]
            merged[key] = (old_state, old_p + p)
        else:
            merged[key] = (next_state, p)

    total = sum(p for _, p in merged.values())
    if total <= 0.0:
        return []
    return [(s, p / total) for s, p in merged.values()]


def expected_reachability_plan(initial_state: State,
                               goal,
                               all_actions: Sequence,
                               max_steps: int,
                               debug: bool = False):
    """Compute finite-horizon expected reachability and a greedy policy."""
    state_store: Dict[Tuple[str, ...], State] = {state_key(initial_state): initial_state}
    policy: Dict[Tuple[Tuple[str, ...], int], Tuple[Optional[str], float]] = {}
    outcome_cache: Dict[Tuple[Tuple[str, ...], str], List[Tuple[State, float]]] = {}

    # Deterministic ordering for reproducibility. Prefer auxiliary actions when
    # they are immediately useful, then stack actions by name.
    sorted_actions = sorted(all_actions, key=lambda a: a.name)

    def heuristic_action_order(
        action,
    ) -> Tuple[int, str]:
        name = action.name

        if name.startswith("makebase"):
            return (0, name)

        if is_stack_action(name):
            return (1, name)

        return (2, name)

    @lru_cache(maxsize=None)
    def value(key: Tuple[str, ...], depth: int) -> float:
        state = state_store[key]

        if goal.evaluate(state):
            policy[(key, depth)] = (None, 1.0)
            return 1.0
        if depth <= 0:
            policy[(key, depth)] = (None, 0.0)
            return 0.0

        usable = get_usable_actions(state, sorted_actions)
        usable = sorted(usable, key=heuristic_action_order)
        if not usable:
            policy[(key, depth)] = (None, 0.0)
            return 0.0

        best_action_name: Optional[str] = None
        best_val = -1.0

        for action in usable:
            cache_key = (key, action.name)
            if cache_key not in outcome_cache:
                outcome_cache[cache_key] = transition_safe(state, action)
            outcomes = outcome_cache[cache_key]
            if not outcomes:
                continue

            expected = 0.0
            for next_state, p in outcomes:
                next_key = state_key(next_state)
                state_store.setdefault(next_key, next_state)
                expected += p * value(next_key, depth - 1)

            # Reproducible tie-break: higher expected value, then lower action name.
            if expected > best_val + 1e-12:
                best_val = expected
                best_action_name = action.name

        if best_val < 0.0:
            best_val = 0.0
            best_action_name = None

        policy[(key, depth)] = (best_action_name, best_val)
        return best_val

    start_key = state_key(initial_state)
    start_val = value(start_key, max_steps)

    return start_val, policy, state_store, outcome_cache, value


def choose_representative_outcome(
    current_state: State,
    outcomes: Sequence[
        Tuple[State, float]
    ],
    remaining_depth: int,
    value_fn,
    mode: str,
) -> Tuple[State, float]:
    """Choose one branch for representative plan output."""

    if not outcomes:
        raise ValueError(
            "Cannot choose from empty outcome list"
        )

    if mode == "probability":
        return max(
            outcomes,
            key=lambda item: item[1],
        )

    if mode == "value":
        return max(
            outcomes,
            key=lambda item: value_fn(
                state_key(item[0]),
                remaining_depth,
            ),
        )

    if mode == "progress":
        progress = [
            (state, probability)
            for state, probability in outcomes
            if is_progress_state(
                state,
                current_state,
            )
        ]

        if progress:
            return max(
                progress,
                key=lambda item: (
                    item[1],
                    value_fn(
                        state_key(item[0]),
                        remaining_depth,
                    ),
                ),
            )

        return max(
            outcomes,
            key=lambda item: item[1],
        )

    # Default: largest p * V contribution.
    return max(
        outcomes,
        key=lambda item: (
            item[1]
            * value_fn(
                state_key(item[0]),
                remaining_depth,
            )
        ),
    )


def rollout_policy(initial_state: State,
                   goal,
                   all_actions: Sequence,
                   max_steps: int,
                   policy,
                   outcome_cache,
                   value_fn,
                   outcome_mode: str):
    """Roll out the computed policy into one representative action sequence."""
    state = initial_state
    history: List[str] = []
    branch_probability = 1.0
    visited_guard = set()

    action_by_name = {a.name: a for a in all_actions}

    for remaining in range(max_steps, 0, -1):
        if goal.evaluate(state):
            break

        key = state_key(state)
        guard_key = (key, remaining)
        if guard_key in visited_guard:
            break
        visited_guard.add(guard_key)

        action_name, _ = policy.get((key, remaining), (None, 0.0))
        if action_name is None:
            break
        action = action_by_name[action_name]
        history.append(action.name)

        outcomes = outcome_cache.get((key, action.name))
        if outcomes is None:
            outcomes = transition_safe(state, action)
            outcome_cache[(key, action.name)] = outcomes
        if not outcomes:
            break

        state, chosen_p = choose_representative_outcome(
            state,
            outcomes,
            remaining - 1,
            value_fn,
            outcome_mode,
        )
        branch_probability *= float(chosen_p)

    return history, state, branch_probability


def max_probability_linear_plan(initial_state: State,
                                goal,
                                all_actions: Sequence,
                                max_steps: int):
    """Find the highest-probability single executable progress path to the goal.

    This is different from expected reachability. Expected reachability computes a
    policy that may take one action, observe a failure branch, and then use a
    fallback action. A plain DeepSym plan.txt cannot express that contingency.

    This function therefore ignores roll/tumble branches for stack actions and
    searches for a single successful branch sequence with maximum probability
    product. It is the right output mode before a closed-loop executor exists.
    """
    start_key = state_key(initial_state)
    state_store: Dict[Tuple[str, ...], State] = {start_key: initial_state}
    parent: Dict[Tuple[Tuple[str, ...], int], Tuple[Tuple[str, ...], int, str, float]] = {}
    best_cost: Dict[Tuple[Tuple[str, ...], int], float] = {(start_key, 0): 0.0}

    sorted_actions = sorted(all_actions, key=lambda a: a.name)
    queue: List[Tuple[float, int, int, Tuple[str, ...]]] = []
    push_counter = 0
    heapq.heappush(queue, (0.0, 0, push_counter, start_key))

    best_goal_node = None

    while queue:
        cost, depth, _seq, key = heapq.heappop(queue)
        node = (key, depth)
        if cost > best_cost.get(node, float("inf")) + 1e-12:
            continue

        state = state_store[key]
        if goal.evaluate(state):
            best_goal_node = node
            break
        if depth >= max_steps:
            continue

        for action in sorted(get_usable_actions(state, sorted_actions), key=lambda a: a.name):
            outcomes = transition_safe(state, action)
            if not outcomes:
                continue

            # A fixed linear plan can only represent success/progress branches.
            # Failure branches become plan failure, not a later fallback action.
            usable_outcomes = progress_outcomes_for_plan(action.name, state, outcomes)
            if not usable_outcomes:
                continue

            for next_state, p in usable_outcomes:
                p = float(p)
                if p <= 0.0:
                    continue
                next_key = state_key(next_state)
                state_store.setdefault(next_key, next_state)
                next_node = (next_key, depth + 1)
                next_cost = cost - math.log(max(p, 1e-12))
                if next_cost + 1e-12 < best_cost.get(next_node, float("inf")):
                    best_cost[next_node] = next_cost
                    parent[next_node] = (key, depth, action.name, p)
                    push_counter += 1
                    heapq.heappush(queue, (next_cost, depth + 1, push_counter, next_key))

    if best_goal_node is None:
        return 0.0, [], initial_state

    # Reconstruct path.
    actions: List[str] = []
    prob = 1.0
    node = best_goal_node
    final_state = state_store[node[0]]
    while node in parent:
        prev_key, prev_depth, action_name, p = parent[node]
        actions.append(action_name)
        prob *= float(p)
        node = (prev_key, prev_depth)
    actions.reverse()
    return prob, actions, final_state


# ---------------------------------------------------------------------------
# Output and debugging
# ---------------------------------------------------------------------------

def extract_stack_actions(action_history: Sequence[str]) -> List[Tuple[str, str]]:
    """Extract physical stack commands as (below, above)."""
    result: List[Tuple[str, str]] = []
    for action_name in action_history:
        parts = action_name.split()
        if len(parts) == 3 and parts[0].startswith("stack"):
            result.append((parts[1], parts[2]))
    return result


def write_plan(plan_path: str,
               object_infos: Dict[str, Dict[str, float]],
               expected_probability: float,
               stack_actions: Sequence[Tuple[str, str]],
               goal_reached_in_rollout: bool) -> None:
    with open(plan_path, "w") as f:
        if object_infos:
            f.write(f"{len(object_infos)}\n")
            for name, info in object_infos.items():
                f.write(f"{name} {info['x']:.5f} {info['y']:.5f} {info['size']:.5f}\n")

        f.write(f"plan probability: {expected_probability:.6f}\n")
        if expected_probability > 0.0 and stack_actions:
            for below, above in stack_actions:
                f.write(f"stack {below.upper()} {above.upper()}\n")
        elif goal_reached_in_rollout:
            # No physical stack may be needed for a trivial goal.
            pass
        else:
            f.write("not found.\n")


def debug_action(action_name: str) -> None:
    parts = action_name.split()
    base = parts[0]
    dist = OPERATOR_EFFECT_DISTS.get(base)
    if dist is None:
        print("        auxiliary/deterministic")
        return
    dist_str = ", ".join(f"{k}:{v:.3f}" for k, v in sorted(dist.items()))
    print(f"        learned_dist=[{dist_str}]")


def main() -> None:
    parser = argparse.ArgumentParser("Railroad expected-reachability planner for DeepSym.")
    parser.add_argument("-opts", type=str, required=True, help="option file")
    parser.add_argument("-goal", type=str, default="(H3)", help="DeepSym goal, e.g. '(H3)' or '(S4)'")
    parser.add_argument("-max-steps", type=int, default=25, help="finite-horizon planning depth in symbolic actions")
    parser.add_argument("--debug-actions", action="store_true", help="print chosen actions and learned distributions")
    parser.add_argument(
        "--rollout-outcome",
        choices=["contribution", "probability", "value", "progress"],
        default="progress",
        help="how to choose representative outcome branches for policy-rollout plan.txt",
    )
    parser.add_argument(
        "--plan-output",
        choices=["maxprob-linear", "policy-rollout"],
        default="maxprob-linear",
        help=(
            "maxprob-linear writes the highest-probability single executable success path; "
            "policy-rollout writes one branch of the expected-reachability policy."
        ),
    )
    args = parser.parse_args()

    opts = yaml.safe_load(open(args.opts, "r"))
    save_dir = opts["save"]

    operators_path = os.path.join(save_dir, "railroad_operators.json")
    if not os.path.exists(operators_path):
        print(f"ERROR: Railroad operators not found at {operators_path}")
        print("Run learn_rules_railroad.py first.")
        sys.exit(1)

    all_operators = load_operators_from_json(operators_path)
    print(f"Loaded and reconstructed {len(all_operators)} probabilistic/auxiliary operators")

    scene_path = os.path.join(save_dir, "railroad_problem.json")
    objects_path = os.path.join(save_dir, "objects.txt")
    objects, obj_types, relations, counters, object_infos = parse_problem_railroad(scene_path, objects_path)

    print(f"Objects: {objects}")
    print(f"Types: {obj_types}")
    print(f"Relations: {len(relations)}")

    initial_state, objects_by_type = build_initial_state(objects, obj_types, relations, counters)
    print(f"Initial state built with {len(initial_state.fluents)} fluents")

    all_actions = []
    for op in all_operators:
        all_actions.extend(op.instantiate(objects_by_type))
    all_actions.sort(key=lambda a: a.name)
    print(f"Grounded {len(all_actions)} actions from {len(all_operators)} operators")

    goal = parse_deepsym_goal(args.goal)
    print(f"Goal: {goal}")

    print("\n=== Starting Railroad expected-reachability planning ===")
    expected_p, policy, state_store, outcome_cache, value_fn = expected_reachability_plan(
        initial_state,
        goal,
        all_actions,
        args.max_steps,
        debug=args.debug_actions,
    )

    print(f"Expected closed-loop/policy probability within {args.max_steps} symbolic actions: {expected_p:.6f}")

    if args.plan_output == "maxprob-linear":
        plan_probability, history, rollout_final_state = max_probability_linear_plan(
            initial_state, goal, all_actions, args.max_steps
        )
        rollout_goal = bool(goal.evaluate(rollout_final_state))
        print(f"Max-probability linear plan reaches goal: {rollout_goal}")
        print(f"Max-probability linear plan probability: {plan_probability:.6f}")
    else:
        history, rollout_final_state, plan_probability = rollout_policy(
            initial_state,
            goal,
            all_actions,
            args.max_steps,
            policy,
            outcome_cache,
            value_fn,
            args.rollout_outcome,
        )
        rollout_goal = bool(goal.evaluate(rollout_final_state))
        print(f"Representative policy rollout reaches goal: {rollout_goal}")
        print(f"Representative branch probability: {plan_probability:.6f}")

    if history:
        for i, act in enumerate(history):
            print(f"Step {i}: {act}")
            if args.debug_actions:
                debug_action(act)
    else:
        print("No action selected.")

    stack_actions = extract_stack_actions(history)

    plan_path = os.path.join(save_dir, "plan.txt")
    write_plan(plan_path, object_infos, plan_probability, stack_actions, rollout_goal)

    print(f"\n=== Plan written to {plan_path} ===")
    print(f"Expected closed-loop/policy probability: {expected_p:.6f}")
    print(f"Written linear plan probability: {plan_probability:.6f}")
    print(f"Symbolic actions in written plan: {len(history)}")
    print(f"Physical stack actions in written plan: {len(stack_actions)}")
    for below, above in stack_actions:
        print(f"  stack {above} on {below}")


if __name__ == "__main__":
    main()