"""Railroad expected-reachability planner for DeepSym.

This version keeps the learned probabilistic effect branches instead of turning
all actions into nominal deterministic success branches. It computes a finite-
horizon expected reachability value:

    V(s, h) = 1                                      if goal(s)
            = 0                                      if h == 0
            = max_a sum_{s'} P(s' | s, a) V(s', h-1) otherwise

Important execution note
------------------------
This is a policy/value planner. DeepSym's current execute_plan.py still expects
one fixed plan.txt. Therefore this script writes a representative rollout of the
policy by following the outcome branch that contributes most to expected value.
That plan.txt is useful for debugging and for approximate open-loop execution,
but the full benefit of expected-reachability planning requires a closed-loop
executor:

    observe -> build symbolic state -> choose one action -> execute -> observe -> replan

Usage:
    python make_plan_railroad.py -opts opts.yaml -goal "(H3)" --debug-actions
"""

import argparse
import json
import math
import os
import re
import sys
from functools import lru_cache
from typing import Dict, Iterable, List, Optional, Sequence, Tuple

import yaml

from railroad._bindings import AndGoal, Fluent as F, LiteralGoal, State
from railroad.core import Effect, Operator, transition
from railroad.planner import get_usable_actions


# Full learned effect distribution by original stack operator name.
OPERATOR_EFFECT_DISTS: Dict[str, Dict[str, float]] = {}


# ---------------------------------------------------------------------------
# Probability helpers
# ---------------------------------------------------------------------------

def _normalize_effect_distribution(prob_effects: Sequence[Dict], *, op_name: str) -> List[Dict]:
    """Merge duplicate effects and normalize probabilities.

    A true probabilistic transition needs a valid distribution. Learned JSON
    generated by learn_rules_railroad.py should already sum to 1; this function
    also protects against manual edits during debugging.
    """
    merged: Dict[str, float] = {}
    for pe in prob_effects:
        name = str(pe["effect_name"])
        p = float(pe["probability"])
        if p <= 0.0:
            continue
        merged[name] = merged.get(name, 0.0) + p

    total = sum(merged.values())
    if total <= 0.0:
        raise ValueError(f"Operator {op_name} has an empty effect distribution")

    if abs(total - 1.0) > 1e-6:
        print(
            f"WARNING: probabilities for {op_name} sum to {total:.6f}; normalizing.",
            file=sys.stderr,
        )

    return [
        {"probability": p / total, "effect_name": name}
        for name, p in sorted(merged.items())
    ]


# ---------------------------------------------------------------------------
# Railroad operator reconstruction
# ---------------------------------------------------------------------------

def _effect_fluents(effect_name: str) -> set:
    """Map a DeepSym effect label to Railroad fluents."""
    effect_name = str(effect_name)

    if effect_name == "stacked":
        # Original DeepSym PPDDL semantics: stacked also implies inserted.
        return {
            F("stacked"),
            F("inserted"),
            F("instack", "?above"),
            F("stackloc", "?above"),
            ~F("stackloc", "?below"),
        }

    if effect_name == "inserted":
        return {
            F("inserted"),
            F("instack", "?above"),
            F("stackloc", "?above"),
            ~F("stackloc", "?below"),
        }

    # Failure outcomes. These do not intentionally progress the tower, but are
    # kept in the probabilistic state model for expected reachability.
    if effect_name in {"roll1", "roll2", "tumble1", "tumble2"}:
        return {F(effect_name)}

    # Unknown labels are preserved as fluents so the planner can still reason
    # with them if the learned effect set changes.
    return {F(effect_name)}


def build_probabilistic_stack_operator(spec: Dict) -> Operator:
    """Build one probabilistic Railroad Operator from one learned stack rule."""
    below_type = spec.get("below_type", spec.get("obj1_type"))
    above_type = spec.get("above_type", spec.get("obj2_type"))
    if below_type is None or above_type is None:
        raise ValueError(f"Malformed stack operator spec: {spec}")

    op_name = str(spec["name"])
    normalized_effects = _normalize_effect_distribution(spec["prob_effects"], op_name=op_name)
    OPERATOR_EFFECT_DISTS[op_name] = {
        str(pe["effect_name"]): float(pe["probability"])
        for pe in normalized_effects
    }

    preconditions = [
        ~F("stacked"),
        ~F("inserted"),
        F("pickloc", "?above"),
        F("stackloc", "?below"),
        F(below_type, "?below"),
        F(above_type, "?above"),
        F(spec["relation"], "?below", "?above"),
    ]

    prob_branches = []
    for pe in normalized_effects:
        p = float(pe["probability"])
        effect_name = str(pe["effect_name"])
        branch_effect = Effect(
            time=0,
            resulting_fluents=_effect_fluents(effect_name),
        )
        prob_branches.append((p, [branch_effect]))

    probabilistic_effect = Effect(
        time=0,
        resulting_fluents=set(),
        prob_effects=prob_branches,
    )

    # Original PPDDL places (not (pickloc ?above)) outside the probabilistic
    # effect, so the object is consumed regardless of the effect outcome.
    pickloc_removal = Effect(
        time=0,
        resulting_fluents={~F("pickloc", "?above")},
    )

    return Operator(
        name=op_name,
        parameters=[("?below", "object"), ("?above", "object")],
        preconditions=preconditions,
        effects=[probabilistic_effect, pickloc_removal],
    )


def build_auxiliary_operator(spec: Dict) -> Operator:
    """Build deterministic DeepSym bookkeeping operators."""
    if spec["type"] == "increase_height":
        return Operator(
            name=spec["name"],
            parameters=[],
            preconditions=[F("stacked"), F(spec["from_counter"])],
            effects=[Effect(
                time=0,
                resulting_fluents={
                    ~F(spec["from_counter"]),
                    F(spec["to_counter"]),
                    ~F("stacked"),
                },
            )],
        )

    if spec["type"] == "increase_stack":
        return Operator(
            name=spec["name"],
            parameters=[],
            preconditions=[F("inserted"), F(spec["from_counter"])],
            effects=[Effect(
                time=0,
                resulting_fluents={
                    ~F(spec["from_counter"]),
                    F(spec["to_counter"]),
                    ~F("inserted"),
                },
            )],
        )

    if spec["type"] == "makebase":
        return Operator(
            name="makebase",
            parameters=[("?obj", "object")],
            preconditions=[~F("base")],
            effects=[Effect(
                time=0,
                resulting_fluents={
                    F("base"),
                    F("stacked"),
                    F("inserted"),
                    ~F("pickloc", "?obj"),
                    F("stackloc", "?obj"),
                },
            )],
        )

    raise ValueError(f"Unknown auxiliary operator type: {spec['type']}")


def load_operators_from_json(json_path: str) -> List[Operator]:
    """Load learned operator specs and reconstruct Railroad Operators."""
    with open(json_path, "r") as f:
        all_specs = json.load(f)

    OPERATOR_EFFECT_DISTS.clear()

    operators: List[Operator] = []
    for spec in all_specs["stack_operators"]:
        operators.append(build_probabilistic_stack_operator(spec))
    for spec in all_specs["auxiliary_operators"]:
        operators.append(build_auxiliary_operator(spec))
    return operators


# ---------------------------------------------------------------------------
# Problem parsing
# ---------------------------------------------------------------------------

def parse_pddl_goal(goal_str: str):
    """Parse a small PDDL-style goal string into a Railroad goal expression."""
    negative_tokens = set(re.findall(r"\(not\s*\((\w+)\)\)", goal_str))

    without_not_clauses = re.sub(r"\(not\s*\(\w+\)\)", " ", goal_str)
    positive_tokens = [
        tok for tok in re.findall(r"\((\w+)\)", without_not_clauses)
        if tok.lower() not in {"and", "goal"}
    ]

    goals = [LiteralGoal(F(tok)) for tok in positive_tokens]
    goals.extend(LiteralGoal(~F(tok)) for tok in sorted(negative_tokens))

    # DeepSym's generated PDDL goals include these; add them for command-line
    # goal strings like "(H3)" or "(S4)".
    if "stacked" not in negative_tokens:
        goals.append(LiteralGoal(~F("stacked")))
    if "inserted" not in negative_tokens:
        goals.append(LiteralGoal(~F("inserted")))

    if not goals:
        raise ValueError(f"No goal fluents found in: {goal_str}")
    return goals[0] if len(goals) == 1 else AndGoal(goals)


def _extract_parenthesized_section(content: str, start_token: str, end_token: str) -> str:
    start = content.find(start_token)
    if start < 0:
        return ""
    start += len(start_token)
    end = content.find(end_token, start)
    if end < 0:
        end = len(content)
    return content[start:end]


def parse_objects_txt(objects_path: str) -> Dict[str, Dict[str, float]]:
    """Parse DeepSym objects.txt/plan header.

    Format:
        5
        O1 x y size
        ...
    """
    infos: Dict[str, Dict[str, float]] = {}
    if not os.path.exists(objects_path):
        return infos

    with open(objects_path, "r") as f:
        lines = [line.strip() for line in f if line.strip()]
    if not lines:
        return infos

    try:
        n = int(lines[0].split()[0])
    except Exception:
        return infos

    for line in lines[1:1 + n]:
        parts = line.split()
        if len(parts) < 4:
            continue
        infos[parts[0]] = {
            "x": float(parts[1]),
            "y": float(parts[2]),
            "size": float(parts[3]),
        }
    return infos


def parse_problem_pddl(problem_path: str, objects_path: Optional[str] = None):
    """Parse DeepSym problem.pddl for objects, types, relations, and counters."""
    with open(problem_path, "r") as f:
        content = f.read()

    object_infos = parse_objects_txt(objects_path) if objects_path else {}

    objects: List[str] = []
    if object_infos:
        objects = list(object_infos.keys())
    else:
        # Robustly parse only the :objects section, not the whole file.
        m = re.search(r":objects\s+(.*?)\s*\)\s*\(:init", content, re.DOTALL | re.IGNORECASE)
        if m:
            objects = re.findall(r"\bO\d+\b", m.group(1))

    init_block = _extract_parenthesized_section(content, ":init", "(:goal")

    obj_types: Dict[str, str] = {}
    for typ, obj in re.findall(r"\((objtype\d+)\s+(O\d+)\)", init_block):
        obj_types[obj] = typ

    relations: List[Tuple[str, str, str]] = []
    for rel, obj1, obj2 in re.findall(r"\((relation\d+)\s+(O\d+)\s+(O\d+)\)", init_block):
        relations.append((rel, obj1, obj2))

    counters = set(re.findall(r"\((H\d+|S\d+)\)", init_block))

    if not objects:
        # Fall back to any typed object names if the :objects section was absent.
        objects = sorted(obj_types.keys())

    missing_types = [obj for obj in objects if obj not in obj_types]
    if missing_types:
        raise ValueError(f"Objects missing objtype predicates in problem.pddl: {missing_types}")

    return objects, obj_types, relations, counters, object_infos


def build_initial_state(objects: Sequence[str],
                        obj_types: Dict[str, str],
                        relations: Sequence[Tuple[str, str, str]],
                        counters: Iterable[str]):
    fluents = set()

    for obj in objects:
        fluents.add(F("pickloc", obj))

    for obj, typ in obj_types.items():
        fluents.add(F(typ, obj))

    for rel, obj1, obj2 in relations:
        fluents.add(F(rel, obj1, obj2))

    counter_set = set(counters)
    fluents.add(F("H0" if not any(c.startswith("H") for c in counter_set) else next(c for c in counter_set if c.startswith("H"))))
    fluents.add(F("S0" if not any(c.startswith("S") for c in counter_set) else next(c for c in counter_set if c.startswith("S"))))

    return State(fluents=fluents), {"object": set(objects)}


# ---------------------------------------------------------------------------
# Expected reachability planner
# ---------------------------------------------------------------------------

def state_key(state: State) -> Tuple[str, ...]:
    """Hashable state key for DeepSym's zero-time symbolic states."""
    return tuple(sorted(str(f) for f in state.fluents))


def action_base_name(action_name: str) -> str:
    return action_name.split()[0]


def is_stack_action(action_name: str) -> bool:
    base = action_base_name(action_name)
    return base.startswith("stack")


def transition_safe(state: State, action) -> List[Tuple[State, float]]:
    """Call Railroad transition and normalize/merge identical states.

    get_usable_actions can be permissive with generated operators and negated
    fluents. transition() is the final precondition check. If transition rejects
    an action, skip it in the expected-reachability DP instead of crashing.
    """
    try:
        outcomes = transition(state, action)
    except Exception as exc:
        msg = str(exc)
        if "Precondition not satisfied" in msg or "precondition" in msg.lower():
            return []
        raise

    merged: Dict[Tuple[str, ...], Tuple[State, float]] = {}

    for next_state, p in outcomes:
        p = float(p)
        if p <= 0.0:
            continue
        key = state_key(next_state)
        if key in merged:
            old_state, old_p = merged[key]
            merged[key] = (old_state, old_p + p)
        else:
            merged[key] = (next_state, p)

    total = sum(p for _, p in merged.values())
    if total <= 0.0:
        return []

    return [(s, p / total) for s, p in merged.values()]

def expected_reachability_plan(initial_state: State,
                               goal,
                               all_actions: Sequence,
                               max_steps: int,
                               debug: bool = False):
    """Compute finite-horizon expected reachability and a greedy policy."""
    state_store: Dict[Tuple[str, ...], State] = {state_key(initial_state): initial_state}
    policy: Dict[Tuple[Tuple[str, ...], int], Tuple[Optional[str], float]] = {}
    outcome_cache: Dict[Tuple[Tuple[str, ...], str], List[Tuple[State, float]]] = {}

    # Deterministic ordering for reproducibility. Prefer auxiliary actions when
    # they are immediately useful, then stack actions by name.
    sorted_actions = sorted(all_actions, key=lambda a: a.name)

    def heuristic_action_order(action) -> Tuple[int, str]:
        name = action.name
        if name.startswith("increase_height") or name.startswith("increase_stack"):
            return (0, name)
        if name.startswith("makebase"):
            return (1, name)
        if is_stack_action(name):
            return (2, name)
        return (3, name)

    @lru_cache(maxsize=None)
    def value(key: Tuple[str, ...], depth: int) -> float:
        state = state_store[key]

        if goal.evaluate(state.fluents):
            policy[(key, depth)] = (None, 1.0)
            return 1.0
        if depth <= 0:
            policy[(key, depth)] = (None, 0.0)
            return 0.0

        usable = get_usable_actions(state, sorted_actions)
        usable = sorted(usable, key=heuristic_action_order)
        if not usable:
            policy[(key, depth)] = (None, 0.0)
            return 0.0

        best_action_name: Optional[str] = None
        best_val = -1.0

        for action in usable:
            cache_key = (key, action.name)
            if cache_key not in outcome_cache:
                outcome_cache[cache_key] = transition_safe(state, action)
            outcomes = outcome_cache[cache_key]
            if not outcomes:
                continue

            expected = 0.0
            for next_state, p in outcomes:
                next_key = state_key(next_state)
                state_store.setdefault(next_key, next_state)
                expected += p * value(next_key, depth - 1)

            # Reproducible tie-break: higher expected value, then lower action name.
            if expected > best_val + 1e-12:
                best_val = expected
                best_action_name = action.name

        if best_val < 0.0:
            best_val = 0.0
            best_action_name = None

        policy[(key, depth)] = (best_action_name, best_val)
        return best_val

    start_key = state_key(initial_state)
    start_val = value(start_key, max_steps)

    return start_val, policy, state_store, outcome_cache, value


def choose_representative_outcome(outcomes: Sequence[Tuple[State, float]],
                                  remaining_depth: int,
                                  value_fn,
                                  mode: str) -> Tuple[State, float]:
    """Choose one outcome branch for writing a representative plan.txt."""
    if not outcomes:
        raise ValueError("Cannot choose from empty outcome list")

    if mode == "probability":
        return max(outcomes, key=lambda item: item[1])

    if mode == "value":
        return max(outcomes, key=lambda item: value_fn(state_key(item[0]), remaining_depth))

    # Default: choose the branch with largest contribution p * V(s').
    return max(
        outcomes,
        key=lambda item: item[1] * value_fn(state_key(item[0]), remaining_depth),
    )


def rollout_policy(initial_state: State,
                   goal,
                   all_actions: Sequence,
                   max_steps: int,
                   policy,
                   outcome_cache,
                   value_fn,
                   outcome_mode: str):
    """Roll out the computed policy into one representative action sequence."""
    state = initial_state
    history: List[str] = []
    visited_guard = set()

    action_by_name = {a.name: a for a in all_actions}

    for remaining in range(max_steps, 0, -1):
        if goal.evaluate(state.fluents):
            break

        key = state_key(state)
        guard_key = (key, remaining)
        if guard_key in visited_guard:
            break
        visited_guard.add(guard_key)

        action_name, _ = policy.get((key, remaining), (None, 0.0))
        if action_name is None:
            break
        action = action_by_name[action_name]
        history.append(action.name)

        outcomes = outcome_cache.get((key, action.name))
        if outcomes is None:
            outcomes = transition_safe(state, action)
            outcome_cache[(key, action.name)] = outcomes
        if not outcomes:
            break

        state, _p = choose_representative_outcome(
            outcomes,
            remaining - 1,
            value_fn,
            outcome_mode,
        )

    return history, state


# ---------------------------------------------------------------------------
# Output and debugging
# ---------------------------------------------------------------------------

def extract_stack_actions(action_history: Sequence[str]) -> List[Tuple[str, str]]:
    """Extract physical stack commands as (below, above)."""
    result: List[Tuple[str, str]] = []
    for action_name in action_history:
        parts = action_name.split()
        if len(parts) == 3 and parts[0].startswith("stack"):
            result.append((parts[1], parts[2]))
    return result


def write_plan(plan_path: str,
               object_infos: Dict[str, Dict[str, float]],
               expected_probability: float,
               stack_actions: Sequence[Tuple[str, str]],
               goal_reached_in_rollout: bool) -> None:
    with open(plan_path, "w") as f:
        if object_infos:
            f.write(f"{len(object_infos)}\n")
            for name, info in object_infos.items():
                f.write(f"{name} {info['x']:.5f} {info['y']:.5f} {info['size']:.5f}\n")

        f.write(f"plan probability: {expected_probability:.6f}\n")
        if expected_probability > 0.0 and stack_actions:
            for below, above in stack_actions:
                f.write(f"stack {below.upper()} {above.upper()}\n")
        elif goal_reached_in_rollout:
            # No physical stack may be needed for a trivial goal.
            pass
        else:
            f.write("not found.\n")


def debug_action(action_name: str) -> None:
    parts = action_name.split()
    base = parts[0]
    dist = OPERATOR_EFFECT_DISTS.get(base)
    if dist is None:
        print("        auxiliary/deterministic")
        return
    dist_str = ", ".join(f"{k}:{v:.3f}" for k, v in sorted(dist.items()))
    print(f"        learned_dist=[{dist_str}]")


def main() -> None:
    parser = argparse.ArgumentParser("Railroad expected-reachability planner for DeepSym.")
    parser.add_argument("-opts", type=str, required=True, help="option file")
    parser.add_argument("-goal", type=str, default="(H3)", help="PDDL-style goal, e.g. '(H3)' or '(S4)'")
    parser.add_argument("-max-steps", type=int, default=25, help="finite-horizon planning depth in symbolic actions")
    parser.add_argument("--debug-actions", action="store_true", help="print chosen actions and learned distributions")
    parser.add_argument(
        "--rollout-outcome",
        choices=["contribution", "probability", "value"],
        default="contribution",
        help="how to choose representative outcome branches for writing plan.txt",
    )
    args = parser.parse_args()

    opts = yaml.safe_load(open(args.opts, "r"))
    save_dir = opts["save"]

    operators_path = os.path.join(save_dir, "railroad_operators.json")
    if not os.path.exists(operators_path):
        print(f"ERROR: Railroad operators not found at {operators_path}")
        print("Run learn_rules_railroad.py first.")
        sys.exit(1)

    all_operators = load_operators_from_json(operators_path)
    print(f"Loaded and reconstructed {len(all_operators)} probabilistic/auxiliary operators")

    problem_path = os.path.join(save_dir, "problem.pddl")
    objects_path = os.path.join(save_dir, "objects.txt")
    objects, obj_types, relations, counters, object_infos = parse_problem_pddl(problem_path, objects_path)

    print(f"Objects: {objects}")
    print(f"Types: {obj_types}")
    print(f"Relations: {len(relations)}")

    initial_state, objects_by_type = build_initial_state(objects, obj_types, relations, counters)
    print(f"Initial state built with {len(initial_state.fluents)} fluents")

    all_actions = []
    for op in all_operators:
        all_actions.extend(op.instantiate(objects_by_type))
    all_actions.sort(key=lambda a: a.name)
    print(f"Grounded {len(all_actions)} actions from {len(all_operators)} operators")

    goal = parse_pddl_goal(args.goal)
    print(f"Goal: {goal}")

    print("\n=== Starting Railroad expected-reachability planning ===")
    expected_p, policy, state_store, outcome_cache, value_fn = expected_reachability_plan(
        initial_state,
        goal,
        all_actions,
        args.max_steps,
        debug=args.debug_actions,
    )

    history, rollout_final_state = rollout_policy(
        initial_state,
        goal,
        all_actions,
        args.max_steps,
        policy,
        outcome_cache,
        value_fn,
        args.rollout_outcome,
    )
    rollout_goal = bool(goal.evaluate(rollout_final_state.fluents))

    print(f"Expected probability of reaching goal within {args.max_steps} symbolic actions: {expected_p:.6f}")
    print(f"Representative rollout reaches goal: {rollout_goal}")

    if history:
        for i, act in enumerate(history):
            print(f"Step {i}: {act}")
            if args.debug_actions:
                debug_action(act)
    else:
        print("No action selected by policy.")

    stack_actions = extract_stack_actions(history)

    plan_path = os.path.join(save_dir, "plan.txt")
    write_plan(plan_path, object_infos, expected_p, stack_actions, rollout_goal)

    print(f"\n=== Plan written to {plan_path} ===")
    print(f"Expected plan/policy probability: {expected_p:.6f}")
    print(f"Symbolic rollout actions: {len(history)}")
    print(f"Physical stack actions in representative rollout: {len(stack_actions)}")
    for below, above in stack_actions:
        print(f"  stack {above} on {below}")


if __name__ == "__main__":
    main()