(define (domain stack)
	(:requirements :typing :negative-preconditions :probabilistic-effects :conditional-effects :disjunctive-preconditions)
	(:predicates
		(inserted) 
		(stacked) 
		(roll1) 
		(tumble1) 
		(roll2) 
		(tumble2) (base) 
		(pickloc ?x)
		(instack ?x)
		(stackloc ?x)
		(relation0 ?x ?y)
		(relation1 ?x ?y)
		(objtype0 ?x)
		(objtype1 ?x)
		(objtype2 ?x)
		(objtype3 ?x)
		(H0)
		(H1)
		(H2)
		(H3)
		(H4)
		(H5)
		(H6)
		(S0)
		(S1)
		(S2)
		(S3)
		(S4)
		(S5)
		(S6)
	)
	(:action stack0
		:parameters (?below ?above)
		:precondition (and (not (stacked)) (not (inserted)) (pickloc ?above) (stackloc ?below) (objtype0 ?below) (or (objtype0 ?above) (objtype1 ?above)) (or (relation0 ?below ?above) (relation1 ?below ?above)))
		:effect (and (probabilistic
				 0.000 (and (inserted) (instack ?above) (stackloc ?above) (not (stackloc ?below)))
				 0.052 (and (stacked) (inserted) (instack ?above) (stackloc ?above) (not (stackloc ?below)))
				 0.034 (roll1)
				 0.034 (tumble1)
				 0.000 (roll2)
				 0.879 (tumble2))
				(not (pickloc ?above)))
	)
	(:action stack1
		:parameters (?below ?above)
		:precondition (and (not (stacked)) (not (inserted)) (pickloc ?above) (stackloc ?below) (objtype2 ?below) (or (objtype0 ?above) (objtype1 ?above)) (or (relation0 ?below ?above) (relation1 ?below ?above)))
		:effect (and (probabilistic
				 0.000 (and (inserted) (instack ?above) (stackloc ?above) (not (stackloc ?below)))
				 0.000 (and (stacked) (inserted) (instack ?above) (stackloc ?above) (not (stackloc ?below)))
				 0.000 (roll1)
				 0.000 (tumble1)
				 0.000 (roll2)
				 1.000 (tumble2))
				(not (pickloc ?above)))
	)
	(:action stack2
		:parameters (?below ?above)
		:precondition (and (not (stacked)) (not (inserted)) (pickloc ?above) (stackloc ?below) (objtype0 ?below) (or (objtype0 ?above) (objtype1 ?above)) (or (relation0 ?below ?above) (relation1 ?below ?above)))
		:effect (and (probabilistic
				 0.014 (and (inserted) (instack ?above) (stackloc ?above) (not (stackloc ?below)))
				 0.082 (and (stacked) (inserted) (instack ?above) (stackloc ?above) (not (stackloc ?below)))
				 0.000 (roll1)
				 0.068 (tumble1)
				 0.000 (roll2)
				 0.836 (tumble2))
				(not (pickloc ?above)))
	)
	(:action stack3
		:parameters (?below ?above)
		:precondition (and (not (stacked)) (not (inserted)) (pickloc ?above) (stackloc ?below) (objtype2 ?below) (or (objtype0 ?above) (objtype1 ?above)) (or (relation0 ?below ?above) (relation1 ?below ?above)))
		:effect (and (probabilistic
				 0.000 (and (inserted) (instack ?above) (stackloc ?above) (not (stackloc ?below)))
				 0.000 (and (stacked) (inserted) (instack ?above) (stackloc ?above) (not (stackloc ?below)))
				 0.015 (roll1)
				 0.200 (tumble1)
				 0.000 (roll2)
				 0.785 (tumble2))
				(not (pickloc ?above)))
	)
	(:action stack4
		:parameters (?below ?above)
		:precondition (and (not (stacked)) (not (inserted)) (pickloc ?above) (stackloc ?below) (or (objtype0 ?below) (objtype2 ?below)) (objtype0 ?above) (or (relation0 ?below ?above) (relation1 ?below ?above)))
		:effect (and (probabilistic
				 0.000 (and (inserted) (instack ?above) (stackloc ?above) (not (stackloc ?below)))
				 0.000 (and (stacked) (inserted) (instack ?above) (stackloc ?above) (not (stackloc ?below)))
				 0.036 (roll1)
				 0.145 (tumble1)
				 0.000 (roll2)
				 0.818 (tumble2))
				(not (pickloc ?above)))
	)
	(:action stack5
		:parameters (?below ?above)
		:precondition (and (not (stacked)) (not (inserted)) (pickloc ?above) (stackloc ?below) (or (objtype0 ?below) (objtype2 ?below)) (objtype1 ?above) (or (relation0 ?below ?above) (relation1 ?below ?above)))
		:effect (and (probabilistic
				 0.000 (and (inserted) (instack ?above) (stackloc ?above) (not (stackloc ?below)))
				 0.000 (and (stacked) (inserted) (instack ?above) (stackloc ?above) (not (stackloc ?below)))
				 0.024 (roll1)
				 0.381 (tumble1)
				 0.000 (roll2)
				 0.595 (tumble2))
				(not (pickloc ?above)))
	)
	(:action stack6
		:parameters (?below ?above)
		:precondition (and (not (stacked)) (not (inserted)) (pickloc ?above) (stackloc ?below) (or (objtype0 ?below) (objtype2 ?below)) (objtype0 ?above) (or (relation0 ?below ?above) (relation1 ?below ?above)))
		:effect (and (probabilistic
				 0.000 (and (inserted) (instack ?above) (stackloc ?above) (not (stackloc ?below)))
				 0.000 (and (stacked) (inserted) (instack ?above) (stackloc ?above) (not (stackloc ?below)))
				 0.000 (roll1)
				 0.743 (tumble1)
				 0.000 (roll2)
				 0.257 (tumble2))
				(not (pickloc ?above)))
	)
	(:action stack7
		:parameters (?below ?above)
		:precondition (and (not (stacked)) (not (inserted)) (pickloc ?above) (stackloc ?below) (or (objtype0 ?below) (objtype2 ?below)) (objtype1 ?above) (or (relation0 ?below ?above) (relation1 ?below ?above)))
		:effect (and (probabilistic
				 0.000 (and (inserted) (instack ?above) (stackloc ?above) (not (stackloc ?below)))
				 0.074 (and (stacked) (inserted) (instack ?above) (stackloc ?above) (not (stackloc ?below)))
				 0.000 (roll1)
				 0.481 (tumble1)
				 0.000 (roll2)
				 0.444 (tumble2))
				(not (pickloc ?above)))
	)
	(:action stack8
		:parameters (?below ?above)
		:precondition (and (not (stacked)) (not (inserted)) (pickloc ?above) (stackloc ?below) (objtype0 ?below) (or (objtype0 ?above) (objtype1 ?above)) (or (relation0 ?below ?above) (relation1 ?below ?above)))
		:effect (and (probabilistic
				 0.044 (and (inserted) (instack ?above) (stackloc ?above) (not (stackloc ?below)))
				 0.051 (and (stacked) (inserted) (instack ?above) (stackloc ?above) (not (stackloc ?below)))
				 0.614 (roll1)
				 0.082 (tumble1)
				 0.006 (roll2)
				 0.203 (tumble2))
				(not (pickloc ?above)))
	)
	(:action stack9
		:parameters (?below ?above)
		:precondition (and (not (stacked)) (not (inserted)) (pickloc ?above) (stackloc ?below) (objtype0 ?below) (or (objtype0 ?above) (objtype1 ?above)) (or (relation0 ?below ?above) (relation1 ?below ?above)))
		:effect (and (probabilistic
				 0.048 (and (inserted) (instack ?above) (stackloc ?above) (not (stackloc ?below)))
				 0.024 (and (stacked) (inserted) (instack ?above) (stackloc ?above) (not (stackloc ?below)))
				 0.428 (roll1)
				 0.357 (tumble1)
				 0.000 (roll2)
				 0.143 (tumble2))
				(not (pickloc ?above)))
	)
	(:action stack10
		:parameters (?below ?above)
		:precondition (and (not (stacked)) (not (inserted)) (pickloc ?above) (stackloc ?below) (objtype2 ?below) (or (objtype0 ?above) (objtype1 ?above)) (or (relation0 ?below ?above) (relation1 ?below ?above)))
		:effect (and (probabilistic
				 0.045 (and (inserted) (instack ?above) (stackloc ?above) (not (stackloc ?below)))
				 0.000 (and (stacked) (inserted) (instack ?above) (stackloc ?above) (not (stackloc ?below)))
				 0.621 (roll1)
				 0.227 (tumble1)
				 0.000 (roll2)
				 0.106 (tumble2))
				(not (pickloc ?above)))
	)
	(:action stack11
		:parameters (?below ?above)
		:precondition (and (not (stacked)) (not (inserted)) (pickloc ?above) (stackloc ?below) (objtype2 ?below) (or (objtype0 ?above) (objtype1 ?above)) (or (relation0 ?below ?above) (relation1 ?below ?above)))
		:effect (and (probabilistic
				 0.007 (and (inserted) (instack ?above) (stackloc ?above) (not (stackloc ?below)))
				 0.000 (and (stacked) (inserted) (instack ?above) (stackloc ?above) (not (stackloc ?below)))
				 0.657 (roll1)
				 0.231 (tumble1)
				 0.007 (roll2)
				 0.097 (tumble2))
				(not (pickloc ?above)))
	)
	(:action stack12
		:parameters (?below ?above)
		:precondition (and (not (stacked)) (not (inserted)) (pickloc ?above) (stackloc ?below) (objtype0 ?below) (or (objtype0 ?above) (objtype1 ?above)) (or (relation0 ?below ?above) (relation1 ?below ?above)))
		:effect (and (probabilistic
				 0.304 (and (inserted) (instack ?above) (stackloc ?above) (not (stackloc ?below)))
				 0.000 (and (stacked) (inserted) (instack ?above) (stackloc ?above) (not (stackloc ?below)))
				 0.478 (roll1)
				 0.043 (tumble1)
				 0.130 (roll2)
				 0.043 (tumble2))
				(not (pickloc ?above)))
	)
	(:action stack13
		:parameters (?below ?above)
		:precondition (and (not (stacked)) (not (inserted)) (pickloc ?above) (stackloc ?below) (objtype2 ?below) (or (objtype0 ?above) (objtype1 ?above)) (or (relation0 ?below ?above) (relation1 ?below ?above)))
		:effect (and (probabilistic
				 0.000 (and (inserted) (instack ?above) (stackloc ?above) (not (stackloc ?below)))
				 0.000 (and (stacked) (inserted) (instack ?above) (stackloc ?above) (not (stackloc ?below)))
				 0.750 (roll1)
				 0.200 (tumble1)
				 0.050 (roll2)
				 0.000 (tumble2))
				(not (pickloc ?above)))
	)
	(:action stack14
		:parameters (?below ?above)
		:precondition (and (not (stacked)) (not (inserted)) (pickloc ?above) (stackloc ?below) (objtype0 ?below) (or (objtype0 ?above) (objtype1 ?above)) (or (relation0 ?below ?above) (relation1 ?below ?above)))
		:effect (and (probabilistic
				 0.000 (and (inserted) (instack ?above) (stackloc ?above) (not (stackloc ?below)))
				 0.039 (and (stacked) (inserted) (instack ?above) (stackloc ?above) (not (stackloc ?below)))
				 0.000 (roll1)
				 0.000 (tumble1)
				 0.948 (roll2)
				 0.013 (tumble2))
				(not (pickloc ?above)))
	)
	(:action stack15
		:parameters (?below ?above)
		:precondition (and (not (stacked)) (not (inserted)) (pickloc ?above) (stackloc ?below) (objtype2 ?below) (or (objtype0 ?above) (objtype1 ?above)) (or (relation0 ?below ?above) (relation1 ?below ?above)))
		:effect (and (probabilistic
				 0.000 (and (inserted) (instack ?above) (stackloc ?above) (not (stackloc ?below)))
				 0.000 (and (stacked) (inserted) (instack ?above) (stackloc ?above) (not (stackloc ?below)))
				 0.000 (roll1)
				 0.050 (tumble1)
				 0.950 (roll2)
				 0.000 (tumble2))
				(not (pickloc ?above)))
	)
	(:action stack16
		:parameters (?below ?above)
		:precondition (and (not (stacked)) (not (inserted)) (pickloc ?above) (stackloc ?below) (or (objtype0 ?below) (objtype2 ?below)) (or (objtype2 ?above) (objtype3 ?above)) (or (relation0 ?below ?above) (relation1 ?below ?above)))
		:effect (and (probabilistic
				 0.000 (and (inserted) (instack ?above) (stackloc ?above) (not (stackloc ?below)))
				 1.000 (and (stacked) (inserted) (instack ?above) (stackloc ?above) (not (stackloc ?below)))
				 0.000 (roll1)
				 0.000 (tumble1)
				 0.000 (roll2)
				 0.000 (tumble2))
				(not (pickloc ?above)))
	)
	(:action stack17
		:parameters (?below ?above)
		:precondition (and (not (stacked)) (not (inserted)) (pickloc ?above) (stackloc ?below) (or (objtype0 ?below) (objtype2 ?below)) (or (objtype2 ?above) (objtype3 ?above)) (or (relation0 ?below ?above) (relation1 ?below ?above)))
		:effect (and (probabilistic
				 0.014 (and (inserted) (instack ?above) (stackloc ?above) (not (stackloc ?below)))
				 0.966 (and (stacked) (inserted) (instack ?above) (stackloc ?above) (not (stackloc ?below)))
				 0.000 (roll1)
				 0.000 (tumble1)
				 0.000 (roll2)
				 0.020 (tumble2))
				(not (pickloc ?above)))
	)
	(:action stack18
		:parameters (?below ?above)
		:precondition (and (not (stacked)) (not (inserted)) (pickloc ?above) (stackloc ?below) (or (objtype0 ?below) (objtype2 ?below)) (or (objtype2 ?above) (objtype3 ?above)) (or (relation0 ?below ?above) (relation1 ?below ?above)))
		:effect (and (probabilistic
				 0.038 (and (inserted) (instack ?above) (stackloc ?above) (not (stackloc ?below)))
				 0.275 (and (stacked) (inserted) (instack ?above) (stackloc ?above) (not (stackloc ?below)))
				 0.000 (roll1)
				 0.012 (tumble1)
				 0.000 (roll2)
				 0.675 (tumble2))
				(not (pickloc ?above)))
	)
	(:action stack19
		:parameters (?below ?above)
		:precondition (and (not (stacked)) (not (inserted)) (pickloc ?above) (stackloc ?below) (or (objtype0 ?below) (objtype2 ?below)) (or (objtype2 ?above) (objtype3 ?above)) (relation0 ?below ?above))
		:effect (and (probabilistic
				 0.717 (and (inserted) (instack ?above) (stackloc ?above) (not (stackloc ?below)))
				 0.170 (and (stacked) (inserted) (instack ?above) (stackloc ?above) (not (stackloc ?below)))
				 0.000 (roll1)
				 0.000 (tumble1)
				 0.000 (roll2)
				 0.113 (tumble2))
				(not (pickloc ?above)))
	)
	(:action stack20
		:parameters (?below ?above)
		:precondition (and (not (stacked)) (not (inserted)) (pickloc ?above) (stackloc ?below) (or (objtype0 ?below) (objtype2 ?below)) (or (objtype2 ?above) (objtype3 ?above)) (relation0 ?below ?above))
		:effect (and (probabilistic
				 0.750 (and (inserted) (instack ?above) (stackloc ?above) (not (stackloc ?below)))
				 0.150 (and (stacked) (inserted) (instack ?above) (stackloc ?above) (not (stackloc ?below)))
				 0.000 (roll1)
				 0.000 (tumble1)
				 0.000 (roll2)
				 0.100 (tumble2))
				(not (pickloc ?above)))
	)
	(:action stack21
		:parameters (?below ?above)
		:precondition (and (not (stacked)) (not (inserted)) (pickloc ?above) (stackloc ?below) (or (objtype0 ?below) (objtype2 ?below)) (or (objtype2 ?above) (objtype3 ?above)) (relation0 ?below ?above))
		:effect (and (probabilistic
				 0.590 (and (inserted) (instack ?above) (stackloc ?above) (not (stackloc ?below)))
				 0.231 (and (stacked) (inserted) (instack ?above) (stackloc ?above) (not (stackloc ?below)))
				 0.000 (roll1)
				 0.000 (tumble1)
				 0.000 (roll2)
				 0.179 (tumble2))
				(not (pickloc ?above)))
	)
	(:action stack22
		:parameters (?below ?above)
		:precondition (and (not (stacked)) (not (inserted)) (pickloc ?above) (stackloc ?below) (or (objtype0 ?below) (objtype2 ?below)) (or (objtype2 ?above) (objtype3 ?above)) (relation1 ?below ?above))
		:effect (and (probabilistic
				 0.900 (and (inserted) (instack ?above) (stackloc ?above) (not (stackloc ?below)))
				 0.100 (and (stacked) (inserted) (instack ?above) (stackloc ?above) (not (stackloc ?below)))
				 0.000 (roll1)
				 0.000 (tumble1)
				 0.000 (roll2)
				 0.000 (tumble2))
				(not (pickloc ?above)))
	)
	(:action stack23
		:parameters (?below ?above)
		:precondition (and (not (stacked)) (not (inserted)) (pickloc ?above) (stackloc ?below) (or (objtype1 ?below) (objtype3 ?below)) (or (objtype0 ?above) (objtype1 ?above) (objtype2 ?above) (objtype3 ?above)) (relation0 ?below ?above))
		:effect (and (probabilistic
				 0.000 (and (inserted) (instack ?above) (stackloc ?above) (not (stackloc ?below)))
				 0.994 (and (stacked) (inserted) (instack ?above) (stackloc ?above) (not (stackloc ?below)))
				 0.000 (roll1)
				 0.000 (tumble1)
				 0.000 (roll2)
				 0.006 (tumble2))
				(not (pickloc ?above)))
	)
	(:action stack24
		:parameters (?below ?above)
		:precondition (and (not (stacked)) (not (inserted)) (pickloc ?above) (stackloc ?below) (or (objtype1 ?below) (objtype3 ?below)) (or (objtype0 ?above) (objtype1 ?above) (objtype2 ?above) (objtype3 ?above)) (relation0 ?below ?above))
		:effect (and (probabilistic
				 0.000 (and (inserted) (instack ?above) (stackloc ?above) (not (stackloc ?below)))
				 0.994 (and (stacked) (inserted) (instack ?above) (stackloc ?above) (not (stackloc ?below)))
				 0.003 (roll1)
				 0.000 (tumble1)
				 0.000 (roll2)
				 0.003 (tumble2))
				(not (pickloc ?above)))
	)
	(:action stack25
		:parameters (?below ?above)
		:precondition (and (not (stacked)) (not (inserted)) (pickloc ?above) (stackloc ?below) (or (objtype1 ?below) (objtype3 ?below)) (or (objtype0 ?above) (objtype1 ?above) (objtype2 ?above) (objtype3 ?above)) (relation1 ?below ?above))
		:effect (and (probabilistic
				 0.000 (and (inserted) (instack ?above) (stackloc ?above) (not (stackloc ?below)))
				 0.808 (and (stacked) (inserted) (instack ?above) (stackloc ?above) (not (stackloc ?below)))
				 0.064 (roll1)
				 0.000 (tumble1)
				 0.016 (roll2)
				 0.112 (tumble2))
				(not (pickloc ?above)))
	)
	(:action stack26
		:parameters (?below ?above)
		:precondition (and (not (stacked)) (not (inserted)) (pickloc ?above) (stackloc ?below) (or (objtype1 ?below) (objtype3 ?below)) (or (objtype0 ?above) (objtype1 ?above) (objtype2 ?above) (objtype3 ?above)) (or (relation0 ?below ?above) (relation1 ?below ?above)))
		:effect (and (probabilistic
				 0.053 (and (inserted) (instack ?above) (stackloc ?above) (not (stackloc ?below)))
				 0.560 (and (stacked) (inserted) (instack ?above) (stackloc ?above) (not (stackloc ?below)))
				 0.040 (roll1)
				 0.000 (tumble1)
				 0.000 (roll2)
				 0.347 (tumble2))
				(not (pickloc ?above)))
	)
	(:action stack27
		:parameters (?below ?above)
		:precondition (and (not (stacked)) (not (inserted)) (pickloc ?above) (stackloc ?below) (or (objtype1 ?below) (objtype3 ?below)) (or (objtype0 ?above) (objtype1 ?above) (objtype2 ?above) (objtype3 ?above)) (or (relation0 ?below ?above) (relation1 ?below ?above)))
		:effect (and (probabilistic
				 0.015 (and (inserted) (instack ?above) (stackloc ?above) (not (stackloc ?below)))
				 0.882 (and (stacked) (inserted) (instack ?above) (stackloc ?above) (not (stackloc ?below)))
				 0.000 (roll1)
				 0.000 (tumble1)
				 0.000 (roll2)
				 0.103 (tumble2))
				(not (pickloc ?above)))
	)
	(:action stack28
		:parameters (?below ?above)
		:precondition (and (not (stacked)) (not (inserted)) (pickloc ?above) (stackloc ?below) (or (objtype1 ?below) (objtype3 ?below)) (or (objtype0 ?above) (objtype1 ?above) (objtype2 ?above) (objtype3 ?above)) (or (relation0 ?below ?above) (relation1 ?below ?above)))
		:effect (and (probabilistic
				 0.658 (and (inserted) (instack ?above) (stackloc ?above) (not (stackloc ?below)))
				 0.342 (and (stacked) (inserted) (instack ?above) (stackloc ?above) (not (stackloc ?below)))
				 0.000 (roll1)
				 0.000 (tumble1)
				 0.000 (roll2)
				 0.000 (tumble2))
				(not (pickloc ?above)))
	)
	(:action stack29
		:parameters (?below ?above)
		:precondition (and (not (stacked)) (not (inserted)) (pickloc ?above) (stackloc ?below) (or (objtype1 ?below) (objtype3 ?below)) (or (objtype0 ?above) (objtype1 ?above) (objtype2 ?above) (objtype3 ?above)) (or (relation0 ?below ?above) (relation1 ?below ?above)))
		:effect (and (probabilistic
				 0.000 (and (inserted) (instack ?above) (stackloc ?above) (not (stackloc ?below)))
				 0.372 (and (stacked) (inserted) (instack ?above) (stackloc ?above) (not (stackloc ?below)))
				 0.023 (roll1)
				 0.000 (tumble1)
				 0.000 (roll2)
				 0.605 (tumble2))
				(not (pickloc ?above)))
	)
	(:action stack30
		:parameters (?below ?above)
		:precondition (and (not (stacked)) (not (inserted)) (pickloc ?above) (stackloc ?below) (or (objtype1 ?below) (objtype3 ?below)) (or (objtype0 ?above) (objtype1 ?above) (objtype2 ?above) (objtype3 ?above)) (or (relation0 ?below ?above) (relation1 ?below ?above)))
		:effect (and (probabilistic
				 0.006 (and (inserted) (instack ?above) (stackloc ?above) (not (stackloc ?below)))
				 0.210 (and (stacked) (inserted) (instack ?above) (stackloc ?above) (not (stackloc ?below)))
				 0.006 (roll1)
				 0.019 (tumble1)
				 0.000 (roll2)
				 0.758 (tumble2))
				(not (pickloc ?above)))
	)
	(:action increase-height1
		:precondition (and (stacked) (H0))
		:effect (and (not (H0)) (H1) (not (stacked)))
	)
	(:action increase-height2
		:precondition (and (stacked) (H1))
		:effect (and (not (H1)) (H2) (not (stacked)))
	)
	(:action increase-height3
		:precondition (and (stacked) (H2))
		:effect (and (not (H2)) (H3) (not (stacked)))
	)
	(:action increase-height4
		:precondition (and (stacked) (H3))
		:effect (and (not (H3)) (H4) (not (stacked)))
	)
	(:action increase-height5
		:precondition (and (stacked) (H4))
		:effect (and (not (H4)) (H5) (not (stacked)))
	)
	(:action increase-height6
		:precondition (and (stacked) (H5))
		:effect (and (not (H5)) (H6) (not (stacked)))
	)
	(:action increase-stack1
		:precondition (and (inserted) (S0))
		:effect (and (not (S0)) (S1) (not (inserted)))
	)
	(:action increase-stack2
		:precondition (and (inserted) (S1))
		:effect (and (not (S1)) (S2) (not (inserted)))
	)
	(:action increase-stack3
		:precondition (and (inserted) (S2))
		:effect (and (not (S2)) (S3) (not (inserted)))
	)
	(:action increase-stack4
		:precondition (and (inserted) (S3))
		:effect (and (not (S3)) (S4) (not (inserted)))
	)
	(:action increase-stack5
		:precondition (and (inserted) (S4))
		:effect (and (not (S4)) (S5) (not (inserted)))
	)
	(:action increase-stack6
		:precondition (and (inserted) (S5))
		:effect (and (not (S5)) (S6) (not (inserted)))
	)
	(:action makebase
		:parameters (?obj)
		:precondition (not (base))
		:effect (and (base) (stacked) (inserted) (not (pickloc ?obj)) (stackloc ?obj))
	)
)
