(define (domain stack)
	(:requirements :typing :negative-preconditions :probabilistic-effects :conditional-effects :disjunctive-preconditions)
	(:predicates
		(move1) 
		(inserted) 
		(move2) 
		(move3) 
		(move4) 
		(stacked) (base) 
		(pickloc ?x)
		(instack ?x)
		(stackloc ?x)
		(relation0 ?x ?y)
		(relation1 ?x ?y)
		(objtype0 ?x)
		(objtype1 ?x)
		(objtype2 ?x)
		(objtype3 ?x)
		(H0)
		(H1)
		(H2)
		(H3)
		(H4)
		(H5)
		(H6)
		(S0)
		(S1)
		(S2)
		(S3)
		(S4)
		(S5)
		(S6)
	)
	(:action stack0
		:parameters (?below ?above)
		:precondition (and (not (stacked)) (not (inserted)) (pickloc ?above) (stackloc ?below) (objtype0 ?below) (or (objtype0 ?above) (objtype2 ?above)) (or (relation0 ?below ?above) (relation1 ?below ?above)))
		:effect (and (probabilistic
				 0.000 (move1)
				 0.040 (and (inserted) (instack ?above) (stackloc ?above) (not (stackloc ?below)))
				 0.010 (move2)
				 0.160 (move3)
				 0.780 (move4)
				 0.010 (and (stacked) (inserted) (instack ?above) (stackloc ?above) (not (stackloc ?below))))
				(not (pickloc ?above)))
	)
	(:action stack1
		:parameters (?below ?above)
		:precondition (and (not (stacked)) (not (inserted)) (pickloc ?above) (stackloc ?below) (objtype0 ?below) (objtype1 ?above) (or (relation0 ?below ?above) (relation1 ?below ?above)))
		:effect (and (probabilistic
				 0.090 (move1)
				 0.080 (and (inserted) (instack ?above) (stackloc ?above) (not (stackloc ?below)))
				 0.630 (move2)
				 0.000 (move3)
				 0.020 (move4)
				 0.180 (and (stacked) (inserted) (instack ?above) (stackloc ?above) (not (stackloc ?below))))
				(not (pickloc ?above)))
	)
	(:action stack2
		:parameters (?below ?above)
		:precondition (and (not (stacked)) (not (inserted)) (pickloc ?above) (stackloc ?below) (objtype0 ?below) (objtype3 ?above) (or (relation0 ?below ?above) (relation1 ?below ?above)))
		:effect (and (probabilistic
				 0.010 (move1)
				 0.045 (and (inserted) (instack ?above) (stackloc ?above) (not (stackloc ?below)))
				 0.160 (move2)
				 0.440 (move3)
				 0.215 (move4)
				 0.130 (and (stacked) (inserted) (instack ?above) (stackloc ?above) (not (stackloc ?below))))
				(not (pickloc ?above)))
	)
	(:action stack3
		:parameters (?below ?above)
		:precondition (and (not (stacked)) (not (inserted)) (pickloc ?above) (stackloc ?below) (objtype0 ?below) (objtype3 ?above) (or (relation0 ?below ?above) (relation1 ?below ?above)))
		:effect (and (probabilistic
				 0.000 (move1)
				 0.030 (and (inserted) (instack ?above) (stackloc ?above) (not (stackloc ?below)))
				 0.550 (move2)
				 0.020 (move3)
				 0.220 (move4)
				 0.180 (and (stacked) (inserted) (instack ?above) (stackloc ?above) (not (stackloc ?below))))
				(not (pickloc ?above)))
	)
	(:action stack4
		:parameters (?below ?above)
		:precondition (and (not (stacked)) (not (inserted)) (pickloc ?above) (stackloc ?below) (objtype2 ?below) (or (objtype0 ?above) (objtype1 ?above)) (or (relation0 ?below ?above) (relation1 ?below ?above)))
		:effect (and (probabilistic
				 0.050 (move1)
				 0.250 (and (inserted) (instack ?above) (stackloc ?above) (not (stackloc ?below)))
				 0.520 (move2)
				 0.170 (move3)
				 0.000 (move4)
				 0.010 (and (stacked) (inserted) (instack ?above) (stackloc ?above) (not (stackloc ?below))))
				(not (pickloc ?above)))
	)
	(:action stack5
		:parameters (?below ?above)
		:precondition (and (not (stacked)) (not (inserted)) (pickloc ?above) (stackloc ?below) (objtype2 ?below) (or (objtype0 ?above) (objtype1 ?above)) (or (relation0 ?below ?above) (relation1 ?below ?above)))
		:effect (and (probabilistic
				 0.055 (move1)
				 0.245 (and (inserted) (instack ?above) (stackloc ?above) (not (stackloc ?below)))
				 0.670 (move2)
				 0.015 (move3)
				 0.005 (move4)
				 0.010 (and (stacked) (inserted) (instack ?above) (stackloc ?above) (not (stackloc ?below))))
				(not (pickloc ?above)))
	)
	(:action stack6
		:parameters (?below ?above)
		:precondition (and (not (stacked)) (not (inserted)) (pickloc ?above) (stackloc ?below) (objtype2 ?below) (objtype2 ?above) (or (relation0 ?below ?above) (relation1 ?below ?above)))
		:effect (and (probabilistic
				 0.000 (move1)
				 0.710 (and (inserted) (instack ?above) (stackloc ?above) (not (stackloc ?below)))
				 0.070 (move2)
				 0.220 (move3)
				 0.000 (move4)
				 0.000 (and (stacked) (inserted) (instack ?above) (stackloc ?above) (not (stackloc ?below))))
				(not (pickloc ?above)))
	)
	(:action stack7
		:parameters (?below ?above)
		:precondition (and (not (stacked)) (not (inserted)) (pickloc ?above) (stackloc ?below) (objtype2 ?below) (objtype2 ?above) (or (relation0 ?below ?above) (relation1 ?below ?above)))
		:effect (and (probabilistic
				 0.000 (move1)
				 0.755 (and (inserted) (instack ?above) (stackloc ?above) (not (stackloc ?below)))
				 0.045 (move2)
				 0.200 (move3)
				 0.000 (move4)
				 0.000 (and (stacked) (inserted) (instack ?above) (stackloc ?above) (not (stackloc ?below))))
				(not (pickloc ?above)))
	)
	(:action stack8
		:parameters (?below ?above)
		:precondition (and (not (stacked)) (not (inserted)) (pickloc ?above) (stackloc ?below) (objtype2 ?below) (objtype3 ?above) (or (relation0 ?below ?above) (relation1 ?below ?above)))
		:effect (and (probabilistic
				 0.000 (move1)
				 0.750 (and (inserted) (instack ?above) (stackloc ?above) (not (stackloc ?below)))
				 0.000 (move2)
				 0.250 (move3)
				 0.000 (move4)
				 0.000 (and (stacked) (inserted) (instack ?above) (stackloc ?above) (not (stackloc ?below))))
				(not (pickloc ?above)))
	)
	(:action stack9
		:parameters (?below ?above)
		:precondition (and (not (stacked)) (not (inserted)) (pickloc ?above) (stackloc ?below) (objtype2 ?below) (objtype2 ?above) (or (relation0 ?below ?above) (relation1 ?below ?above)))
		:effect (and (probabilistic
				 0.005 (move1)
				 0.925 (and (inserted) (instack ?above) (stackloc ?above) (not (stackloc ?below)))
				 0.000 (move2)
				 0.070 (move3)
				 0.000 (move4)
				 0.000 (and (stacked) (inserted) (instack ?above) (stackloc ?above) (not (stackloc ?below))))
				(not (pickloc ?above)))
	)
	(:action stack10
		:parameters (?below ?above)
		:precondition (and (not (stacked)) (not (inserted)) (pickloc ?above) (stackloc ?below) (objtype2 ?below) (objtype2 ?above) (or (relation0 ?below ?above) (relation1 ?below ?above)))
		:effect (and (probabilistic
				 0.008 (move1)
				 0.974 (and (inserted) (instack ?above) (stackloc ?above) (not (stackloc ?below)))
				 0.013 (move2)
				 0.005 (move3)
				 0.000 (move4)
				 0.000 (and (stacked) (inserted) (instack ?above) (stackloc ?above) (not (stackloc ?below))))
				(not (pickloc ?above)))
	)
	(:action stack11
		:parameters (?below ?above)
		:precondition (and (not (stacked)) (not (inserted)) (pickloc ?above) (stackloc ?below) (objtype2 ?below) (objtype3 ?above) (or (relation0 ?below ?above) (relation1 ?below ?above)))
		:effect (and (probabilistic
				 0.005 (move1)
				 0.710 (and (inserted) (instack ?above) (stackloc ?above) (not (stackloc ?below)))
				 0.200 (move2)
				 0.070 (move3)
				 0.015 (move4)
				 0.000 (and (stacked) (inserted) (instack ?above) (stackloc ?above) (not (stackloc ?below))))
				(not (pickloc ?above)))
	)
	(:action stack12
		:parameters (?below ?above)
		:precondition (and (not (stacked)) (not (inserted)) (pickloc ?above) (stackloc ?below) (or (objtype1 ?below) (objtype3 ?below)) (or (objtype0 ?above) (objtype2 ?above)) (or (relation0 ?below ?above) (relation1 ?below ?above)))
		:effect (and (probabilistic
				 0.000 (move1)
				 0.000 (and (inserted) (instack ?above) (stackloc ?above) (not (stackloc ?below)))
				 0.000 (move2)
				 0.120 (move3)
				 0.800 (move4)
				 0.080 (and (stacked) (inserted) (instack ?above) (stackloc ?above) (not (stackloc ?below))))
				(not (pickloc ?above)))
	)
	(:action stack13
		:parameters (?below ?above)
		:precondition (and (not (stacked)) (not (inserted)) (pickloc ?above) (stackloc ?below) (or (objtype1 ?below) (objtype3 ?below)) (objtype0 ?above) (or (relation0 ?below ?above) (relation1 ?below ?above)))
		:effect (and (probabilistic
				 0.080 (move1)
				 0.000 (and (inserted) (instack ?above) (stackloc ?above) (not (stackloc ?below)))
				 0.440 (move2)
				 0.010 (move3)
				 0.090 (move4)
				 0.380 (and (stacked) (inserted) (instack ?above) (stackloc ?above) (not (stackloc ?below))))
				(not (pickloc ?above)))
	)
	(:action stack14
		:parameters (?below ?above)
		:precondition (and (not (stacked)) (not (inserted)) (pickloc ?above) (stackloc ?below) (or (objtype1 ?below) (objtype3 ?below)) (objtype2 ?above) (or (relation0 ?below ?above) (relation1 ?below ?above)))
		:effect (and (probabilistic
				 0.050 (move1)
				 0.000 (and (inserted) (instack ?above) (stackloc ?above) (not (stackloc ?below)))
				 0.065 (move2)
				 0.405 (move3)
				 0.245 (move4)
				 0.235 (and (stacked) (inserted) (instack ?above) (stackloc ?above) (not (stackloc ?below))))
				(not (pickloc ?above)))
	)
	(:action stack15
		:parameters (?below ?above)
		:precondition (and (not (stacked)) (not (inserted)) (pickloc ?above) (stackloc ?below) (or (objtype1 ?below) (objtype3 ?below)) (or (objtype1 ?above) (objtype3 ?above)) (or (relation0 ?below ?above) (relation1 ?below ?above)))
		:effect (and (probabilistic
				 0.000 (move1)
				 0.000 (and (inserted) (instack ?above) (stackloc ?above) (not (stackloc ?below)))
				 0.790 (move2)
				 0.000 (move3)
				 0.140 (move4)
				 0.070 (and (stacked) (inserted) (instack ?above) (stackloc ?above) (not (stackloc ?below))))
				(not (pickloc ?above)))
	)
	(:action increase-height1
		:precondition (and (stacked) (H0))
		:effect (and (not (H0)) (H1) (not (stacked)))
	)
	(:action increase-height2
		:precondition (and (stacked) (H1))
		:effect (and (not (H1)) (H2) (not (stacked)))
	)
	(:action increase-height3
		:precondition (and (stacked) (H2))
		:effect (and (not (H2)) (H3) (not (stacked)))
	)
	(:action increase-height4
		:precondition (and (stacked) (H3))
		:effect (and (not (H3)) (H4) (not (stacked)))
	)
	(:action increase-height5
		:precondition (and (stacked) (H4))
		:effect (and (not (H4)) (H5) (not (stacked)))
	)
	(:action increase-height6
		:precondition (and (stacked) (H5))
		:effect (and (not (H5)) (H6) (not (stacked)))
	)
	(:action increase-stack1
		:precondition (and (inserted) (S0))
		:effect (and (not (S0)) (S1) (not (inserted)))
	)
	(:action increase-stack2
		:precondition (and (inserted) (S1))
		:effect (and (not (S1)) (S2) (not (inserted)))
	)
	(:action increase-stack3
		:precondition (and (inserted) (S2))
		:effect (and (not (S2)) (S3) (not (inserted)))
	)
	(:action increase-stack4
		:precondition (and (inserted) (S3))
		:effect (and (not (S3)) (S4) (not (inserted)))
	)
	(:action increase-stack5
		:precondition (and (inserted) (S4))
		:effect (and (not (S4)) (S5) (not (inserted)))
	)
	(:action increase-stack6
		:precondition (and (inserted) (S5))
		:effect (and (not (S5)) (S6) (not (inserted)))
	)
	(:action makebase
		:parameters (?obj)
		:precondition (not (base))
		:effect (and (base) (stacked) (inserted) (not (pickloc ?obj)) (stackloc ?obj))
	)
)
