(define (domain stack)
	(:requirements :typing :negative-preconditions :probabilistic-effects :conditional-effects :disjunctive-preconditions)
	(:predicates
		(inserted)
		(stacked)
		(roll1)
		(tumble1)
		(roll2)
		(tumble2)
		(base)
		(pickloc ?x)
		(instack ?x)
		(stackloc ?x)
		(relation0 ?x ?y)
		(relation1 ?x ?y)
		(objtype0 ?x)
		(objtype1 ?x)
		(objtype2 ?x)
		(objtype3 ?x)
		(H0)
		(H1)
		(H2)
		(H3)
		(H4)
		(H5)
		(H6)
		(S0)
		(S1)
		(S2)
		(S3)
		(S4)
		(S5)
		(S6)
	)
	(:action stack0
		:parameters (?below ?above)
		:precondition (and (not (stacked)) (not (inserted)) (pickloc ?above) (stackloc ?below) (and (objtype3 ?below) (objtype1 ?above) (relation0 ?below ?above)))
		:effect (and (probabilistic 0.032 (and (stacked) (inserted) (instack ?above) (stackloc ?above) (not (stackloc ?below))) 0.016 (roll1) 0.032 (tumble1) 0.920 (tumble2)) (not (pickloc ?above)))
	)
	(:action stack1
		:parameters (?below ?above)
		:precondition (and (not (stacked)) (not (inserted)) (pickloc ?above) (stackloc ?below) (and (objtype1 ?below) (objtype1 ?above) (relation0 ?below ?above)))
		:effect (and (probabilistic 0.013 (and (stacked) (inserted) (instack ?above) (stackloc ?above) (not (stackloc ?below))) 0.038 (roll1) 0.013 (tumble1) 0.936 (tumble2)) (not (pickloc ?above)))
	)
	(:action stack2
		:parameters (?below ?above)
		:precondition (and (not (stacked)) (not (inserted)) (pickloc ?above) (stackloc ?below) (and (objtype3 ?below) (objtype3 ?above) (relation0 ?below ?above)))
		:effect (and (probabilistic 0.019 (and (inserted) (instack ?above) (stackloc ?above) (not (stackloc ?below))) 0.148 (and (stacked) (inserted) (instack ?above) (stackloc ?above) (not (stackloc ?below))) 0.056 (tumble1) 0.777 (tumble2)) (not (pickloc ?above)))
	)
	(:action stack3
		:parameters (?below ?above)
		:precondition (and (not (stacked)) (not (inserted)) (pickloc ?above) (stackloc ?below) (and (objtype1 ?below) (objtype3 ?above) (relation0 ?below ?above)))
		:effect (and (probabilistic 0.016 (roll1) 0.238 (tumble1) 0.746 (tumble2)) (not (pickloc ?above)))
	)
	(:action stack4
		:parameters (?below ?above)
		:precondition (and (not (stacked)) (not (inserted)) (pickloc ?above) (stackloc ?below) (and (objtype1 ?below) (objtype3 ?above) (relation1 ?below ?above)))
		:effect (and (probabilistic 0.694 (tumble1) 0.306 (tumble2)) (not (pickloc ?above)))
	)
	(:action stack5
		:parameters (?below ?above)
		:precondition (and (not (stacked)) (not (inserted)) (pickloc ?above) (stackloc ?below) (and (objtype3 ?below) (objtype3 ?above) (relation1 ?below ?above)))
		:effect (and (probabilistic 0.519 (tumble1) 0.481 (tumble2)) (not (pickloc ?above)))
	)
	(:action stack6
		:parameters (?below ?above)
		:precondition (and (not (stacked)) (not (inserted)) (pickloc ?above) (stackloc ?below) (and (objtype1 ?below) (objtype1 ?above) (relation1 ?below ?above)))
		:effect (and (probabilistic 0.023 (roll1) 0.163 (tumble1) 0.814 (tumble2)) (not (pickloc ?above)))
	)
	(:action stack7
		:parameters (?below ?above)
		:precondition (and (not (stacked)) (not (inserted)) (pickloc ?above) (stackloc ?below) (and (objtype3 ?below) (objtype1 ?above) (relation1 ?below ?above)))
		:effect (and (probabilistic 0.432 (tumble1) 0.568 (tumble2)) (not (pickloc ?above)))
	)
	(:action stack8
		:parameters (?below ?above)
		:precondition (and (not (stacked)) (not (inserted)) (pickloc ?above) (stackloc ?below) (and (objtype1 ?below) (objtype2 ?above) (relation0 ?below ?above)))
		:effect (and (probabilistic 0.012 (and (inserted) (instack ?above) (stackloc ?above) (not (stackloc ?below))) 0.006 (and (stacked) (inserted) (instack ?above) (stackloc ?above) (not (stackloc ?below))) 0.632 (roll1) 0.211 (tumble1) 0.006 (roll2) 0.133 (tumble2)) (not (pickloc ?above)))
	)
	(:action stack9
		:parameters (?below ?above)
		:precondition (and (not (stacked)) (not (inserted)) (pickloc ?above) (stackloc ?below) (and (objtype3 ?below) (objtype2 ?above) (relation0 ?below ?above)))
		:effect (and (probabilistic 0.043 (and (inserted) (instack ?above) (stackloc ?above) (not (stackloc ?below))) 0.050 (and (stacked) (inserted) (instack ?above) (stackloc ?above) (not (stackloc ?below))) 0.636 (roll1) 0.093 (tumble1) 0.007 (roll2) 0.171 (tumble2)) (not (pickloc ?above)))
	)
	(:action stack10
		:parameters (?below ?above)
		:precondition (and (not (stacked)) (not (inserted)) (pickloc ?above) (stackloc ?below) (and (objtype1 ?below) (objtype2 ?above) (relation1 ?below ?above)))
		:effect (and (probabilistic 0.056 (and (inserted) (instack ?above) (stackloc ?above) (not (stackloc ?below))) 0.610 (roll1) 0.241 (tumble1) 0.093 (tumble2)) (not (pickloc ?above)))
	)
	(:action stack11
		:parameters (?below ?above)
		:precondition (and (not (stacked)) (not (inserted)) (pickloc ?above) (stackloc ?below) (and (objtype3 ?below) (objtype2 ?above) (relation1 ?below ?above)))
		:effect (and (probabilistic 0.050 (and (inserted) (instack ?above) (stackloc ?above) (not (stackloc ?below))) 0.025 (and (stacked) (inserted) (instack ?above) (stackloc ?above) (not (stackloc ?below))) 0.425 (roll1) 0.325 (tumble1) 0.175 (tumble2)) (not (pickloc ?above)))
	)
	(:action stack12
		:parameters (?below ?above)
		:precondition (and (not (stacked)) (not (inserted)) (pickloc ?above) (stackloc ?below) (and (objtype1 ?below) (objtype0 ?above) (relation1 ?below ?above)))
		:effect (and (probabilistic 0.696 (roll1) 0.174 (tumble1) 0.087 (roll2) 0.043 (tumble2)) (not (pickloc ?above)))
	)
	(:action stack13
		:parameters (?below ?above)
		:precondition (and (not (stacked)) (not (inserted)) (pickloc ?above) (stackloc ?below) (and (objtype3 ?below) (objtype0 ?above) (relation1 ?below ?above)))
		:effect (and (probabilistic 0.333 (and (inserted) (instack ?above) (stackloc ?above) (not (stackloc ?below))) 0.476 (roll1) 0.048 (tumble1) 0.143 (roll2)) (not (pickloc ?above)))
	)
	(:action stack14
		:parameters (?below ?above)
		:precondition (and (not (stacked)) (not (inserted)) (pickloc ?above) (stackloc ?below) (and (objtype3 ?below) (objtype0 ?above) (relation0 ?below ?above)))
		:effect (and (probabilistic 0.043 (and (stacked) (inserted) (instack ?above) (stackloc ?above) (not (stackloc ?below))) 0.957 (roll2)) (not (pickloc ?above)))
	)
	(:action stack15
		:parameters (?below ?above)
		:precondition (and (not (stacked)) (not (inserted)) (pickloc ?above) (stackloc ?below) (and (objtype1 ?below) (objtype0 ?above) (relation0 ?below ?above)))
		:effect (and (probabilistic 0.046 (tumble1) 0.943 (roll2) 0.011 (tumble2)) (not (pickloc ?above)))
	)
	(:action stack16
		:parameters (?below ?above)
		:precondition (and (not (stacked)) (not (inserted)) (pickloc ?above) (stackloc ?below) (and (objtype0 ?below) (objtype2 ?above) (relation0 ?below ?above)))
		:effect (and (probabilistic 0.690 (and (inserted) (instack ?above) (stackloc ?above) (not (stackloc ?below))) 0.207 (and (stacked) (inserted) (instack ?above) (stackloc ?above) (not (stackloc ?below))) 0.103 (tumble2)) (not (pickloc ?above)))
	)
	(:action stack17
		:parameters (?below ?above)
		:precondition (and (not (stacked)) (not (inserted)) (pickloc ?above) (stackloc ?below) (and (objtype0 ?below) (objtype1 ?above) (relation0 ?below ?above)))
		:effect (and (probabilistic 0.695 (and (inserted) (instack ?above) (stackloc ?above) (not (stackloc ?below))) 0.222 (and (stacked) (inserted) (instack ?above) (stackloc ?above) (not (stackloc ?below))) 0.083 (tumble2)) (not (pickloc ?above)))
	)
	(:action stack18
		:parameters (?below ?above)
		:precondition (and (not (stacked)) (not (inserted)) (pickloc ?above) (stackloc ?below) (and (objtype0 ?below) (objtype0 ?above) (relation0 ?below ?above)))
		:effect (and (probabilistic 0.028 (and (inserted) (instack ?above) (stackloc ?above) (not (stackloc ?below))) 0.972 (and (stacked) (inserted) (instack ?above) (stackloc ?above) (not (stackloc ?below)))) (not (pickloc ?above)))
	)
	(:action stack19
		:parameters (?below ?above)
		:precondition (and (not (stacked)) (not (inserted)) (pickloc ?above) (stackloc ?below) (and (objtype0 ?below) (objtype1 ?above) (relation1 ?below ?above)))
		:effect (and (probabilistic 0.027 (and (inserted) (instack ?above) (stackloc ?above) (not (stackloc ?below))) 0.878 (and (stacked) (inserted) (instack ?above) (stackloc ?above) (not (stackloc ?below))) 0.095 (tumble2)) (not (pickloc ?above)))
	)
	(:action stack20
		:parameters (?below ?above)
		:precondition (and (not (stacked)) (not (inserted)) (pickloc ?above) (stackloc ?below) (and (objtype0 ?below) (objtype2 ?above) (relation1 ?below ?above)))
		:effect (and (probabilistic 0.979 (and (stacked) (inserted) (instack ?above) (stackloc ?above) (not (stackloc ?below))) 0.021 (tumble2)) (not (pickloc ?above)))
	)
	(:action stack21
		:parameters (?below ?above)
		:precondition (and (not (stacked)) (not (inserted)) (pickloc ?above) (stackloc ?below) (and (objtype0 ?below) (objtype0 ?above) (relation1 ?below ?above)))
		:effect (and (probabilistic 0.725 (and (inserted) (instack ?above) (stackloc ?above) (not (stackloc ?below))) 0.034 (and (stacked) (inserted) (instack ?above) (stackloc ?above) (not (stackloc ?below))) 0.241 (tumble2)) (not (pickloc ?above)))
	)
	(:action stack22
		:parameters (?below ?above)
		:precondition (and (not (stacked)) (not (inserted)) (pickloc ?above) (stackloc ?below) (and (objtype0 ?below) (objtype3 ?above) (relation1 ?below ?above)))
		:effect (and (probabilistic 0.323 (and (stacked) (inserted) (instack ?above) (stackloc ?above) (not (stackloc ?below))) 0.015 (tumble1) 0.662 (tumble2)) (not (pickloc ?above)))
	)
	(:action stack23
		:parameters (?below ?above)
		:precondition (and (not (stacked)) (not (inserted)) (pickloc ?above) (stackloc ?below) (and (objtype0 ?below) (objtype3 ?above) (relation0 ?below ?above)))
		:effect (and (probabilistic 0.720 (and (inserted) (instack ?above) (stackloc ?above) (not (stackloc ?below))) 0.160 (and (stacked) (inserted) (instack ?above) (stackloc ?above) (not (stackloc ?below))) 0.120 (tumble2)) (not (pickloc ?above)))
	)
	(:action stack24
		:parameters (?below ?above)
		:precondition (and (not (stacked)) (not (inserted)) (pickloc ?above) (stackloc ?below) (and (objtype2 ?below) (objtype0 ?above) (relation1 ?below ?above)))
		:effect (and (probabilistic 0.610 (and (inserted) (instack ?above) (stackloc ?above) (not (stackloc ?below))) 0.390 (and (stacked) (inserted) (instack ?above) (stackloc ?above) (not (stackloc ?below)))) (not (pickloc ?above)))
	)
	(:action stack25
		:parameters (?below ?above)
		:precondition (and (not (stacked)) (not (inserted)) (pickloc ?above) (stackloc ?below) (and (objtype2 ?below) (objtype2 ?above) (relation1 ?below ?above)))
		:effect (and (probabilistic 0.021 (and (inserted) (instack ?above) (stackloc ?above) (not (stackloc ?below))) 0.854 (and (stacked) (inserted) (instack ?above) (stackloc ?above) (not (stackloc ?below))) 0.125 (tumble2)) (not (pickloc ?above)))
	)
	(:action stack26
		:parameters (?below ?above)
		:precondition (and (not (stacked)) (not (inserted)) (pickloc ?above) (stackloc ?below) (and (objtype2 ?below) (objtype0 ?above) (relation0 ?below ?above)))
		:effect (and (probabilistic 0.994 (and (stacked) (inserted) (instack ?above) (stackloc ?above) (not (stackloc ?below))) 0.006 (tumble2)) (not (pickloc ?above)))
	)
	(:action stack27
		:parameters (?below ?above)
		:precondition (and (not (stacked)) (not (inserted)) (pickloc ?above) (stackloc ?below) (and (objtype2 ?below) (objtype2 ?above) (relation0 ?below ?above)))
		:effect (and (probabilistic 0.991 (and (stacked) (inserted) (instack ?above) (stackloc ?above) (not (stackloc ?below))) 0.003 (roll1) 0.006 (tumble2)) (not (pickloc ?above)))
	)
	(:action stack28
		:parameters (?below ?above)
		:precondition (and (not (stacked)) (not (inserted)) (pickloc ?above) (stackloc ?below) (and (objtype2 ?below) (objtype1 ?above) (relation1 ?below ?above)))
		:effect (and (probabilistic 0.067 (and (inserted) (instack ?above) (stackloc ?above) (not (stackloc ?below))) 0.489 (and (stacked) (inserted) (instack ?above) (stackloc ?above) (not (stackloc ?below))) 0.044 (roll1) 0.400 (tumble2)) (not (pickloc ?above)))
	)
	(:action stack29
		:parameters (?below ?above)
		:precondition (and (not (stacked)) (not (inserted)) (pickloc ?above) (stackloc ?below) (and (objtype2 ?below) (objtype1 ?above) (relation0 ?below ?above)))
		:effect (and (probabilistic 0.006 (and (inserted) (instack ?above) (stackloc ?above) (not (stackloc ?below))) 0.692 (and (stacked) (inserted) (instack ?above) (stackloc ?above) (not (stackloc ?below))) 0.051 (roll1) 0.011 (roll2) 0.240 (tumble2)) (not (pickloc ?above)))
	)
	(:action stack30
		:parameters (?below ?above)
		:precondition (and (not (stacked)) (not (inserted)) (pickloc ?above) (stackloc ?below) (and (objtype2 ?below) (objtype3 ?above) (relation0 ?below ?above)))
		:effect (and (probabilistic 0.007 (and (inserted) (instack ?above) (stackloc ?above) (not (stackloc ?below))) 0.240 (and (stacked) (inserted) (instack ?above) (stackloc ?above) (not (stackloc ?below))) 0.007 (roll1) 0.021 (tumble1) 0.725 (tumble2)) (not (pickloc ?above)))
	)
	(:action stack31
		:parameters (?below ?above)
		:precondition (and (not (stacked)) (not (inserted)) (pickloc ?above) (stackloc ?below) (and (objtype2 ?below) (objtype3 ?above) (relation1 ?below ?above)))
		:effect (and (probabilistic 0.412 (and (stacked) (inserted) (instack ?above) (stackloc ?above) (not (stackloc ?below))) 0.029 (roll1) 0.559 (tumble2)) (not (pickloc ?above)))
	)
	(:action increase-height1
		:precondition (and (stacked) (H0))
		:effect (and (not (H0)) (H1) (not (stacked)))
	)
	(:action increase-height2
		:precondition (and (stacked) (H1))
		:effect (and (not (H1)) (H2) (not (stacked)))
	)
	(:action increase-height3
		:precondition (and (stacked) (H2))
		:effect (and (not (H2)) (H3) (not (stacked)))
	)
	(:action increase-height4
		:precondition (and (stacked) (H3))
		:effect (and (not (H3)) (H4) (not (stacked)))
	)
	(:action increase-height5
		:precondition (and (stacked) (H4))
		:effect (and (not (H4)) (H5) (not (stacked)))
	)
	(:action increase-height6
		:precondition (and (stacked) (H5))
		:effect (and (not (H5)) (H6) (not (stacked)))
	)
	(:action increase-stack1
		:precondition (and (inserted) (S0))
		:effect (and (not (S0)) (S1) (not (inserted)))
	)
	(:action increase-stack2
		:precondition (and (inserted) (S1))
		:effect (and (not (S1)) (S2) (not (inserted)))
	)
	(:action increase-stack3
		:precondition (and (inserted) (S2))
		:effect (and (not (S2)) (S3) (not (inserted)))
	)
	(:action increase-stack4
		:precondition (and (inserted) (S3))
		:effect (and (not (S3)) (S4) (not (inserted)))
	)
	(:action increase-stack5
		:precondition (and (inserted) (S4))
		:effect (and (not (S4)) (S5) (not (inserted)))
	)
	(:action increase-stack6
		:precondition (and (inserted) (S5))
		:effect (and (not (S5)) (S6) (not (inserted)))
	)
	(:action makebase
		:parameters (?obj)
		:precondition (not (base))
		:effect (and (base) (stacked) (inserted) (not (pickloc ?obj)) (stackloc ?obj))
	)
)
(define (problem dom1) (:domain stack)
	(:objects O1 O2 O3 O4 O5)
	(:init
		(pickloc O1) (objtype0 O1)
		(pickloc O2) (objtype1 O2)
		(pickloc O3) (objtype3 O3)
		(pickloc O4) (objtype2 O4)
		(pickloc O5) (objtype1 O5)
		(relation1 O1 O2)
		(relation0 O1 O3)
		(relation0 O1 O4)
		(relation0 O1 O5)
		(relation0 O2 O1)
		(relation0 O2 O3)
		(relation0 O2 O4)
		(relation0 O2 O5)
		(relation0 O3 O1)
		(relation0 O3 O2)
		(relation0 O3 O4)
		(relation0 O3 O5)
		(relation0 O4 O1)
		(relation1 O4 O2)
		(relation1 O4 O3)
		(relation0 O4 O5)
		(relation0 O5 O1)
		(relation1 O5 O2)
		(relation1 O5 O3)
		(relation1 O5 O4)
		(H0)
		(S0)
	)
	(:goal (and (H1) (S2) (not (stacked)) (not (inserted))))
)
