(define (domain stack)
	(:requirements :typing :negative-preconditions :probabilistic-effects :conditional-effects :disjunctive-preconditions)
	(:predicates
		(inserted)
		(stacked)
		(roll1)
		(tumble1)
		(roll2)
		(tumble2)
		(base)
		(pickloc ?x)
		(instack ?x)
		(stackloc ?x)
		(relation0 ?x ?y)
		(relation1 ?x ?y)
		(objtype0 ?x)
		(objtype1 ?x)
		(objtype2 ?x)
		(objtype3 ?x)
		(H0)
		(H1)
		(H2)
		(H3)
		(H4)
		(H5)
		(H6)
		(S0)
		(S1)
		(S2)
		(S3)
		(S4)
		(S5)
		(S6)
	)
	(:action stack0
		:parameters (?below ?above)
		:precondition (and (not (stacked)) (not (inserted)) (pickloc ?above) (stackloc ?below) (and (objtype0 ?below) (objtype0 ?above) (relation0 ?below ?above)))
		:effect (and (probabilistic 0.026 (roll1) 0.184 (tumble1) 0.790 (tumble2)) (not (pickloc ?above)))
	)
	(:action stack1
		:parameters (?below ?above)
		:precondition (and (not (stacked)) (not (inserted)) (pickloc ?above) (stackloc ?below) (and (objtype3 ?below) (objtype0 ?above) (relation0 ?below ?above)))
		:effect (and (probabilistic 0.385 (tumble1) 0.615 (tumble2)) (not (pickloc ?above)))
	)
	(:action stack2
		:parameters (?below ?above)
		:precondition (and (not (stacked)) (not (inserted)) (pickloc ?above) (stackloc ?below) (and (objtype0 ?below) (objtype3 ?above) (relation0 ?below ?above)))
		:effect (and (probabilistic 0.778 (tumble1) 0.222 (tumble2)) (not (pickloc ?above)))
	)
	(:action stack3
		:parameters (?below ?above)
		:precondition (and (not (stacked)) (not (inserted)) (pickloc ?above) (stackloc ?below) (and (objtype3 ?below) (objtype3 ?above) (relation0 ?below ?above)))
		:effect (and (probabilistic 0.038 (and (stacked) (inserted) (instack ?above) (stackloc ?above) (not (stackloc ?below))) 0.539 (tumble1) 0.423 (tumble2)) (not (pickloc ?above)))
	)
	(:action stack4
		:parameters (?below ?above)
		:precondition (and (not (stacked)) (not (inserted)) (pickloc ?above) (stackloc ?below) (and (objtype0 ?below) (objtype0 ?above) (relation1 ?below ?above)))
		:effect (and (probabilistic 0.016 (roll1) 0.016 (tumble1) 0.968 (tumble2)) (not (pickloc ?above)))
	)
	(:action stack5
		:parameters (?below ?above)
		:precondition (and (not (stacked)) (not (inserted)) (pickloc ?above) (stackloc ?below) (and (objtype0 ?below) (objtype3 ?above) (relation1 ?below ?above)))
		:effect (and (probabilistic 0.016 (roll1) 0.172 (tumble1) 0.812 (tumble2)) (not (pickloc ?above)))
	)
	(:action stack6
		:parameters (?below ?above)
		:precondition (and (not (stacked)) (not (inserted)) (pickloc ?above) (stackloc ?below) (and (objtype3 ?below) (objtype0 ?above) (relation1 ?below ?above)))
		:effect (and (probabilistic 0.041 (and (stacked) (inserted) (instack ?above) (stackloc ?above) (not (stackloc ?below))) 0.041 (roll1) 0.108 (tumble1) 0.810 (tumble2)) (not (pickloc ?above)))
	)
	(:action stack7
		:parameters (?below ?above)
		:precondition (and (not (stacked)) (not (inserted)) (pickloc ?above) (stackloc ?below) (and (objtype3 ?below) (objtype3 ?above) (relation1 ?below ?above)))
		:effect (and (probabilistic 0.014 (and (inserted) (instack ?above) (stackloc ?above) (not (stackloc ?below))) 0.095 (and (stacked) (inserted) (instack ?above) (stackloc ?above) (not (stackloc ?below))) 0.054 (tumble1) 0.837 (tumble2)) (not (pickloc ?above)))
	)
	(:action stack8
		:parameters (?below ?above)
		:precondition (and (not (stacked)) (not (inserted)) (pickloc ?above) (stackloc ?below) (and (objtype0 ?below) (objtype2 ?above) (relation1 ?below ?above)))
		:effect (and (probabilistic 0.013 (and (inserted) (instack ?above) (stackloc ?above) (not (stackloc ?below))) 0.653 (roll1) 0.227 (tumble1) 0.007 (roll2) 0.100 (tumble2)) (not (pickloc ?above)))
	)
	(:action stack9
		:parameters (?below ?above)
		:precondition (and (not (stacked)) (not (inserted)) (pickloc ?above) (stackloc ?below) (and (objtype0 ?below) (objtype2 ?above) (relation0 ?below ?above)))
		:effect (and (probabilistic 0.040 (and (inserted) (instack ?above) (stackloc ?above) (not (stackloc ?below))) 0.620 (roll1) 0.240 (tumble1) 0.100 (tumble2)) (not (pickloc ?above)))
	)
	(:action stack10
		:parameters (?below ?above)
		:precondition (and (not (stacked)) (not (inserted)) (pickloc ?above) (stackloc ?below) (and (objtype3 ?below) (objtype2 ?above) (relation1 ?below ?above)))
		:effect (and (probabilistic 0.053 (and (inserted) (instack ?above) (stackloc ?above) (not (stackloc ?below))) 0.053 (and (stacked) (inserted) (instack ?above) (stackloc ?above) (not (stackloc ?below))) 0.598 (roll1) 0.089 (tumble1) 0.006 (roll2) 0.201 (tumble2)) (not (pickloc ?above)))
	)
	(:action stack11
		:parameters (?below ?above)
		:precondition (and (not (stacked)) (not (inserted)) (pickloc ?above) (stackloc ?below) (and (objtype3 ?below) (objtype2 ?above) (relation0 ?below ?above)))
		:effect (and (probabilistic 0.452 (roll1) 0.419 (tumble1) 0.129 (tumble2)) (not (pickloc ?above)))
	)
	(:action stack12
		:parameters (?below ?above)
		:precondition (and (not (stacked)) (not (inserted)) (pickloc ?above) (stackloc ?below) (and (objtype0 ?below) (objtype1 ?above) (relation1 ?below ?above)))
		:effect (and (probabilistic 0.750 (roll1) 0.200 (tumble1) 0.050 (roll2)) (not (pickloc ?above)))
	)
	(:action stack13
		:parameters (?below ?above)
		:precondition (and (not (stacked)) (not (inserted)) (pickloc ?above) (stackloc ?below) (and (objtype3 ?below) (objtype1 ?above) (relation1 ?below ?above)))
		:effect (and (probabilistic 0.350 (and (inserted) (instack ?above) (stackloc ?above) (not (stackloc ?below))) 0.550 (roll1) 0.050 (tumble1) 0.050 (tumble2)) (not (pickloc ?above)))
	)
	(:action stack14
		:parameters (?below ?above)
		:precondition (and (not (stacked)) (not (inserted)) (pickloc ?above) (stackloc ?below) (and (objtype3 ?below) (objtype1 ?above) (relation0 ?below ?above)))
		:effect (and (probabilistic 0.038 (and (stacked) (inserted) (instack ?above) (stackloc ?above) (not (stackloc ?below))) 0.950 (roll2) 0.012 (tumble2)) (not (pickloc ?above)))
	)
	(:action stack15
		:parameters (?below ?above)
		:precondition (and (not (stacked)) (not (inserted)) (pickloc ?above) (stackloc ?below) (and (objtype0 ?below) (objtype1 ?above) (relation0 ?below ?above)))
		:effect (and (probabilistic 0.050 (tumble1) 0.950 (roll2)) (not (pickloc ?above)))
	)
	(:action stack16
		:parameters (?below ?above)
		:precondition (and (not (stacked)) (not (inserted)) (pickloc ?above) (stackloc ?below) (and (objtype1 ?below) (objtype0 ?above) (relation1 ?below ?above)))
		:effect (and (probabilistic 0.028 (and (inserted) (instack ?above) (stackloc ?above) (not (stackloc ?below))) 0.972 (and (stacked) (inserted) (instack ?above) (stackloc ?above) (not (stackloc ?below)))) (not (pickloc ?above)))
	)
	(:action stack17
		:parameters (?below ?above)
		:precondition (and (not (stacked)) (not (inserted)) (pickloc ?above) (stackloc ?below) (and (objtype1 ?below) (objtype1 ?above) (relation1 ?below ?above)))
		:effect (and (probabilistic 0.015 (and (inserted) (instack ?above) (stackloc ?above) (not (stackloc ?below))) 0.970 (and (stacked) (inserted) (instack ?above) (stackloc ?above) (not (stackloc ?below))) 0.015 (tumble2)) (not (pickloc ?above)))
	)
	(:action stack18
		:parameters (?below ?above)
		:precondition (and (not (stacked)) (not (inserted)) (pickloc ?above) (stackloc ?below) (and (objtype1 ?below) (objtype2 ?above) (relation1 ?below ?above)))
		:effect (and (probabilistic 0.007 (and (inserted) (instack ?above) (stackloc ?above) (not (stackloc ?below))) 0.960 (and (stacked) (inserted) (instack ?above) (stackloc ?above) (not (stackloc ?below))) 0.033 (tumble2)) (not (pickloc ?above)))
	)
	(:action stack19
		:parameters (?below ?above)
		:precondition (and (not (stacked)) (not (inserted)) (pickloc ?above) (stackloc ?below) (and (objtype1 ?below) (objtype3 ?above) (relation1 ?below ?above)))
		:effect (and (probabilistic 0.059 (and (inserted) (instack ?above) (stackloc ?above) (not (stackloc ?below))) 0.451 (and (stacked) (inserted) (instack ?above) (stackloc ?above) (not (stackloc ?below))) 0.490 (tumble2)) (not (pickloc ?above)))
	)
	(:action stack20
		:parameters (?below ?above)
		:precondition (and (not (stacked)) (not (inserted)) (pickloc ?above) (stackloc ?below) (and (objtype1 ?below) (objtype0 ?above) (relation0 ?below ?above)))
		:effect (and (probabilistic 0.893 (and (inserted) (instack ?above) (stackloc ?above) (not (stackloc ?below))) 0.107 (and (stacked) (inserted) (instack ?above) (stackloc ?above) (not (stackloc ?below)))) (not (pickloc ?above)))
	)
	(:action stack21
		:parameters (?below ?above)
		:precondition (and (not (stacked)) (not (inserted)) (pickloc ?above) (stackloc ?below) (and (objtype1 ?below) (objtype2 ?above) (relation0 ?below ?above)))
		:effect (and (probabilistic 0.813 (and (inserted) (instack ?above) (stackloc ?above) (not (stackloc ?below))) 0.104 (and (stacked) (inserted) (instack ?above) (stackloc ?above) (not (stackloc ?below))) 0.083 (tumble2)) (not (pickloc ?above)))
	)
	(:action stack22
		:parameters (?below ?above)
		:precondition (and (not (stacked)) (not (inserted)) (pickloc ?above) (stackloc ?below) (and (objtype1 ?below) (objtype1 ?above) (relation0 ?below ?above)))
		:effect (and (probabilistic 0.687 (and (inserted) (instack ?above) (stackloc ?above) (not (stackloc ?below))) 0.125 (and (stacked) (inserted) (instack ?above) (stackloc ?above) (not (stackloc ?below))) 0.188 (tumble2)) (not (pickloc ?above)))
	)
	(:action stack23
		:parameters (?below ?above)
		:precondition (and (not (stacked)) (not (inserted)) (pickloc ?above) (stackloc ?below) (and (objtype1 ?below) (objtype3 ?above) (relation0 ?below ?above)))
		:effect (and (probabilistic 0.306 (and (inserted) (instack ?above) (stackloc ?above) (not (stackloc ?below))) 0.041 (and (stacked) (inserted) (instack ?above) (stackloc ?above) (not (stackloc ?below))) 0.020 (tumble1) 0.633 (tumble2)) (not (pickloc ?above)))
	)
	(:action stack24
		:parameters (?below ?above)
		:precondition (and (not (stacked)) (not (inserted)) (pickloc ?above) (stackloc ?below) (and (objtype2 ?below) (objtype1 ?above) (relation1 ?below ?above)))
		:effect (and (probabilistic 0.632 (and (inserted) (instack ?above) (stackloc ?above) (not (stackloc ?below))) 0.368 (and (stacked) (inserted) (instack ?above) (stackloc ?above) (not (stackloc ?below)))) (not (pickloc ?above)))
	)
	(:action stack25
		:parameters (?below ?above)
		:precondition (and (not (stacked)) (not (inserted)) (pickloc ?above) (stackloc ?below) (and (objtype2 ?below) (objtype1 ?above) (relation0 ?below ?above)))
		:effect (and (probabilistic 0.006 (and (inserted) (instack ?above) (stackloc ?above) (not (stackloc ?below))) 0.988 (and (stacked) (inserted) (instack ?above) (stackloc ?above) (not (stackloc ?below))) 0.006 (tumble2)) (not (pickloc ?above)))
	)
	(:action stack26
		:parameters (?below ?above)
		:precondition (and (not (stacked)) (not (inserted)) (pickloc ?above) (stackloc ?below) (and (objtype2 ?below) (objtype2 ?above) (relation1 ?below ?above)))
		:effect (and (probabilistic 0.991 (and (stacked) (inserted) (instack ?above) (stackloc ?above) (not (stackloc ?below))) 0.003 (roll1) 0.006 (tumble2)) (not (pickloc ?above)))
	)
	(:action stack27
		:parameters (?below ?above)
		:precondition (and (not (stacked)) (not (inserted)) (pickloc ?above) (stackloc ?below) (and (objtype2 ?below) (objtype2 ?above) (relation0 ?below ?above)))
		:effect (and (probabilistic 0.022 (and (inserted) (instack ?above) (stackloc ?above) (not (stackloc ?below))) 0.848 (and (stacked) (inserted) (instack ?above) (stackloc ?above) (not (stackloc ?below))) 0.130 (tumble2)) (not (pickloc ?above)))
	)
	(:action stack28
		:parameters (?below ?above)
		:precondition (and (not (stacked)) (not (inserted)) (pickloc ?above) (stackloc ?below) (and (objtype2 ?below) (objtype0 ?above) (relation0 ?below ?above)))
		:effect (and (probabilistic 0.089 (and (inserted) (instack ?above) (stackloc ?above) (not (stackloc ?below))) 0.467 (and (stacked) (inserted) (instack ?above) (stackloc ?above) (not (stackloc ?below))) 0.044 (roll1) 0.400 (tumble2)) (not (pickloc ?above)))
	)
	(:action stack29
		:parameters (?below ?above)
		:precondition (and (not (stacked)) (not (inserted)) (pickloc ?above) (stackloc ?below) (and (objtype2 ?below) (objtype0 ?above) (relation1 ?below ?above)))
		:effect (and (probabilistic 0.787 (and (stacked) (inserted) (instack ?above) (stackloc ?above) (not (stackloc ?below))) 0.058 (roll1) 0.013 (roll2) 0.142 (tumble2)) (not (pickloc ?above)))
	)
	(:action stack30
		:parameters (?below ?above)
		:precondition (and (not (stacked)) (not (inserted)) (pickloc ?above) (stackloc ?below) (and (objtype2 ?below) (objtype3 ?above) (relation0 ?below ?above)))
		:effect (and (probabilistic 0.432 (and (stacked) (inserted) (instack ?above) (stackloc ?above) (not (stackloc ?below))) 0.023 (roll1) 0.023 (tumble1) 0.522 (tumble2)) (not (pickloc ?above)))
	)
	(:action stack31
		:parameters (?below ?above)
		:precondition (and (not (stacked)) (not (inserted)) (pickloc ?above) (stackloc ?below) (and (objtype2 ?below) (objtype3 ?above) (relation1 ?below ?above)))
		:effect (and (probabilistic 0.006 (and (inserted) (instack ?above) (stackloc ?above) (not (stackloc ?below))) 0.192 (and (stacked) (inserted) (instack ?above) (stackloc ?above) (not (stackloc ?below))) 0.006 (roll1) 0.013 (tumble1) 0.783 (tumble2)) (not (pickloc ?above)))
	)
	(:action increase-height1
		:precondition (and (stacked) (H0))
		:effect (and (not (H0)) (H1) (not (stacked)))
	)
	(:action increase-height2
		:precondition (and (stacked) (H1))
		:effect (and (not (H1)) (H2) (not (stacked)))
	)
	(:action increase-height3
		:precondition (and (stacked) (H2))
		:effect (and (not (H2)) (H3) (not (stacked)))
	)
	(:action increase-height4
		:precondition (and (stacked) (H3))
		:effect (and (not (H3)) (H4) (not (stacked)))
	)
	(:action increase-height5
		:precondition (and (stacked) (H4))
		:effect (and (not (H4)) (H5) (not (stacked)))
	)
	(:action increase-height6
		:precondition (and (stacked) (H5))
		:effect (and (not (H5)) (H6) (not (stacked)))
	)
	(:action increase-stack1
		:precondition (and (inserted) (S0))
		:effect (and (not (S0)) (S1) (not (inserted)))
	)
	(:action increase-stack2
		:precondition (and (inserted) (S1))
		:effect (and (not (S1)) (S2) (not (inserted)))
	)
	(:action increase-stack3
		:precondition (and (inserted) (S2))
		:effect (and (not (S2)) (S3) (not (inserted)))
	)
	(:action increase-stack4
		:precondition (and (inserted) (S3))
		:effect (and (not (S3)) (S4) (not (inserted)))
	)
	(:action increase-stack5
		:precondition (and (inserted) (S4))
		:effect (and (not (S4)) (S5) (not (inserted)))
	)
	(:action increase-stack6
		:precondition (and (inserted) (S5))
		:effect (and (not (S5)) (S6) (not (inserted)))
	)
	(:action makebase
		:parameters (?obj)
		:precondition (not (base))
		:effect (and (base) (stacked) (inserted) (not (pickloc ?obj)) (stackloc ?obj))
	)
)
