(define (domain blocks)
    (:requirements :equality :probabilistic-effects :typing)
    (:types controlled_role0 controlled_role1)
    (:predicates
        (z0 ?x)
        (not_z0 ?x)
        (r0 ?x ?y)
        (not_r0 ?x ?y)
        (r1 ?x ?y)
        (not_r1 ?x ?y)
        (r2 ?x ?y)
        (not_r2 ?x ?y)
    )

    (:action o0_0_o1_0_i18_c929
        :parameters (?o0 - controlled_role0 ?o1 - controlled_role1)
        :precondition (and
        (not (= ?o0 ?o1))
        (z0 ?o0)
        (z0 ?o1)
        (not_r0 ?o0 ?o0)
        (not_r0 ?o1 ?o1)
        (r1 ?o0 ?o0)
        (r1 ?o1 ?o1)
        (not_r2 ?o0 ?o0)
        (not_r2 ?o1 ?o1)
    )
        :effect (probabilistic
            0.51099000 (and
                (not_z0 ?o0)
                (not (z0 ?o0))
                (not_r0 ?o0 ?o1)
                (not_r0 ?o1 ?o0)
                (r1 ?o1 ?o0)
                (not_r2 ?o0 ?o1)
                (z0 ?o1)
                (not_r0 ?o0 ?o0)
                (not_r0 ?o1 ?o1)
                (r1 ?o0 ?o0)
                (r1 ?o1 ?o1)
                (not_r2 ?o0 ?o0)
                (not_r2 ?o1 ?o1)
            )
            0.48901000 (and
                (not_z0 ?o0)
                (not (z0 ?o0))
                (not_r0 ?o1 ?o0)
                (not_r0 ?o0 ?o1)
                (r1 ?o1 ?o0)
                (r1 ?o0 ?o1)
                (not_r2 ?o0 ?o1)
                (z0 ?o1)
                (not_r0 ?o0 ?o0)
                (not_r0 ?o1 ?o1)
                (r1 ?o0 ?o0)
                (r1 ?o1 ?o1)
                (not_r2 ?o0 ?o0)
                (not_r2 ?o1 ?o1)
            )
        )
    )
)
