(define (domain stack)
	(:requirements :typing :negative-preconditions :probabilistic-effects :conditional-effects :disjunctive-preconditions)
	(:predicates
		(inserted) 
		(m1) 
		(m2) 
		(m3) 
		(stacked) 
		(m4) (base) 
		(pickloc ?x)
		(instack ?x)
		(stackloc ?x)
		(relation0 ?x ?y)
		(relation1 ?x ?y)
		(objtype0 ?x)
		(objtype1 ?x)
		(objtype2 ?x)
		(objtype3 ?x)
		(H0)
		(H1)
		(H2)
		(H3)
		(H4)
		(H5)
		(H6)
		(S0)
		(S1)
		(S2)
		(S3)
		(S4)
		(S5)
		(S6)
	)
	(:action stack0
		:parameters (?below ?above)
		:precondition (and (not (stacked)) (not (inserted)) (pickloc ?above) (stackloc ?below) (objtype0 ?below) (objtype0 ?above) (relation0 ?below ?above))
		:effect (and (probabilistic
				 0.013 (and (inserted) (instack ?above) (stackloc ?above) (not (stackloc ?below)))
				 0.803 (m1)
				 0.053 (m2)
				 0.026 (m3)
				 0.105 (and (stacked) (inserted) (instack ?above) (stackloc ?above) (not (stackloc ?below)))
				 0.000 (m4))
				(not (pickloc ?above)))
	)
	(:action stack1
		:parameters (?below ?above)
		:precondition (and (not (stacked)) (not (inserted)) (pickloc ?above) (stackloc ?below) (objtype1 ?below) (objtype0 ?above) (relation0 ?below ?above))
		:effect (and (probabilistic
				 0.006 (and (inserted) (instack ?above) (stackloc ?above) (not (stackloc ?below)))
				 0.761 (m1)
				 0.012 (m2)
				 0.006 (m3)
				 0.209 (and (stacked) (inserted) (instack ?above) (stackloc ?above) (not (stackloc ?below)))
				 0.006 (m4))
				(not (pickloc ?above)))
	)
	(:action stack2
		:parameters (?below ?above)
		:precondition (and (not (stacked)) (not (inserted)) (pickloc ?above) (stackloc ?below) (objtype2 ?below) (objtype0 ?above) (relation0 ?below ?above))
		:effect (and (probabilistic
				 0.013 (and (inserted) (instack ?above) (stackloc ?above) (not (stackloc ?below)))
				 0.724 (m1)
				 0.013 (m2)
				 0.000 (m3)
				 0.250 (and (stacked) (inserted) (instack ?above) (stackloc ?above) (not (stackloc ?below)))
				 0.000 (m4))
				(not (pickloc ?above)))
	)
	(:action stack3
		:parameters (?below ?above)
		:precondition (and (not (stacked)) (not (inserted)) (pickloc ?above) (stackloc ?below) (objtype3 ?below) (objtype0 ?above) (relation0 ?below ?above))
		:effect (and (probabilistic
				 0.000 (and (inserted) (instack ?above) (stackloc ?above) (not (stackloc ?below)))
				 0.667 (m1)
				 0.232 (m2)
				 0.087 (m3)
				 0.000 (and (stacked) (inserted) (instack ?above) (stackloc ?above) (not (stackloc ?below)))
				 0.014 (m4))
				(not (pickloc ?above)))
	)
	(:action stack4
		:parameters (?below ?above)
		:precondition (and (not (stacked)) (not (inserted)) (pickloc ?above) (stackloc ?below) (objtype0 ?below) (objtype2 ?above) (relation0 ?below ?above))
		:effect (and (probabilistic
				 0.000 (and (inserted) (instack ?above) (stackloc ?above) (not (stackloc ?below)))
				 0.012 (m1)
				 0.000 (m2)
				 0.938 (m3)
				 0.050 (and (stacked) (inserted) (instack ?above) (stackloc ?above) (not (stackloc ?below)))
				 0.000 (m4))
				(not (pickloc ?above)))
	)
	(:action stack5
		:parameters (?below ?above)
		:precondition (and (not (stacked)) (not (inserted)) (pickloc ?above) (stackloc ?below) (objtype1 ?below) (objtype2 ?above) (relation0 ?below ?above))
		:effect (and (probabilistic
				 0.000 (and (inserted) (instack ?above) (stackloc ?above) (not (stackloc ?below)))
				 0.006 (m1)
				 0.000 (m2)
				 0.000 (m3)
				 0.994 (and (stacked) (inserted) (instack ?above) (stackloc ?above) (not (stackloc ?below)))
				 0.000 (m4))
				(not (pickloc ?above)))
	)
	(:action stack6
		:parameters (?below ?above)
		:precondition (and (not (stacked)) (not (inserted)) (pickloc ?above) (stackloc ?below) (objtype2 ?below) (objtype2 ?above) (relation0 ?below ?above))
		:effect (and (probabilistic
				 0.000 (and (inserted) (instack ?above) (stackloc ?above) (not (stackloc ?below)))
				 0.015 (m1)
				 0.000 (m2)
				 0.000 (m3)
				 0.985 (and (stacked) (inserted) (instack ?above) (stackloc ?above) (not (stackloc ?below)))
				 0.000 (m4))
				(not (pickloc ?above)))
	)
	(:action stack7
		:parameters (?below ?above)
		:precondition (and (not (stacked)) (not (inserted)) (pickloc ?above) (stackloc ?below) (objtype3 ?below) (objtype2 ?above) (relation0 ?below ?above))
		:effect (and (probabilistic
				 0.000 (and (inserted) (instack ?above) (stackloc ?above) (not (stackloc ?below)))
				 0.000 (m1)
				 0.038 (m2)
				 0.962 (m3)
				 0.000 (and (stacked) (inserted) (instack ?above) (stackloc ?above) (not (stackloc ?below)))
				 0.000 (m4))
				(not (pickloc ?above)))
	)
	(:action stack8
		:parameters (?below ?above)
		:precondition (and (not (stacked)) (not (inserted)) (pickloc ?above) (stackloc ?below) (objtype0 ?below) (objtype1 ?above) (relation0 ?below ?above))
		:effect (and (probabilistic
				 0.021 (and (inserted) (instack ?above) (stackloc ?above) (not (stackloc ?below)))
				 0.160 (m1)
				 0.062 (m2)
				 0.097 (m3)
				 0.056 (and (stacked) (inserted) (instack ?above) (stackloc ?above) (not (stackloc ?below)))
				 0.604 (m4))
				(not (pickloc ?above)))
	)
	(:action stack9
		:parameters (?below ?above)
		:precondition (and (not (stacked)) (not (inserted)) (pickloc ?above) (stackloc ?below) (objtype2 ?below) (objtype1 ?above) (relation0 ?below ?above))
		:effect (and (probabilistic
				 0.019 (and (inserted) (instack ?above) (stackloc ?above) (not (stackloc ?below)))
				 0.026 (m1)
				 0.000 (m2)
				 0.000 (m3)
				 0.955 (and (stacked) (inserted) (instack ?above) (stackloc ?above) (not (stackloc ?below)))
				 0.000 (m4))
				(not (pickloc ?above)))
	)
	(:action stack10
		:parameters (?below ?above)
		:precondition (and (not (stacked)) (not (inserted)) (pickloc ?above) (stackloc ?below) (objtype1 ?below) (objtype1 ?above) (relation0 ?below ?above))
		:effect (and (probabilistic
				 0.000 (and (inserted) (instack ?above) (stackloc ?above) (not (stackloc ?below)))
				 0.003 (m1)
				 0.000 (m2)
				 0.000 (m3)
				 0.994 (and (stacked) (inserted) (instack ?above) (stackloc ?above) (not (stackloc ?below)))
				 0.003 (m4))
				(not (pickloc ?above)))
	)
	(:action stack11
		:parameters (?below ?above)
		:precondition (and (not (stacked)) (not (inserted)) (pickloc ?above) (stackloc ?below) (objtype3 ?below) (objtype1 ?above) (relation0 ?below ?above))
		:effect (and (probabilistic
				 0.008 (and (inserted) (instack ?above) (stackloc ?above) (not (stackloc ?below)))
				 0.091 (m1)
				 0.250 (m2)
				 0.068 (m3)
				 0.000 (and (stacked) (inserted) (instack ?above) (stackloc ?above) (not (stackloc ?below)))
				 0.583 (m4))
				(not (pickloc ?above)))
	)
	(:action stack12
		:parameters (?below ?above)
		:precondition (and (not (stacked)) (not (inserted)) (pickloc ?above) (stackloc ?below) (objtype0 ?below) (objtype3 ?above) (relation0 ?below ?above))
		:effect (and (probabilistic
				 0.000 (and (inserted) (instack ?above) (stackloc ?above) (not (stackloc ?below)))
				 0.671 (m1)
				 0.082 (m2)
				 0.178 (m3)
				 0.041 (and (stacked) (inserted) (instack ?above) (stackloc ?above) (not (stackloc ?below)))
				 0.027 (m4))
				(not (pickloc ?above)))
	)
	(:action stack13
		:parameters (?below ?above)
		:precondition (and (not (stacked)) (not (inserted)) (pickloc ?above) (stackloc ?below) (objtype1 ?below) (objtype3 ?above) (relation0 ?below ?above))
		:effect (and (probabilistic
				 0.019 (and (inserted) (instack ?above) (stackloc ?above) (not (stackloc ?below)))
				 0.162 (m1)
				 0.000 (m2)
				 0.012 (m3)
				 0.750 (and (stacked) (inserted) (instack ?above) (stackloc ?above) (not (stackloc ?below)))
				 0.056 (m4))
				(not (pickloc ?above)))
	)
	(:action stack14
		:parameters (?below ?above)
		:precondition (and (not (stacked)) (not (inserted)) (pickloc ?above) (stackloc ?below) (objtype2 ?below) (objtype3 ?above) (relation0 ?below ?above))
		:effect (and (probabilistic
				 0.030 (and (inserted) (instack ?above) (stackloc ?above) (not (stackloc ?below)))
				 0.000 (m1)
				 0.000 (m2)
				 0.000 (m3)
				 0.970 (and (stacked) (inserted) (instack ?above) (stackloc ?above) (not (stackloc ?below)))
				 0.000 (m4))
				(not (pickloc ?above)))
	)
	(:action stack15
		:parameters (?below ?above)
		:precondition (and (not (stacked)) (not (inserted)) (pickloc ?above) (stackloc ?below) (objtype3 ?below) (objtype3 ?above) (relation0 ?below ?above))
		:effect (and (probabilistic
				 0.000 (and (inserted) (instack ?above) (stackloc ?above) (not (stackloc ?below)))
				 0.940 (m1)
				 0.030 (m2)
				 0.030 (m3)
				 0.000 (and (stacked) (inserted) (instack ?above) (stackloc ?above) (not (stackloc ?below)))
				 0.000 (m4))
				(not (pickloc ?above)))
	)
	(:action stack16
		:parameters (?below ?above)
		:precondition (and (not (stacked)) (not (inserted)) (pickloc ?above) (stackloc ?below) (objtype0 ?below) (objtype0 ?above) (relation1 ?below ?above))
		:effect (and (probabilistic
				 0.000 (and (inserted) (instack ?above) (stackloc ?above) (not (stackloc ?below)))
				 0.417 (m1)
				 0.583 (m2)
				 0.000 (m3)
				 0.000 (and (stacked) (inserted) (instack ?above) (stackloc ?above) (not (stackloc ?below)))
				 0.000 (m4))
				(not (pickloc ?above)))
	)
	(:action stack17
		:parameters (?below ?above)
		:precondition (and (not (stacked)) (not (inserted)) (pickloc ?above) (stackloc ?below) (objtype0 ?below) (objtype1 ?above) (relation1 ?below ?above))
		:effect (and (probabilistic
				 0.036 (and (inserted) (instack ?above) (stackloc ?above) (not (stackloc ?below)))
				 0.161 (m1)
				 0.339 (m2)
				 0.018 (m3)
				 0.018 (and (stacked) (inserted) (instack ?above) (stackloc ?above) (not (stackloc ?below)))
				 0.428 (m4))
				(not (pickloc ?above)))
	)
	(:action stack18
		:parameters (?below ?above)
		:precondition (and (not (stacked)) (not (inserted)) (pickloc ?above) (stackloc ?below) (objtype0 ?below) (objtype2 ?above) (relation1 ?below ?above))
		:effect (and (probabilistic
				 0.150 (and (inserted) (instack ?above) (stackloc ?above) (not (stackloc ?below)))
				 0.000 (m1)
				 0.050 (m2)
				 0.050 (m3)
				 0.000 (and (stacked) (inserted) (instack ?above) (stackloc ?above) (not (stackloc ?below)))
				 0.750 (m4))
				(not (pickloc ?above)))
	)
	(:action stack19
		:parameters (?below ?above)
		:precondition (and (not (stacked)) (not (inserted)) (pickloc ?above) (stackloc ?below) (objtype0 ?below) (objtype3 ?above) (relation1 ?below ?above))
		:effect (and (probabilistic
				 0.000 (and (inserted) (instack ?above) (stackloc ?above) (not (stackloc ?below)))
				 0.222 (m1)
				 0.444 (m2)
				 0.333 (m3)
				 0.000 (and (stacked) (inserted) (instack ?above) (stackloc ?above) (not (stackloc ?below)))
				 0.000 (m4))
				(not (pickloc ?above)))
	)
	(:action stack20
		:parameters (?below ?above)
		:precondition (and (not (stacked)) (not (inserted)) (pickloc ?above) (stackloc ?below) (objtype2 ?below) (objtype0 ?above) (relation1 ?below ?above))
		:effect (and (probabilistic
				 0.708 (and (inserted) (instack ?above) (stackloc ?above) (not (stackloc ?below)))
				 0.042 (m1)
				 0.000 (m2)
				 0.000 (m3)
				 0.250 (and (stacked) (inserted) (instack ?above) (stackloc ?above) (not (stackloc ?below)))
				 0.000 (m4))
				(not (pickloc ?above)))
	)
	(:action stack21
		:parameters (?below ?above)
		:precondition (and (not (stacked)) (not (inserted)) (pickloc ?above) (stackloc ?below) (objtype2 ?below) (objtype2 ?above) (relation1 ?below ?above))
		:effect (and (probabilistic
				 0.750 (and (inserted) (instack ?above) (stackloc ?above) (not (stackloc ?below)))
				 0.188 (m1)
				 0.000 (m2)
				 0.000 (m3)
				 0.062 (and (stacked) (inserted) (instack ?above) (stackloc ?above) (not (stackloc ?below)))
				 0.000 (m4))
				(not (pickloc ?above)))
	)
	(:action stack22
		:parameters (?below ?above)
		:precondition (and (not (stacked)) (not (inserted)) (pickloc ?above) (stackloc ?below) (objtype2 ?below) (objtype1 ?above) (relation1 ?below ?above))
		:effect (and (probabilistic
				 0.841 (and (inserted) (instack ?above) (stackloc ?above) (not (stackloc ?below)))
				 0.114 (m1)
				 0.000 (m2)
				 0.000 (m3)
				 0.045 (and (stacked) (inserted) (instack ?above) (stackloc ?above) (not (stackloc ?below)))
				 0.000 (m4))
				(not (pickloc ?above)))
	)
	(:action stack23
		:parameters (?below ?above)
		:precondition (and (not (stacked)) (not (inserted)) (pickloc ?above) (stackloc ?below) (objtype2 ?below) (objtype3 ?above) (relation1 ?below ?above))
		:effect (and (probabilistic
				 0.765 (and (inserted) (instack ?above) (stackloc ?above) (not (stackloc ?below)))
				 0.000 (m1)
				 0.000 (m2)
				 0.000 (m3)
				 0.235 (and (stacked) (inserted) (instack ?above) (stackloc ?above) (not (stackloc ?below)))
				 0.000 (m4))
				(not (pickloc ?above)))
	)
	(:action stack24
		:parameters (?below ?above)
		:precondition (and (not (stacked)) (not (inserted)) (pickloc ?above) (stackloc ?below) (objtype1 ?below) (objtype0 ?above) (relation1 ?below ?above))
		:effect (and (probabilistic
				 0.000 (and (inserted) (instack ?above) (stackloc ?above) (not (stackloc ?below)))
				 0.500 (m1)
				 0.000 (m2)
				 0.000 (m3)
				 0.464 (and (stacked) (inserted) (instack ?above) (stackloc ?above) (not (stackloc ?below)))
				 0.036 (m4))
				(not (pickloc ?above)))
	)
	(:action stack25
		:parameters (?below ?above)
		:precondition (and (not (stacked)) (not (inserted)) (pickloc ?above) (stackloc ?below) (objtype1 ?below) (objtype2 ?above) (relation1 ?below ?above))
		:effect (and (probabilistic
				 0.781 (and (inserted) (instack ?above) (stackloc ?above) (not (stackloc ?below)))
				 0.000 (m1)
				 0.000 (m2)
				 0.000 (m3)
				 0.219 (and (stacked) (inserted) (instack ?above) (stackloc ?above) (not (stackloc ?below)))
				 0.000 (m4))
				(not (pickloc ?above)))
	)
	(:action stack26
		:parameters (?below ?above)
		:precondition (and (not (stacked)) (not (inserted)) (pickloc ?above) (stackloc ?below) (objtype1 ?below) (objtype1 ?above) (relation1 ?below ?above))
		:effect (and (probabilistic
				 0.000 (and (inserted) (instack ?above) (stackloc ?above) (not (stackloc ?below)))
				 0.100 (m1)
				 0.000 (m2)
				 0.000 (m3)
				 0.886 (and (stacked) (inserted) (instack ?above) (stackloc ?above) (not (stackloc ?below)))
				 0.014 (m4))
				(not (pickloc ?above)))
	)
	(:action stack27
		:parameters (?below ?above)
		:precondition (and (not (stacked)) (not (inserted)) (pickloc ?above) (stackloc ?below) (objtype1 ?below) (objtype3 ?above) (relation1 ?below ?above))
		:effect (and (probabilistic
				 0.000 (and (inserted) (instack ?above) (stackloc ?above) (not (stackloc ?below)))
				 0.350 (m1)
				 0.000 (m2)
				 0.000 (m3)
				 0.575 (and (stacked) (inserted) (instack ?above) (stackloc ?above) (not (stackloc ?below)))
				 0.075 (m4))
				(not (pickloc ?above)))
	)
	(:action stack28
		:parameters (?below ?above)
		:precondition (and (not (stacked)) (not (inserted)) (pickloc ?above) (stackloc ?below) (objtype3 ?below) (objtype0 ?above) (relation1 ?below ?above))
		:effect (and (probabilistic
				 0.000 (and (inserted) (instack ?above) (stackloc ?above) (not (stackloc ?below)))
				 0.194 (m1)
				 0.709 (m2)
				 0.097 (m3)
				 0.000 (and (stacked) (inserted) (instack ?above) (stackloc ?above) (not (stackloc ?below)))
				 0.000 (m4))
				(not (pickloc ?above)))
	)
	(:action stack29
		:parameters (?below ?above)
		:precondition (and (not (stacked)) (not (inserted)) (pickloc ?above) (stackloc ?below) (objtype3 ?below) (objtype1 ?above) (relation1 ?below ?above))
		:effect (and (probabilistic
				 0.029 (and (inserted) (instack ?above) (stackloc ?above) (not (stackloc ?below)))
				 0.074 (m1)
				 0.206 (m2)
				 0.044 (m3)
				 0.000 (and (stacked) (inserted) (instack ?above) (stackloc ?above) (not (stackloc ?below)))
				 0.647 (m4))
				(not (pickloc ?above)))
	)
	(:action stack30
		:parameters (?below ?above)
		:precondition (and (not (stacked)) (not (inserted)) (pickloc ?above) (stackloc ?below) (objtype3 ?below) (objtype2 ?above) (relation1 ?below ?above))
		:effect (and (probabilistic
				 0.000 (and (inserted) (instack ?above) (stackloc ?above) (not (stackloc ?below)))
				 0.000 (m1)
				 0.200 (m2)
				 0.100 (m3)
				 0.000 (and (stacked) (inserted) (instack ?above) (stackloc ?above) (not (stackloc ?below)))
				 0.700 (m4))
				(not (pickloc ?above)))
	)
	(:action stack31
		:parameters (?below ?above)
		:precondition (and (not (stacked)) (not (inserted)) (pickloc ?above) (stackloc ?below) (objtype3 ?below) (objtype3 ?above) (relation1 ?below ?above))
		:effect (and (probabilistic
				 0.000 (and (inserted) (instack ?above) (stackloc ?above) (not (stackloc ?below)))
				 0.636 (m1)
				 0.182 (m2)
				 0.182 (m3)
				 0.000 (and (stacked) (inserted) (instack ?above) (stackloc ?above) (not (stackloc ?below)))
				 0.000 (m4))
				(not (pickloc ?above)))
	)
	(:action increase-height1
		:precondition (and (stacked) (H0))
		:effect (and (not (H0)) (H1) (not (stacked)))
	)
	(:action increase-height2
		:precondition (and (stacked) (H1))
		:effect (and (not (H1)) (H2) (not (stacked)))
	)
	(:action increase-height3
		:precondition (and (stacked) (H2))
		:effect (and (not (H2)) (H3) (not (stacked)))
	)
	(:action increase-height4
		:precondition (and (stacked) (H3))
		:effect (and (not (H3)) (H4) (not (stacked)))
	)
	(:action increase-height5
		:precondition (and (stacked) (H4))
		:effect (and (not (H4)) (H5) (not (stacked)))
	)
	(:action increase-height6
		:precondition (and (stacked) (H5))
		:effect (and (not (H5)) (H6) (not (stacked)))
	)
	(:action increase-stack1
		:precondition (and (inserted) (S0))
		:effect (and (not (S0)) (S1) (not (inserted)))
	)
	(:action increase-stack2
		:precondition (and (inserted) (S1))
		:effect (and (not (S1)) (S2) (not (inserted)))
	)
	(:action increase-stack3
		:precondition (and (inserted) (S2))
		:effect (and (not (S2)) (S3) (not (inserted)))
	)
	(:action increase-stack4
		:precondition (and (inserted) (S3))
		:effect (and (not (S3)) (S4) (not (inserted)))
	)
	(:action increase-stack5
		:precondition (and (inserted) (S4))
		:effect (and (not (S4)) (S5) (not (inserted)))
	)
	(:action increase-stack6
		:precondition (and (inserted) (S5))
		:effect (and (not (S5)) (S6) (not (inserted)))
	)
	(:action makebase
		:parameters (?obj)
		:precondition (not (base))
		:effect (and (base) (stacked) (inserted) (not (pickloc ?obj)) (stackloc ?obj))
	)
)
