(define (domain stack)
	(:requirements :typing :negative-preconditions :probabilistic-effects :conditional-effects :disjunctive-preconditions)
	(:predicates
		(m1) 
		(inserted) 
		(m2) 
		(m3) 
		(m4) 
		(stacked) (base) 
		(pickloc ?x)
		(instack ?x)
		(stackloc ?x)
		(relation0 ?x ?y)
		(relation1 ?x ?y)
		(objtype0 ?x)
		(objtype1 ?x)
		(objtype2 ?x)
		(objtype3 ?x)
		(H0)
		(H1)
		(H2)
		(H3)
		(H4)
		(H5)
		(H6)
		(S0)
		(S1)
		(S2)
		(S3)
		(S4)
		(S5)
		(S6)
	)
	(:action stack0
		:parameters (?below ?above)
		:precondition (and (not (stacked)) (not (inserted)) (pickloc ?above) (stackloc ?below) (objtype0 ?below) (objtype0 ?above) (relation0 ?below ?above))
		:effect (and (probabilistic
				 0.053 (m1)
				 0.000 (and (inserted) (instack ?above) (stackloc ?above) (not (stackloc ?below)))
				 0.829 (m2)
				 0.013 (m3)
				 0.000 (m4)
				 0.105 (and (stacked) (inserted) (instack ?above) (stackloc ?above) (not (stackloc ?below))))
				(not (pickloc ?above)))
	)
	(:action stack1
		:parameters (?below ?above)
		:precondition (and (not (stacked)) (not (inserted)) (pickloc ?above) (stackloc ?below) (objtype1 ?below) (objtype0 ?above) (relation0 ?below ?above))
		:effect (and (probabilistic
				 0.017 (m1)
				 0.000 (and (inserted) (instack ?above) (stackloc ?above) (not (stackloc ?below)))
				 0.762 (m2)
				 0.017 (m3)
				 0.006 (m4)
				 0.198 (and (stacked) (inserted) (instack ?above) (stackloc ?above) (not (stackloc ?below))))
				(not (pickloc ?above)))
	)
	(:action stack2
		:parameters (?below ?above)
		:precondition (and (not (stacked)) (not (inserted)) (pickloc ?above) (stackloc ?below) (objtype2 ?below) (objtype0 ?above) (relation0 ?below ?above))
		:effect (and (probabilistic
				 0.013 (m1)
				 0.000 (and (inserted) (instack ?above) (stackloc ?above) (not (stackloc ?below)))
				 0.724 (m2)
				 0.013 (m3)
				 0.000 (m4)
				 0.250 (and (stacked) (inserted) (instack ?above) (stackloc ?above) (not (stackloc ?below))))
				(not (pickloc ?above)))
	)
	(:action stack3
		:parameters (?below ?above)
		:precondition (and (not (stacked)) (not (inserted)) (pickloc ?above) (stackloc ?below) (objtype3 ?below) (objtype0 ?above) (relation0 ?below ?above))
		:effect (and (probabilistic
				 0.246 (m1)
				 0.000 (and (inserted) (instack ?above) (stackloc ?above) (not (stackloc ?below)))
				 0.710 (m2)
				 0.000 (m3)
				 0.043 (m4)
				 0.000 (and (stacked) (inserted) (instack ?above) (stackloc ?above) (not (stackloc ?below))))
				(not (pickloc ?above)))
	)
	(:action stack4
		:parameters (?below ?above)
		:precondition (and (not (stacked)) (not (inserted)) (pickloc ?above) (stackloc ?below) (objtype0 ?below) (objtype2 ?above) (relation0 ?below ?above))
		:effect (and (probabilistic
				 0.000 (m1)
				 0.949 (and (inserted) (instack ?above) (stackloc ?above) (not (stackloc ?below)))
				 0.013 (m2)
				 0.000 (m3)
				 0.000 (m4)
				 0.038 (and (stacked) (inserted) (instack ?above) (stackloc ?above) (not (stackloc ?below))))
				(not (pickloc ?above)))
	)
	(:action stack5
		:parameters (?below ?above)
		:precondition (and (not (stacked)) (not (inserted)) (pickloc ?above) (stackloc ?below) (objtype1 ?below) (objtype2 ?above) (relation0 ?below ?above))
		:effect (and (probabilistic
				 0.000 (m1)
				 0.000 (and (inserted) (instack ?above) (stackloc ?above) (not (stackloc ?below)))
				 0.006 (m2)
				 0.119 (m3)
				 0.000 (m4)
				 0.875 (and (stacked) (inserted) (instack ?above) (stackloc ?above) (not (stackloc ?below))))
				(not (pickloc ?above)))
	)
	(:action stack6
		:parameters (?below ?above)
		:precondition (and (not (stacked)) (not (inserted)) (pickloc ?above) (stackloc ?below) (objtype2 ?below) (objtype2 ?above) (relation0 ?below ?above))
		:effect (and (probabilistic
				 0.000 (m1)
				 0.000 (and (inserted) (instack ?above) (stackloc ?above) (not (stackloc ?below)))
				 0.015 (m2)
				 0.103 (m3)
				 0.000 (m4)
				 0.882 (and (stacked) (inserted) (instack ?above) (stackloc ?above) (not (stackloc ?below))))
				(not (pickloc ?above)))
	)
	(:action stack7
		:parameters (?below ?above)
		:precondition (and (not (stacked)) (not (inserted)) (pickloc ?above) (stackloc ?below) (objtype3 ?below) (objtype2 ?above) (relation0 ?below ?above))
		:effect (and (probabilistic
				 0.050 (m1)
				 0.950 (and (inserted) (instack ?above) (stackloc ?above) (not (stackloc ?below)))
				 0.000 (m2)
				 0.000 (m3)
				 0.000 (m4)
				 0.000 (and (stacked) (inserted) (instack ?above) (stackloc ?above) (not (stackloc ?below))))
				(not (pickloc ?above)))
	)
	(:action stack8
		:parameters (?below ?above)
		:precondition (and (not (stacked)) (not (inserted)) (pickloc ?above) (stackloc ?below) (objtype0 ?below) (objtype1 ?above) (relation0 ?below ?above))
		:effect (and (probabilistic
				 0.062 (m1)
				 0.007 (and (inserted) (instack ?above) (stackloc ?above) (not (stackloc ?below)))
				 0.181 (m2)
				 0.014 (m3)
				 0.680 (m4)
				 0.056 (and (stacked) (inserted) (instack ?above) (stackloc ?above) (not (stackloc ?below))))
				(not (pickloc ?above)))
	)
	(:action stack9
		:parameters (?below ?above)
		:precondition (and (not (stacked)) (not (inserted)) (pickloc ?above) (stackloc ?below) (objtype2 ?below) (objtype1 ?above) (relation0 ?below ?above))
		:effect (and (probabilistic
				 0.000 (m1)
				 0.000 (and (inserted) (instack ?above) (stackloc ?above) (not (stackloc ?below)))
				 0.026 (m2)
				 0.090 (m3)
				 0.000 (m4)
				 0.884 (and (stacked) (inserted) (instack ?above) (stackloc ?above) (not (stackloc ?below))))
				(not (pickloc ?above)))
	)
	(:action stack10
		:parameters (?below ?above)
		:precondition (and (not (stacked)) (not (inserted)) (pickloc ?above) (stackloc ?below) (objtype1 ?below) (objtype1 ?above) (relation0 ?below ?above))
		:effect (and (probabilistic
				 0.000 (m1)
				 0.000 (and (inserted) (instack ?above) (stackloc ?above) (not (stackloc ?below)))
				 0.003 (m2)
				 0.015 (m3)
				 0.003 (m4)
				 0.979 (and (stacked) (inserted) (instack ?above) (stackloc ?above) (not (stackloc ?below))))
				(not (pickloc ?above)))
	)
	(:action stack11
		:parameters (?below ?above)
		:precondition (and (not (stacked)) (not (inserted)) (pickloc ?above) (stackloc ?below) (objtype3 ?below) (objtype1 ?above) (relation0 ?below ?above))
		:effect (and (probabilistic
				 0.258 (m1)
				 0.008 (and (inserted) (instack ?above) (stackloc ?above) (not (stackloc ?below)))
				 0.091 (m2)
				 0.008 (m3)
				 0.635 (m4)
				 0.000 (and (stacked) (inserted) (instack ?above) (stackloc ?above) (not (stackloc ?below))))
				(not (pickloc ?above)))
	)
	(:action stack12
		:parameters (?below ?above)
		:precondition (and (not (stacked)) (not (inserted)) (pickloc ?above) (stackloc ?below) (objtype0 ?below) (objtype3 ?above) (relation0 ?below ?above))
		:effect (and (probabilistic
				 0.082 (m1)
				 0.000 (and (inserted) (instack ?above) (stackloc ?above) (not (stackloc ?below)))
				 0.795 (m2)
				 0.000 (m3)
				 0.082 (m4)
				 0.041 (and (stacked) (inserted) (instack ?above) (stackloc ?above) (not (stackloc ?below))))
				(not (pickloc ?above)))
	)
	(:action stack13
		:parameters (?below ?above)
		:precondition (and (not (stacked)) (not (inserted)) (pickloc ?above) (stackloc ?below) (objtype1 ?below) (objtype3 ?above) (relation0 ?below ?above))
		:effect (and (probabilistic
				 0.000 (m1)
				 0.012 (and (inserted) (instack ?above) (stackloc ?above) (not (stackloc ?below)))
				 0.162 (m2)
				 0.038 (m3)
				 0.062 (m4)
				 0.725 (and (stacked) (inserted) (instack ?above) (stackloc ?above) (not (stackloc ?below))))
				(not (pickloc ?above)))
	)
	(:action stack14
		:parameters (?below ?above)
		:precondition (and (not (stacked)) (not (inserted)) (pickloc ?above) (stackloc ?below) (objtype2 ?below) (objtype3 ?above) (relation0 ?below ?above))
		:effect (and (probabilistic
				 0.000 (m1)
				 0.000 (and (inserted) (instack ?above) (stackloc ?above) (not (stackloc ?below)))
				 0.000 (m2)
				 0.288 (m3)
				 0.000 (m4)
				 0.712 (and (stacked) (inserted) (instack ?above) (stackloc ?above) (not (stackloc ?below))))
				(not (pickloc ?above)))
	)
	(:action stack15
		:parameters (?below ?above)
		:precondition (and (not (stacked)) (not (inserted)) (pickloc ?above) (stackloc ?below) (objtype3 ?below) (objtype3 ?above) (relation0 ?below ?above))
		:effect (and (probabilistic
				 0.045 (m1)
				 0.000 (and (inserted) (instack ?above) (stackloc ?above) (not (stackloc ?below)))
				 0.940 (m2)
				 0.000 (m3)
				 0.015 (m4)
				 0.000 (and (stacked) (inserted) (instack ?above) (stackloc ?above) (not (stackloc ?below))))
				(not (pickloc ?above)))
	)
	(:action stack16
		:parameters (?below ?above)
		:precondition (and (not (stacked)) (not (inserted)) (pickloc ?above) (stackloc ?below) (objtype0 ?below) (objtype0 ?above) (relation1 ?below ?above))
		:effect (and (probabilistic
				 0.583 (m1)
				 0.000 (and (inserted) (instack ?above) (stackloc ?above) (not (stackloc ?below)))
				 0.417 (m2)
				 0.000 (m3)
				 0.000 (m4)
				 0.000 (and (stacked) (inserted) (instack ?above) (stackloc ?above) (not (stackloc ?below))))
				(not (pickloc ?above)))
	)
	(:action stack17
		:parameters (?below ?above)
		:precondition (and (not (stacked)) (not (inserted)) (pickloc ?above) (stackloc ?below) (objtype0 ?below) (objtype1 ?above) (relation1 ?below ?above))
		:effect (and (probabilistic
				 0.339 (m1)
				 0.000 (and (inserted) (instack ?above) (stackloc ?above) (not (stackloc ?below)))
				 0.161 (m2)
				 0.018 (m3)
				 0.464 (m4)
				 0.018 (and (stacked) (inserted) (instack ?above) (stackloc ?above) (not (stackloc ?below))))
				(not (pickloc ?above)))
	)
	(:action stack18
		:parameters (?below ?above)
		:precondition (and (not (stacked)) (not (inserted)) (pickloc ?above) (stackloc ?below) (objtype0 ?below) (objtype2 ?above) (relation1 ?below ?above))
		:effect (and (probabilistic
				 0.050 (m1)
				 0.000 (and (inserted) (instack ?above) (stackloc ?above) (not (stackloc ?below)))
				 0.050 (m2)
				 0.050 (m3)
				 0.850 (m4)
				 0.000 (and (stacked) (inserted) (instack ?above) (stackloc ?above) (not (stackloc ?below))))
				(not (pickloc ?above)))
	)
	(:action stack19
		:parameters (?below ?above)
		:precondition (and (not (stacked)) (not (inserted)) (pickloc ?above) (stackloc ?below) (objtype0 ?below) (objtype3 ?above) (relation1 ?below ?above))
		:effect (and (probabilistic
				 0.444 (m1)
				 0.000 (and (inserted) (instack ?above) (stackloc ?above) (not (stackloc ?below)))
				 0.481 (m2)
				 0.000 (m3)
				 0.074 (m4)
				 0.000 (and (stacked) (inserted) (instack ?above) (stackloc ?above) (not (stackloc ?below))))
				(not (pickloc ?above)))
	)
	(:action stack20
		:parameters (?below ?above)
		:precondition (and (not (stacked)) (not (inserted)) (pickloc ?above) (stackloc ?below) (objtype2 ?below) (objtype0 ?above) (relation1 ?below ?above))
		:effect (and (probabilistic
				 0.000 (m1)
				 0.000 (and (inserted) (instack ?above) (stackloc ?above) (not (stackloc ?below)))
				 0.042 (m2)
				 0.708 (m3)
				 0.000 (m4)
				 0.250 (and (stacked) (inserted) (instack ?above) (stackloc ?above) (not (stackloc ?below))))
				(not (pickloc ?above)))
	)
	(:action stack21
		:parameters (?below ?above)
		:precondition (and (not (stacked)) (not (inserted)) (pickloc ?above) (stackloc ?below) (objtype2 ?below) (objtype2 ?above) (relation1 ?below ?above))
		:effect (and (probabilistic
				 0.000 (m1)
				 0.000 (and (inserted) (instack ?above) (stackloc ?above) (not (stackloc ?below)))
				 0.188 (m2)
				 0.750 (m3)
				 0.000 (m4)
				 0.062 (and (stacked) (inserted) (instack ?above) (stackloc ?above) (not (stackloc ?below))))
				(not (pickloc ?above)))
	)
	(:action stack22
		:parameters (?below ?above)
		:precondition (and (not (stacked)) (not (inserted)) (pickloc ?above) (stackloc ?below) (objtype2 ?below) (objtype1 ?above) (relation1 ?below ?above))
		:effect (and (probabilistic
				 0.000 (m1)
				 0.000 (and (inserted) (instack ?above) (stackloc ?above) (not (stackloc ?below)))
				 0.114 (m2)
				 0.841 (m3)
				 0.000 (m4)
				 0.045 (and (stacked) (inserted) (instack ?above) (stackloc ?above) (not (stackloc ?below))))
				(not (pickloc ?above)))
	)
	(:action stack23
		:parameters (?below ?above)
		:precondition (and (not (stacked)) (not (inserted)) (pickloc ?above) (stackloc ?below) (objtype2 ?below) (objtype3 ?above) (relation1 ?below ?above))
		:effect (and (probabilistic
				 0.000 (m1)
				 0.000 (and (inserted) (instack ?above) (stackloc ?above) (not (stackloc ?below)))
				 0.000 (m2)
				 0.794 (m3)
				 0.000 (m4)
				 0.206 (and (stacked) (inserted) (instack ?above) (stackloc ?above) (not (stackloc ?below))))
				(not (pickloc ?above)))
	)
	(:action stack24
		:parameters (?below ?above)
		:precondition (and (not (stacked)) (not (inserted)) (pickloc ?above) (stackloc ?below) (objtype1 ?below) (objtype0 ?above) (relation1 ?below ?above))
		:effect (and (probabilistic
				 0.000 (m1)
				 0.000 (and (inserted) (instack ?above) (stackloc ?above) (not (stackloc ?below)))
				 0.500 (m2)
				 0.107 (m3)
				 0.036 (m4)
				 0.357 (and (stacked) (inserted) (instack ?above) (stackloc ?above) (not (stackloc ?below))))
				(not (pickloc ?above)))
	)
	(:action stack25
		:parameters (?below ?above)
		:precondition (and (not (stacked)) (not (inserted)) (pickloc ?above) (stackloc ?below) (objtype1 ?below) (objtype2 ?above) (relation1 ?below ?above))
		:effect (and (probabilistic
				 0.000 (m1)
				 0.000 (and (inserted) (instack ?above) (stackloc ?above) (not (stackloc ?below)))
				 0.000 (m2)
				 0.875 (m3)
				 0.000 (m4)
				 0.125 (and (stacked) (inserted) (instack ?above) (stackloc ?above) (not (stackloc ?below))))
				(not (pickloc ?above)))
	)
	(:action stack26
		:parameters (?below ?above)
		:precondition (and (not (stacked)) (not (inserted)) (pickloc ?above) (stackloc ?below) (objtype1 ?below) (objtype1 ?above) (relation1 ?below ?above))
		:effect (and (probabilistic
				 0.000 (m1)
				 0.000 (and (inserted) (instack ?above) (stackloc ?above) (not (stackloc ?below)))
				 0.100 (m2)
				 0.271 (m3)
				 0.014 (m4)
				 0.614 (and (stacked) (inserted) (instack ?above) (stackloc ?above) (not (stackloc ?below))))
				(not (pickloc ?above)))
	)
	(:action stack27
		:parameters (?below ?above)
		:precondition (and (not (stacked)) (not (inserted)) (pickloc ?above) (stackloc ?below) (objtype1 ?below) (objtype3 ?above) (relation1 ?below ?above))
		:effect (and (probabilistic
				 0.000 (m1)
				 0.000 (and (inserted) (instack ?above) (stackloc ?above) (not (stackloc ?below)))
				 0.350 (m2)
				 0.075 (m3)
				 0.075 (m4)
				 0.500 (and (stacked) (inserted) (instack ?above) (stackloc ?above) (not (stackloc ?below))))
				(not (pickloc ?above)))
	)
	(:action stack28
		:parameters (?below ?above)
		:precondition (and (not (stacked)) (not (inserted)) (pickloc ?above) (stackloc ?below) (objtype3 ?below) (objtype0 ?above) (relation1 ?below ?above))
		:effect (and (probabilistic
				 0.742 (m1)
				 0.000 (and (inserted) (instack ?above) (stackloc ?above) (not (stackloc ?below)))
				 0.258 (m2)
				 0.000 (m3)
				 0.000 (m4)
				 0.000 (and (stacked) (inserted) (instack ?above) (stackloc ?above) (not (stackloc ?below))))
				(not (pickloc ?above)))
	)
	(:action stack29
		:parameters (?below ?above)
		:precondition (and (not (stacked)) (not (inserted)) (pickloc ?above) (stackloc ?below) (objtype3 ?below) (objtype1 ?above) (relation1 ?below ?above))
		:effect (and (probabilistic
				 0.221 (m1)
				 0.000 (and (inserted) (instack ?above) (stackloc ?above) (not (stackloc ?below)))
				 0.074 (m2)
				 0.029 (m3)
				 0.676 (m4)
				 0.000 (and (stacked) (inserted) (instack ?above) (stackloc ?above) (not (stackloc ?below))))
				(not (pickloc ?above)))
	)
	(:action stack30
		:parameters (?below ?above)
		:precondition (and (not (stacked)) (not (inserted)) (pickloc ?above) (stackloc ?below) (objtype3 ?below) (objtype2 ?above) (relation1 ?below ?above))
		:effect (and (probabilistic
				 0.200 (m1)
				 0.050 (and (inserted) (instack ?above) (stackloc ?above) (not (stackloc ?below)))
				 0.000 (m2)
				 0.000 (m3)
				 0.750 (m4)
				 0.000 (and (stacked) (inserted) (instack ?above) (stackloc ?above) (not (stackloc ?below))))
				(not (pickloc ?above)))
	)
	(:action stack31
		:parameters (?below ?above)
		:precondition (and (not (stacked)) (not (inserted)) (pickloc ?above) (stackloc ?below) (objtype3 ?below) (objtype3 ?above) (relation1 ?below ?above))
		:effect (and (probabilistic
				 0.242 (m1)
				 0.000 (and (inserted) (instack ?above) (stackloc ?above) (not (stackloc ?below)))
				 0.727 (m2)
				 0.000 (m3)
				 0.030 (m4)
				 0.000 (and (stacked) (inserted) (instack ?above) (stackloc ?above) (not (stackloc ?below))))
				(not (pickloc ?above)))
	)
	(:action increase-height1
		:precondition (and (stacked) (H0))
		:effect (and (not (H0)) (H1) (not (stacked)))
	)
	(:action increase-height2
		:precondition (and (stacked) (H1))
		:effect (and (not (H1)) (H2) (not (stacked)))
	)
	(:action increase-height3
		:precondition (and (stacked) (H2))
		:effect (and (not (H2)) (H3) (not (stacked)))
	)
	(:action increase-height4
		:precondition (and (stacked) (H3))
		:effect (and (not (H3)) (H4) (not (stacked)))
	)
	(:action increase-height5
		:precondition (and (stacked) (H4))
		:effect (and (not (H4)) (H5) (not (stacked)))
	)
	(:action increase-height6
		:precondition (and (stacked) (H5))
		:effect (and (not (H5)) (H6) (not (stacked)))
	)
	(:action increase-stack1
		:precondition (and (inserted) (S0))
		:effect (and (not (S0)) (S1) (not (inserted)))
	)
	(:action increase-stack2
		:precondition (and (inserted) (S1))
		:effect (and (not (S1)) (S2) (not (inserted)))
	)
	(:action increase-stack3
		:precondition (and (inserted) (S2))
		:effect (and (not (S2)) (S3) (not (inserted)))
	)
	(:action increase-stack4
		:precondition (and (inserted) (S3))
		:effect (and (not (S3)) (S4) (not (inserted)))
	)
	(:action increase-stack5
		:precondition (and (inserted) (S4))
		:effect (and (not (S4)) (S5) (not (inserted)))
	)
	(:action increase-stack6
		:precondition (and (inserted) (S5))
		:effect (and (not (S5)) (S6) (not (inserted)))
	)
	(:action makebase
		:parameters (?obj)
		:precondition (not (base))
		:effect (and (base) (stacked) (inserted) (not (pickloc ?obj)) (stackloc ?obj))
	)
)
