(define (domain stack)
	(:requirements :typing :negative-preconditions :probabilistic-effects :conditional-effects :disjunctive-preconditions)
	(:predicates
		(inserted)
		(stacked)
		(roll1)
		(tumble1)
		(roll2)
		(tumble2)
		(base)
		(pickloc ?x)
		(instack ?x)
		(stackloc ?x)
		(relation0 ?x ?y)
		(relation1 ?x ?y)
		(objtype0 ?x)
		(objtype1 ?x)
		(objtype2 ?x)
		(objtype3 ?x)
		(H0)
		(H1)
		(H2)
		(H3)
		(H4)
		(H5)
		(H6)
		(S0)
		(S1)
		(S2)
		(S3)
		(S4)
		(S5)
		(S6)
	)
	(:action stack0
		:parameters (?below ?above)
		:precondition (and (not (stacked)) (not (inserted)) (pickloc ?above) (stackloc ?below) (and (objtype0 ?below) (objtype3 ?above) (relation0 ?below ?above)))
		:effect (and (probabilistic 1.000 (tumble2)) (not (pickloc ?above)))
	)
	(:action stack1
		:parameters (?below ?above)
		:precondition (and (not (stacked)) (not (inserted)) (pickloc ?above) (stackloc ?below) (and (objtype0 ?below) (objtype3 ?above) (relation1 ?below ?above)))
		:effect (and (probabilistic 0.010 (roll1) 0.408 (tumble1) 0.582 (tumble2)) (not (pickloc ?above)))
	)
	(:action stack2
		:parameters (?below ?above)
		:precondition (and (not (stacked)) (not (inserted)) (pickloc ?above) (stackloc ?below) (or (and (objtype3 ?below) (objtype3 ?above) (relation0 ?below ?above)) (and (objtype3 ?below) (objtype3 ?above) (relation1 ?below ?above))))
		:effect (and (probabilistic 0.012 (and (inserted) (instack ?above) (stackloc ?above) (not (stackloc ?below))) 0.099 (and (stacked) (inserted) (instack ?above) (stackloc ?above) (not (stackloc ?below))) 0.210 (tumble1) 0.679 (tumble2)) (not (pickloc ?above)))
	)
	(:action stack3
		:parameters (?below ?above)
		:precondition (and (not (stacked)) (not (inserted)) (pickloc ?above) (stackloc ?below) (and (objtype0 ?below) (objtype0 ?above) (relation0 ?below ?above)))
		:effect (and (probabilistic 0.022 (and (stacked) (inserted) (instack ?above) (stackloc ?above) (not (stackloc ?below))) 0.044 (roll1) 0.934 (tumble2)) (not (pickloc ?above)))
	)
	(:action stack4
		:parameters (?below ?above)
		:precondition (and (not (stacked)) (not (inserted)) (pickloc ?above) (stackloc ?below) (and (objtype3 ?below) (objtype0 ?above) (relation0 ?below ?above)))
		:effect (and (probabilistic 0.038 (and (stacked) (inserted) (instack ?above) (stackloc ?above) (not (stackloc ?below))) 0.019 (roll1) 0.058 (tumble1) 0.885 (tumble2)) (not (pickloc ?above)))
	)
	(:action stack5
		:parameters (?below ?above)
		:precondition (and (not (stacked)) (not (inserted)) (pickloc ?above) (stackloc ?below) (and (objtype0 ?below) (objtype0 ?above) (relation1 ?below ?above)))
		:effect (and (probabilistic 0.026 (roll1) 0.105 (tumble1) 0.869 (tumble2)) (not (pickloc ?above)))
	)
	(:action stack6
		:parameters (?below ?above)
		:precondition (and (not (stacked)) (not (inserted)) (pickloc ?above) (stackloc ?below) (and (objtype3 ?below) (objtype0 ?above) (relation1 ?below ?above)))
		:effect (and (probabilistic 0.319 (tumble1) 0.681 (tumble2)) (not (pickloc ?above)))
	)
	(:action stack7
		:parameters (?below ?above)
		:precondition (and (not (stacked)) (not (inserted)) (pickloc ?above) (stackloc ?below) (and (objtype0 ?below) (objtype2 ?above) (relation0 ?below ?above)))
		:effect (and (probabilistic 0.028 (and (inserted) (instack ?above) (stackloc ?above) (not (stackloc ?below))) 0.014 (and (stacked) (inserted) (instack ?above) (stackloc ?above) (not (stackloc ?below))) 0.508 (roll1) 0.239 (tumble1) 0.211 (tumble2)) (not (pickloc ?above)))
	)
	(:action stack8
		:parameters (?below ?above)
		:precondition (and (not (stacked)) (not (inserted)) (pickloc ?above) (stackloc ?below) (and (objtype3 ?below) (objtype2 ?above) (relation0 ?below ?above)))
		:effect (and (probabilistic 0.042 (and (inserted) (instack ?above) (stackloc ?above) (not (stackloc ?below))) 0.056 (and (stacked) (inserted) (instack ?above) (stackloc ?above) (not (stackloc ?below))) 0.569 (roll1) 0.083 (tumble1) 0.014 (roll2) 0.236 (tumble2)) (not (pickloc ?above)))
	)
	(:action stack9
		:parameters (?below ?above)
		:precondition (and (not (stacked)) (not (inserted)) (pickloc ?above) (stackloc ?below) (and (objtype0 ?below) (objtype2 ?above) (relation1 ?below ?above)))
		:effect (and (probabilistic 0.020 (and (inserted) (instack ?above) (stackloc ?above) (not (stackloc ?below))) 0.684 (roll1) 0.208 (tumble1) 0.007 (roll2) 0.081 (tumble2)) (not (pickloc ?above)))
	)
	(:action stack10
		:parameters (?below ?above)
		:precondition (and (not (stacked)) (not (inserted)) (pickloc ?above) (stackloc ?below) (and (objtype3 ?below) (objtype2 ?above) (relation1 ?below ?above)))
		:effect (and (probabilistic 0.046 (and (inserted) (instack ?above) (stackloc ?above) (not (stackloc ?below))) 0.037 (and (stacked) (inserted) (instack ?above) (stackloc ?above) (not (stackloc ?below))) 0.602 (roll1) 0.185 (tumble1) 0.130 (tumble2)) (not (pickloc ?above)))
	)
	(:action stack11
		:parameters (?below ?above)
		:precondition (and (not (stacked)) (not (inserted)) (pickloc ?above) (stackloc ?below) (and (objtype3 ?below) (objtype1 ?above) (relation1 ?below ?above)))
		:effect (and (probabilistic 0.350 (and (inserted) (instack ?above) (stackloc ?above) (not (stackloc ?below))) 0.500 (roll1) 0.050 (tumble1) 0.100 (roll2)) (not (pickloc ?above)))
	)
	(:action stack12
		:parameters (?below ?above)
		:precondition (and (not (stacked)) (not (inserted)) (pickloc ?above) (stackloc ?below) (and (objtype0 ?below) (objtype1 ?above) (relation1 ?below ?above)))
		:effect (and (probabilistic 0.696 (roll1) 0.174 (tumble1) 0.087 (roll2) 0.043 (tumble2)) (not (pickloc ?above)))
	)
	(:action stack13
		:parameters (?below ?above)
		:precondition (and (not (stacked)) (not (inserted)) (pickloc ?above) (stackloc ?below) (and (objtype0 ?below) (objtype1 ?above) (relation0 ?below ?above)))
		:effect (and (probabilistic 0.046 (tumble1) 0.943 (roll2) 0.011 (tumble2)) (not (pickloc ?above)))
	)
	(:action stack14
		:parameters (?below ?above)
		:precondition (and (not (stacked)) (not (inserted)) (pickloc ?above) (stackloc ?below) (and (objtype3 ?below) (objtype1 ?above) (relation0 ?below ?above)))
		:effect (and (probabilistic 0.043 (and (stacked) (inserted) (instack ?above) (stackloc ?above) (not (stackloc ?below))) 0.957 (roll2)) (not (pickloc ?above)))
	)
	(:action stack15
		:parameters (?below ?above)
		:precondition (and (not (stacked)) (not (inserted)) (pickloc ?above) (stackloc ?below) (and (objtype1 ?below) (objtype1 ?above) (relation1 ?below ?above)))
		:effect (and (probabilistic 0.742 (and (inserted) (instack ?above) (stackloc ?above) (not (stackloc ?below))) 0.097 (and (stacked) (inserted) (instack ?above) (stackloc ?above) (not (stackloc ?below))) 0.161 (tumble2)) (not (pickloc ?above)))
	)
	(:action stack16
		:parameters (?below ?above)
		:precondition (and (not (stacked)) (not (inserted)) (pickloc ?above) (stackloc ?below) (and (objtype1 ?below) (objtype2 ?above) (relation1 ?below ?above)))
		:effect (and (probabilistic 0.760 (and (inserted) (instack ?above) (stackloc ?above) (not (stackloc ?below))) 0.120 (and (stacked) (inserted) (instack ?above) (stackloc ?above) (not (stackloc ?below))) 0.120 (tumble2)) (not (pickloc ?above)))
	)
	(:action stack17
		:parameters (?below ?above)
		:precondition (and (not (stacked)) (not (inserted)) (pickloc ?above) (stackloc ?below) (and (objtype1 ?below) (objtype0 ?above) (relation1 ?below ?above)))
		:effect (and (probabilistic 0.655 (and (inserted) (instack ?above) (stackloc ?above) (not (stackloc ?below))) 0.345 (tumble2)) (not (pickloc ?above)))
	)
	(:action stack18
		:parameters (?below ?above)
		:precondition (and (not (stacked)) (not (inserted)) (pickloc ?above) (stackloc ?below) (and (objtype1 ?below) (objtype3 ?above) (relation1 ?below ?above)))
		:effect (and (probabilistic 0.175 (and (inserted) (instack ?above) (stackloc ?above) (not (stackloc ?below))) 0.050 (and (stacked) (inserted) (instack ?above) (stackloc ?above) (not (stackloc ?below))) 0.025 (tumble1) 0.750 (tumble2)) (not (pickloc ?above)))
	)
	(:action stack19
		:parameters (?below ?above)
		:precondition (and (not (stacked)) (not (inserted)) (pickloc ?above) (stackloc ?below) (and (objtype1 ?below) (objtype2 ?above) (relation0 ?below ?above)))
		:effect (and (probabilistic 0.013 (and (inserted) (instack ?above) (stackloc ?above) (not (stackloc ?below))) 0.967 (and (stacked) (inserted) (instack ?above) (stackloc ?above) (not (stackloc ?below))) 0.020 (tumble2)) (not (pickloc ?above)))
	)
	(:action stack20
		:parameters (?below ?above)
		:precondition (and (not (stacked)) (not (inserted)) (pickloc ?above) (stackloc ?below) (and (objtype1 ?below) (objtype1 ?above) (relation0 ?below ?above)))
		:effect (and (probabilistic 0.971 (and (stacked) (inserted) (instack ?above) (stackloc ?above) (not (stackloc ?below))) 0.029 (tumble2)) (not (pickloc ?above)))
	)
	(:action stack21
		:parameters (?below ?above)
		:precondition (and (not (stacked)) (not (inserted)) (pickloc ?above) (stackloc ?below) (and (objtype1 ?below) (objtype0 ?above) (relation0 ?below ?above)))
		:effect (and (probabilistic 0.099 (and (inserted) (instack ?above) (stackloc ?above) (not (stackloc ?below))) 0.901 (and (stacked) (inserted) (instack ?above) (stackloc ?above) (not (stackloc ?below)))) (not (pickloc ?above)))
	)
	(:action stack22
		:parameters (?below ?above)
		:precondition (and (not (stacked)) (not (inserted)) (pickloc ?above) (stackloc ?below) (and (objtype1 ?below) (objtype3 ?above) (relation0 ?below ?above)))
		:effect (and (probabilistic 0.220 (and (inserted) (instack ?above) (stackloc ?above) (not (stackloc ?below))) 0.460 (and (stacked) (inserted) (instack ?above) (stackloc ?above) (not (stackloc ?below))) 0.320 (tumble2)) (not (pickloc ?above)))
	)
	(:action stack23
		:parameters (?below ?above)
		:precondition (and (not (stacked)) (not (inserted)) (pickloc ?above) (stackloc ?below) (and (objtype2 ?below) (objtype2 ?above) (relation1 ?below ?above)))
		:effect (and (probabilistic 0.006 (and (inserted) (instack ?above) (stackloc ?above) (not (stackloc ?below))) 0.941 (and (stacked) (inserted) (instack ?above) (stackloc ?above) (not (stackloc ?below))) 0.006 (roll1) 0.047 (tumble2)) (not (pickloc ?above)))
	)
	(:action stack24
		:parameters (?below ?above)
		:precondition (and (not (stacked)) (not (inserted)) (pickloc ?above) (stackloc ?below) (and (objtype2 ?below) (objtype1 ?above) (relation1 ?below ?above)))
		:effect (and (probabilistic 0.686 (and (inserted) (instack ?above) (stackloc ?above) (not (stackloc ?below))) 0.314 (and (stacked) (inserted) (instack ?above) (stackloc ?above) (not (stackloc ?below)))) (not (pickloc ?above)))
	)
	(:action stack25
		:parameters (?below ?above)
		:precondition (and (not (stacked)) (not (inserted)) (pickloc ?above) (stackloc ?below) (and (objtype2 ?below) (objtype2 ?above) (relation0 ?below ?above)))
		:effect (and (probabilistic 1.000 (and (stacked) (inserted) (instack ?above) (stackloc ?above) (not (stackloc ?below)))) (not (pickloc ?above)))
	)
	(:action stack26
		:parameters (?below ?above)
		:precondition (and (not (stacked)) (not (inserted)) (pickloc ?above) (stackloc ?below) (and (objtype2 ?below) (objtype1 ?above) (relation0 ?below ?above)))
		:effect (and (probabilistic 0.006 (and (inserted) (instack ?above) (stackloc ?above) (not (stackloc ?below))) 0.988 (and (stacked) (inserted) (instack ?above) (stackloc ?above) (not (stackloc ?below))) 0.006 (tumble2)) (not (pickloc ?above)))
	)
	(:action stack27
		:parameters (?below ?above)
		:precondition (and (not (stacked)) (not (inserted)) (pickloc ?above) (stackloc ?below) (and (objtype2 ?below) (objtype0 ?above) (relation1 ?below ?above)))
		:effect (and (probabilistic 0.044 (and (inserted) (instack ?above) (stackloc ?above) (not (stackloc ?below))) 0.407 (and (stacked) (inserted) (instack ?above) (stackloc ?above) (not (stackloc ?below))) 0.044 (roll1) 0.505 (tumble2)) (not (pickloc ?above)))
	)
	(:action stack28
		:parameters (?below ?above)
		:precondition (and (not (stacked)) (not (inserted)) (pickloc ?above) (stackloc ?below) (and (objtype2 ?below) (objtype0 ?above) (relation0 ?below ?above)))
		:effect (and (probabilistic 0.821 (and (stacked) (inserted) (instack ?above) (stackloc ?above) (not (stackloc ?below))) 0.054 (roll1) 0.016 (roll2) 0.109 (tumble2)) (not (pickloc ?above)))
	)
	(:action stack29
		:parameters (?below ?above)
		:precondition (and (not (stacked)) (not (inserted)) (pickloc ?above) (stackloc ?below) (or (and (objtype2 ?below) (objtype3 ?above) (relation0 ?below ?above)) (and (objtype2 ?below) (objtype3 ?above) (relation1 ?below ?above))))
		:effect (and (probabilistic 0.006 (and (inserted) (instack ?above) (stackloc ?above) (not (stackloc ?below))) 0.272 (and (stacked) (inserted) (instack ?above) (stackloc ?above) (not (stackloc ?below))) 0.011 (roll1) 0.017 (tumble1) 0.694 (tumble2)) (not (pickloc ?above)))
	)
	(:action increase-height1
		:precondition (and (stacked) (H0))
		:effect (and (not (H0)) (H1) (not (stacked)))
	)
	(:action increase-height2
		:precondition (and (stacked) (H1))
		:effect (and (not (H1)) (H2) (not (stacked)))
	)
	(:action increase-height3
		:precondition (and (stacked) (H2))
		:effect (and (not (H2)) (H3) (not (stacked)))
	)
	(:action increase-height4
		:precondition (and (stacked) (H3))
		:effect (and (not (H3)) (H4) (not (stacked)))
	)
	(:action increase-height5
		:precondition (and (stacked) (H4))
		:effect (and (not (H4)) (H5) (not (stacked)))
	)
	(:action increase-height6
		:precondition (and (stacked) (H5))
		:effect (and (not (H5)) (H6) (not (stacked)))
	)
	(:action increase-stack1
		:precondition (and (inserted) (S0))
		:effect (and (not (S0)) (S1) (not (inserted)))
	)
	(:action increase-stack2
		:precondition (and (inserted) (S1))
		:effect (and (not (S1)) (S2) (not (inserted)))
	)
	(:action increase-stack3
		:precondition (and (inserted) (S2))
		:effect (and (not (S2)) (S3) (not (inserted)))
	)
	(:action increase-stack4
		:precondition (and (inserted) (S3))
		:effect (and (not (S3)) (S4) (not (inserted)))
	)
	(:action increase-stack5
		:precondition (and (inserted) (S4))
		:effect (and (not (S4)) (S5) (not (inserted)))
	)
	(:action increase-stack6
		:precondition (and (inserted) (S5))
		:effect (and (not (S5)) (S6) (not (inserted)))
	)
	(:action makebase
		:parameters (?obj)
		:precondition (not (base))
		:effect (and (base) (stacked) (inserted) (not (pickloc ?obj)) (stackloc ?obj))
	)
)
