(define (domain stack)
	(:requirements :typing :negative-preconditions :probabilistic-effects :conditional-effects :disjunctive-preconditions)
	(:predicates
		(stacked) 
		(roll1) 
		(roll2) 
		(roll3) 
		(roll4) 
		(inserted) (base) 
		(pickloc ?x)
		(instack ?x)
		(stackloc ?x)
		(relation0 ?x ?y)
		(relation1 ?x ?y)
		(objtype0 ?x)
		(objtype1 ?x)
		(objtype2 ?x)
		(objtype3 ?x)
		(H0)
		(H1)
		(H2)
		(H3)
		(H4)
		(H5)
		(H6)
		(S0)
		(S1)
		(S2)
		(S3)
		(S4)
		(S5)
		(S6)
	)
	(:action stack0
		:parameters (?below ?above)
		:precondition (and (not (stacked)) (not (inserted)) (pickloc ?above) (stackloc ?below) (or (objtype0 ?below) (objtype1 ?below)) (objtype0 ?above) (or (relation0 ?below ?above) (relation1 ?below ?above)))
		:effect (and (probabilistic
				 0.000 (and (stacked) (inserted) (instack ?above) (stackloc ?above) (not (stackloc ?below)))
				 0.010 (roll1)
				 0.330 (roll2)
				 0.370 (roll3)
				 0.290 (roll4)
				 0.000 (and (inserted) (instack ?above) (stackloc ?above) (not (stackloc ?below))))
				(not (pickloc ?above)))
	)
	(:action stack1
		:parameters (?below ?above)
		:precondition (and (not (stacked)) (not (inserted)) (pickloc ?above) (stackloc ?below) (or (objtype0 ?below) (objtype1 ?below)) (objtype1 ?above) (or (relation0 ?below ?above) (relation1 ?below ?above)))
		:effect (and (probabilistic
				 0.000 (and (stacked) (inserted) (instack ?above) (stackloc ?above) (not (stackloc ?below)))
				 0.000 (roll1)
				 0.500 (roll2)
				 0.060 (roll3)
				 0.440 (roll4)
				 0.000 (and (inserted) (instack ?above) (stackloc ?above) (not (stackloc ?below))))
				(not (pickloc ?above)))
	)
	(:action stack2
		:parameters (?below ?above)
		:precondition (and (not (stacked)) (not (inserted)) (pickloc ?above) (stackloc ?below) (or (objtype0 ?below) (objtype1 ?below)) (objtype0 ?above) (or (relation0 ?below ?above) (relation1 ?below ?above)))
		:effect (and (probabilistic
				 0.000 (and (stacked) (inserted) (instack ?above) (stackloc ?above) (not (stackloc ?below)))
				 0.010 (roll1)
				 0.660 (roll2)
				 0.180 (roll3)
				 0.070 (roll4)
				 0.080 (and (inserted) (instack ?above) (stackloc ?above) (not (stackloc ?below))))
				(not (pickloc ?above)))
	)
	(:action stack3
		:parameters (?below ?above)
		:precondition (and (not (stacked)) (not (inserted)) (pickloc ?above) (stackloc ?below) (or (objtype0 ?below) (objtype1 ?below)) (objtype1 ?above) (or (relation0 ?below ?above) (relation1 ?below ?above)))
		:effect (and (probabilistic
				 0.000 (and (stacked) (inserted) (instack ?above) (stackloc ?above) (not (stackloc ?below)))
				 0.020 (roll1)
				 0.480 (roll2)
				 0.180 (roll3)
				 0.290 (roll4)
				 0.030 (and (inserted) (instack ?above) (stackloc ?above) (not (stackloc ?below))))
				(not (pickloc ?above)))
	)
	(:action stack4
		:parameters (?below ?above)
		:precondition (and (not (stacked)) (not (inserted)) (pickloc ?above) (stackloc ?below) (objtype0 ?below) (or (objtype2 ?above) (objtype3 ?above)) (or (relation0 ?below ?above) (relation1 ?below ?above)))
		:effect (and (probabilistic
				 0.490 (and (stacked) (inserted) (instack ?above) (stackloc ?above) (not (stackloc ?below)))
				 0.207 (roll1)
				 0.050 (roll2)
				 0.093 (roll3)
				 0.123 (roll4)
				 0.037 (and (inserted) (instack ?above) (stackloc ?above) (not (stackloc ?below))))
				(not (pickloc ?above)))
	)
	(:action stack5
		:parameters (?below ?above)
		:precondition (and (not (stacked)) (not (inserted)) (pickloc ?above) (stackloc ?below) (objtype1 ?below) (or (objtype2 ?above) (objtype3 ?above)) (or (relation0 ?below ?above) (relation1 ?below ?above)))
		:effect (and (probabilistic
				 0.483 (and (stacked) (inserted) (instack ?above) (stackloc ?above) (not (stackloc ?below)))
				 0.177 (roll1)
				 0.013 (roll2)
				 0.163 (roll3)
				 0.163 (roll4)
				 0.000 (and (inserted) (instack ?above) (stackloc ?above) (not (stackloc ?below))))
				(not (pickloc ?above)))
	)
	(:action stack6
		:parameters (?below ?above)
		:precondition (and (not (stacked)) (not (inserted)) (pickloc ?above) (stackloc ?below) (or (objtype2 ?below) (objtype3 ?below)) (or (objtype0 ?above) (objtype2 ?above)) (or (relation0 ?below ?above) (relation1 ?below ?above)))
		:effect (and (probabilistic
				 0.000 (and (stacked) (inserted) (instack ?above) (stackloc ?above) (not (stackloc ?below)))
				 0.070 (roll1)
				 0.670 (roll2)
				 0.010 (roll3)
				 0.003 (roll4)
				 0.247 (and (inserted) (instack ?above) (stackloc ?above) (not (stackloc ?below))))
				(not (pickloc ?above)))
	)
	(:action stack7
		:parameters (?below ?above)
		:precondition (and (not (stacked)) (not (inserted)) (pickloc ?above) (stackloc ?below) (or (objtype2 ?below) (objtype3 ?below)) (objtype1 ?above) (or (relation0 ?below ?above) (relation1 ?below ?above)))
		:effect (and (probabilistic
				 0.017 (and (stacked) (inserted) (instack ?above) (stackloc ?above) (not (stackloc ?below)))
				 0.123 (roll1)
				 0.137 (roll2)
				 0.000 (roll3)
				 0.000 (roll4)
				 0.723 (and (inserted) (instack ?above) (stackloc ?above) (not (stackloc ?below))))
				(not (pickloc ?above)))
	)
	(:action stack8
		:parameters (?below ?above)
		:precondition (and (not (stacked)) (not (inserted)) (pickloc ?above) (stackloc ?below) (or (objtype2 ?below) (objtype3 ?below)) (objtype3 ?above) (or (relation0 ?below ?above) (relation1 ?below ?above)))
		:effect (and (probabilistic
				 0.000 (and (stacked) (inserted) (instack ?above) (stackloc ?above) (not (stackloc ?below)))
				 0.092 (roll1)
				 0.028 (roll2)
				 0.000 (roll3)
				 0.000 (roll4)
				 0.880 (and (inserted) (instack ?above) (stackloc ?above) (not (stackloc ?below))))
				(not (pickloc ?above)))
	)
	(:action increase-height1
		:precondition (and (stacked) (H0))
		:effect (and (not (H0)) (H1) (not (stacked)))
	)
	(:action increase-height2
		:precondition (and (stacked) (H1))
		:effect (and (not (H1)) (H2) (not (stacked)))
	)
	(:action increase-height3
		:precondition (and (stacked) (H2))
		:effect (and (not (H2)) (H3) (not (stacked)))
	)
	(:action increase-height4
		:precondition (and (stacked) (H3))
		:effect (and (not (H3)) (H4) (not (stacked)))
	)
	(:action increase-height5
		:precondition (and (stacked) (H4))
		:effect (and (not (H4)) (H5) (not (stacked)))
	)
	(:action increase-height6
		:precondition (and (stacked) (H5))
		:effect (and (not (H5)) (H6) (not (stacked)))
	)
	(:action increase-stack1
		:precondition (and (inserted) (S0))
		:effect (and (not (S0)) (S1) (not (inserted)))
	)
	(:action increase-stack2
		:precondition (and (inserted) (S1))
		:effect (and (not (S1)) (S2) (not (inserted)))
	)
	(:action increase-stack3
		:precondition (and (inserted) (S2))
		:effect (and (not (S2)) (S3) (not (inserted)))
	)
	(:action increase-stack4
		:precondition (and (inserted) (S3))
		:effect (and (not (S3)) (S4) (not (inserted)))
	)
	(:action increase-stack5
		:precondition (and (inserted) (S4))
		:effect (and (not (S4)) (S5) (not (inserted)))
	)
	(:action increase-stack6
		:precondition (and (inserted) (S5))
		:effect (and (not (S5)) (S6) (not (inserted)))
	)
	(:action makebase
		:parameters (?obj)
		:precondition (not (base))
		:effect (and (base) (stacked) (inserted) (not (pickloc ?obj)) (stackloc ?obj))
	)
)
