(define (domain stack)
	(:requirements :typing :negative-preconditions :probabilistic-effects :conditional-effects :disjunctive-preconditions)
	(:predicates
		(roll1) 
		(roll2) 
		(roll3) 
		(stacked) 
		(roll4) 
		(inserted) (base) 
		(pickloc ?x)
		(instack ?x)
		(stackloc ?x)
		(relation0 ?x ?y)
		(relation1 ?x ?y)
		(objtype0 ?x)
		(objtype1 ?x)
		(objtype2 ?x)
		(objtype3 ?x)
		(H0)
		(H1)
		(H2)
		(H3)
		(H4)
		(H5)
		(H6)
		(S0)
		(S1)
		(S2)
		(S3)
		(S4)
		(S5)
		(S6)
	)
	(:action stack0
		:parameters (?below ?above)
		:precondition (and (not (stacked)) (not (inserted)) (pickloc ?above) (stackloc ?below) (or (objtype0 ?below) (objtype1 ?below)) (or (objtype0 ?above) (objtype1 ?above)) (or (relation0 ?below ?above) (relation1 ?below ?above)))
		:effect (and (probabilistic
				 0.080 (roll1)
				 0.070 (roll2)
				 0.850 (roll3)
				 0.000 (and (stacked) (inserted) (instack ?above) (stackloc ?above) (not (stackloc ?below)))
				 0.000 (roll4)
				 0.000 (and (inserted) (instack ?above) (stackloc ?above) (not (stackloc ?below))))
				(not (pickloc ?above)))
	)
	(:action stack1
		:parameters (?below ?above)
		:precondition (and (not (stacked)) (not (inserted)) (pickloc ?above) (stackloc ?below) (or (objtype0 ?below) (objtype1 ?below)) (or (objtype0 ?above) (objtype1 ?above)) (or (relation0 ?below ?above) (relation1 ?below ?above)))
		:effect (and (probabilistic
				 0.180 (roll1)
				 0.210 (roll2)
				 0.560 (roll3)
				 0.030 (and (stacked) (inserted) (instack ?above) (stackloc ?above) (not (stackloc ?below)))
				 0.000 (roll4)
				 0.020 (and (inserted) (instack ?above) (stackloc ?above) (not (stackloc ?below))))
				(not (pickloc ?above)))
	)
	(:action stack2
		:parameters (?below ?above)
		:precondition (and (not (stacked)) (not (inserted)) (pickloc ?above) (stackloc ?below) (or (objtype0 ?below) (objtype1 ?below)) (or (objtype0 ?above) (objtype1 ?above)) (or (relation0 ?below ?above) (relation1 ?below ?above)))
		:effect (and (probabilistic
				 0.390 (roll1)
				 0.060 (roll2)
				 0.460 (roll3)
				 0.000 (and (stacked) (inserted) (instack ?above) (stackloc ?above) (not (stackloc ?below)))
				 0.080 (roll4)
				 0.010 (and (inserted) (instack ?above) (stackloc ?above) (not (stackloc ?below))))
				(not (pickloc ?above)))
	)
	(:action stack3
		:parameters (?below ?above)
		:precondition (and (not (stacked)) (not (inserted)) (pickloc ?above) (stackloc ?below) (or (objtype0 ?below) (objtype1 ?below)) (or (objtype0 ?above) (objtype1 ?above)) (or (relation0 ?below ?above) (relation1 ?below ?above)))
		:effect (and (probabilistic
				 0.180 (roll1)
				 0.010 (roll2)
				 0.640 (roll3)
				 0.080 (and (stacked) (inserted) (instack ?above) (stackloc ?above) (not (stackloc ?below)))
				 0.090 (roll4)
				 0.000 (and (inserted) (instack ?above) (stackloc ?above) (not (stackloc ?below))))
				(not (pickloc ?above)))
	)
	(:action stack4
		:parameters (?below ?above)
		:precondition (and (not (stacked)) (not (inserted)) (pickloc ?above) (stackloc ?below) (objtype0 ?below) (or (objtype2 ?above) (objtype3 ?above)) (or (relation0 ?below ?above) (relation1 ?below ?above)))
		:effect (and (probabilistic
				 0.097 (roll1)
				 0.466 (roll2)
				 0.130 (roll3)
				 0.043 (and (stacked) (inserted) (instack ?above) (stackloc ?above) (not (stackloc ?below)))
				 0.007 (roll4)
				 0.257 (and (inserted) (instack ?above) (stackloc ?above) (not (stackloc ?below))))
				(not (pickloc ?above)))
	)
	(:action stack5
		:parameters (?below ?above)
		:precondition (and (not (stacked)) (not (inserted)) (pickloc ?above) (stackloc ?below) (objtype1 ?below) (or (objtype2 ?above) (objtype3 ?above)) (or (relation0 ?below ?above) (relation1 ?below ?above)))
		:effect (and (probabilistic
				 0.203 (roll1)
				 0.483 (roll2)
				 0.057 (roll3)
				 0.000 (and (stacked) (inserted) (instack ?above) (stackloc ?above) (not (stackloc ?below)))
				 0.023 (roll4)
				 0.233 (and (inserted) (instack ?above) (stackloc ?above) (not (stackloc ?below))))
				(not (pickloc ?above)))
	)
	(:action stack6
		:parameters (?below ?above)
		:precondition (and (not (stacked)) (not (inserted)) (pickloc ?above) (stackloc ?below) (or (objtype2 ?below) (objtype3 ?below)) (or (objtype0 ?above) (objtype2 ?above)) (or (relation0 ?below ?above) (relation1 ?below ?above)))
		:effect (and (probabilistic
				 0.010 (roll1)
				 0.003 (roll2)
				 0.620 (roll3)
				 0.247 (and (stacked) (inserted) (instack ?above) (stackloc ?above) (not (stackloc ?below)))
				 0.050 (roll4)
				 0.070 (and (inserted) (instack ?above) (stackloc ?above) (not (stackloc ?below))))
				(not (pickloc ?above)))
	)
	(:action stack7
		:parameters (?below ?above)
		:precondition (and (not (stacked)) (not (inserted)) (pickloc ?above) (stackloc ?below) (or (objtype2 ?below) (objtype3 ?below)) (objtype1 ?above) (or (relation0 ?below ?above) (relation1 ?below ?above)))
		:effect (and (probabilistic
				 0.000 (roll1)
				 0.013 (roll2)
				 0.133 (roll3)
				 0.727 (and (stacked) (inserted) (instack ?above) (stackloc ?above) (not (stackloc ?below)))
				 0.003 (roll4)
				 0.123 (and (inserted) (instack ?above) (stackloc ?above) (not (stackloc ?below))))
				(not (pickloc ?above)))
	)
	(:action stack8
		:parameters (?below ?above)
		:precondition (and (not (stacked)) (not (inserted)) (pickloc ?above) (stackloc ?below) (or (objtype2 ?below) (objtype3 ?below)) (objtype3 ?above) (or (relation0 ?below ?above) (relation1 ?below ?above)))
		:effect (and (probabilistic
				 0.000 (roll1)
				 0.000 (roll2)
				 0.023 (roll3)
				 0.880 (and (stacked) (inserted) (instack ?above) (stackloc ?above) (not (stackloc ?below)))
				 0.004 (roll4)
				 0.092 (and (inserted) (instack ?above) (stackloc ?above) (not (stackloc ?below))))
				(not (pickloc ?above)))
	)
	(:action increase-height1
		:precondition (and (stacked) (H0))
		:effect (and (not (H0)) (H1) (not (stacked)))
	)
	(:action increase-height2
		:precondition (and (stacked) (H1))
		:effect (and (not (H1)) (H2) (not (stacked)))
	)
	(:action increase-height3
		:precondition (and (stacked) (H2))
		:effect (and (not (H2)) (H3) (not (stacked)))
	)
	(:action increase-height4
		:precondition (and (stacked) (H3))
		:effect (and (not (H3)) (H4) (not (stacked)))
	)
	(:action increase-height5
		:precondition (and (stacked) (H4))
		:effect (and (not (H4)) (H5) (not (stacked)))
	)
	(:action increase-height6
		:precondition (and (stacked) (H5))
		:effect (and (not (H5)) (H6) (not (stacked)))
	)
	(:action increase-stack1
		:precondition (and (inserted) (S0))
		:effect (and (not (S0)) (S1) (not (inserted)))
	)
	(:action increase-stack2
		:precondition (and (inserted) (S1))
		:effect (and (not (S1)) (S2) (not (inserted)))
	)
	(:action increase-stack3
		:precondition (and (inserted) (S2))
		:effect (and (not (S2)) (S3) (not (inserted)))
	)
	(:action increase-stack4
		:precondition (and (inserted) (S3))
		:effect (and (not (S3)) (S4) (not (inserted)))
	)
	(:action increase-stack5
		:precondition (and (inserted) (S4))
		:effect (and (not (S4)) (S5) (not (inserted)))
	)
	(:action increase-stack6
		:precondition (and (inserted) (S5))
		:effect (and (not (S5)) (S6) (not (inserted)))
	)
	(:action makebase
		:parameters (?obj)
		:precondition (not (base))
		:effect (and (base) (stacked) (inserted) (not (pickloc ?obj)) (stackloc ?obj))
	)
)
(define (problem dom1) (:domain stack)
	(:objects O1 O2 O3 O4 O5)
	(:init
		(pickloc O1) (objtype3 O1)
		(pickloc O2) (objtype3 O2)
		(pickloc O3) (objtype2 O3)
		(pickloc O4) (objtype2 O4)
		(pickloc O5) (objtype1 O5)
		(relation0 O1 O2)
		(relation0 O1 O3)
		(relation0 O1 O4)
		(relation0 O1 O5)
		(relation0 O2 O1)
		(relation0 O2 O3)
		(relation0 O2 O4)
		(relation0 O2 O5)
		(relation0 O3 O1)
		(relation0 O3 O2)
		(relation0 O3 O4)
		(relation0 O3 O5)
		(relation0 O4 O1)
		(relation0 O4 O2)
		(relation0 O4 O3)
		(relation0 O4 O5)
		(relation0 O5 O1)
		(relation0 O5 O2)
		(relation0 O5 O3)
		(relation0 O5 O4)
		(H0)
		(S0)
	)
	(:goal (and (H2) (not (stacked)) (not (inserted))))
)
