(define (domain stack)
	(:requirements :typing :negative-preconditions :probabilistic-effects :conditional-effects :disjunctive-preconditions)
	(:predicates
		(inserted) 
		(stacked) 
		(roll1) 
		(tumble1) 
		(roll2) 
		(tumble2) (base) 
		(pickloc ?x)
		(instack ?x)
		(stackloc ?x)
		(relation0 ?x ?y)
		(relation1 ?x ?y)
		(objtype0 ?x)
		(objtype1 ?x)
		(objtype2 ?x)
		(objtype3 ?x)
		(H0)
		(H1)
		(H2)
		(H3)
		(H4)
		(H5)
		(H6)
		(S0)
		(S1)
		(S2)
		(S3)
		(S4)
		(S5)
		(S6)
	)
	(:action stack0
		:parameters (?below ?above)
		:precondition (and (not (stacked)) (not (inserted)) (pickloc ?above) (stackloc ?below) (objtype0 ?below) (objtype0 ?above) (relation0 ?below ?above))
		:effect (and (probabilistic
				 0.013 (and (inserted) (instack ?above) (stackloc ?above) (not (stackloc ?below)))
				 0.104 (and (stacked) (inserted) (instack ?above) (stackloc ?above) (not (stackloc ?below)))
				 0.000 (roll1)
				 0.065 (tumble1)
				 0.000 (roll2)
				 0.818 (tumble2))
				(not (pickloc ?above)))
	)
	(:action stack1
		:parameters (?below ?above)
		:precondition (and (not (stacked)) (not (inserted)) (pickloc ?above) (stackloc ?below) (objtype2 ?below) (objtype0 ?above) (relation0 ?below ?above))
		:effect (and (probabilistic
				 0.006 (and (inserted) (instack ?above) (stackloc ?above) (not (stackloc ?below)))
				 0.222 (and (stacked) (inserted) (instack ?above) (stackloc ?above) (not (stackloc ?below)))
				 0.006 (roll1)
				 0.018 (tumble1)
				 0.000 (roll2)
				 0.748 (tumble2))
				(not (pickloc ?above)))
	)
	(:action stack2
		:parameters (?below ?above)
		:precondition (and (not (stacked)) (not (inserted)) (pickloc ?above) (stackloc ?below) (objtype1 ?below) (objtype0 ?above) (relation0 ?below ?above))
		:effect (and (probabilistic
				 0.013 (and (inserted) (instack ?above) (stackloc ?above) (not (stackloc ?below)))
				 0.267 (and (stacked) (inserted) (instack ?above) (stackloc ?above) (not (stackloc ?below)))
				 0.000 (roll1)
				 0.013 (tumble1)
				 0.000 (roll2)
				 0.707 (tumble2))
				(not (pickloc ?above)))
	)
	(:action stack3
		:parameters (?below ?above)
		:precondition (and (not (stacked)) (not (inserted)) (pickloc ?above) (stackloc ?below) (objtype3 ?below) (objtype0 ?above) (relation0 ?below ?above))
		:effect (and (probabilistic
				 0.000 (and (inserted) (instack ?above) (stackloc ?above) (not (stackloc ?below)))
				 0.000 (and (stacked) (inserted) (instack ?above) (stackloc ?above) (not (stackloc ?below)))
				 0.015 (roll1)
				 0.239 (tumble1)
				 0.000 (roll2)
				 0.746 (tumble2))
				(not (pickloc ?above)))
	)
	(:action stack4
		:parameters (?below ?above)
		:precondition (and (not (stacked)) (not (inserted)) (pickloc ?above) (stackloc ?below) (objtype0 ?below) (objtype1 ?above) (relation0 ?below ?above))
		:effect (and (probabilistic
				 0.000 (and (inserted) (instack ?above) (stackloc ?above) (not (stackloc ?below)))
				 0.038 (and (stacked) (inserted) (instack ?above) (stackloc ?above) (not (stackloc ?below)))
				 0.000 (roll1)
				 0.000 (tumble1)
				 0.950 (roll2)
				 0.012 (tumble2))
				(not (pickloc ?above)))
	)
	(:action stack5
		:parameters (?below ?above)
		:precondition (and (not (stacked)) (not (inserted)) (pickloc ?above) (stackloc ?below) (objtype2 ?below) (objtype1 ?above) (relation0 ?below ?above))
		:effect (and (probabilistic
				 0.006 (and (inserted) (instack ?above) (stackloc ?above) (not (stackloc ?below)))
				 0.988 (and (stacked) (inserted) (instack ?above) (stackloc ?above) (not (stackloc ?below)))
				 0.000 (roll1)
				 0.000 (tumble1)
				 0.000 (roll2)
				 0.006 (tumble2))
				(not (pickloc ?above)))
	)
	(:action stack6
		:parameters (?below ?above)
		:precondition (and (not (stacked)) (not (inserted)) (pickloc ?above) (stackloc ?below) (objtype1 ?below) (objtype1 ?above) (relation0 ?below ?above))
		:effect (and (probabilistic
				 0.015 (and (inserted) (instack ?above) (stackloc ?above) (not (stackloc ?below)))
				 0.985 (and (stacked) (inserted) (instack ?above) (stackloc ?above) (not (stackloc ?below)))
				 0.000 (roll1)
				 0.000 (tumble1)
				 0.000 (roll2)
				 0.000 (tumble2))
				(not (pickloc ?above)))
	)
	(:action stack7
		:parameters (?below ?above)
		:precondition (and (not (stacked)) (not (inserted)) (pickloc ?above) (stackloc ?below) (objtype3 ?below) (objtype1 ?above) (relation0 ?below ?above))
		:effect (and (probabilistic
				 0.000 (and (inserted) (instack ?above) (stackloc ?above) (not (stackloc ?below)))
				 0.000 (and (stacked) (inserted) (instack ?above) (stackloc ?above) (not (stackloc ?below)))
				 0.000 (roll1)
				 0.050 (tumble1)
				 0.950 (roll2)
				 0.000 (tumble2))
				(not (pickloc ?above)))
	)
	(:action stack8
		:parameters (?below ?above)
		:precondition (and (not (stacked)) (not (inserted)) (pickloc ?above) (stackloc ?below) (objtype0 ?below) (objtype2 ?above) (relation0 ?below ?above))
		:effect (and (probabilistic
				 0.048 (and (inserted) (instack ?above) (stackloc ?above) (not (stackloc ?below)))
				 0.048 (and (stacked) (inserted) (instack ?above) (stackloc ?above) (not (stackloc ?below)))
				 0.585 (roll1)
				 0.117 (tumble1)
				 0.005 (roll2)
				 0.197 (tumble2))
				(not (pickloc ?above)))
	)
	(:action stack9
		:parameters (?below ?above)
		:precondition (and (not (stacked)) (not (inserted)) (pickloc ?above) (stackloc ?below) (objtype2 ?below) (objtype2 ?above) (relation0 ?below ?above))
		:effect (and (probabilistic
				 0.003 (and (inserted) (instack ?above) (stackloc ?above) (not (stackloc ?below)))
				 0.984 (and (stacked) (inserted) (instack ?above) (stackloc ?above) (not (stackloc ?below)))
				 0.003 (roll1)
				 0.000 (tumble1)
				 0.000 (roll2)
				 0.010 (tumble2))
				(not (pickloc ?above)))
	)
	(:action stack10
		:parameters (?below ?above)
		:precondition (and (not (stacked)) (not (inserted)) (pickloc ?above) (stackloc ?below) (objtype1 ?below) (objtype2 ?above) (relation0 ?below ?above))
		:effect (and (probabilistic
				 0.013 (and (inserted) (instack ?above) (stackloc ?above) (not (stackloc ?below)))
				 0.955 (and (stacked) (inserted) (instack ?above) (stackloc ?above) (not (stackloc ?below)))
				 0.000 (roll1)
				 0.000 (tumble1)
				 0.000 (roll2)
				 0.032 (tumble2))
				(not (pickloc ?above)))
	)
	(:action stack11
		:parameters (?below ?above)
		:precondition (and (not (stacked)) (not (inserted)) (pickloc ?above) (stackloc ?below) (objtype3 ?below) (objtype2 ?above) (relation0 ?below ?above))
		:effect (and (probabilistic
				 0.022 (and (inserted) (instack ?above) (stackloc ?above) (not (stackloc ?below)))
				 0.000 (and (stacked) (inserted) (instack ?above) (stackloc ?above) (not (stackloc ?below)))
				 0.639 (roll1)
				 0.233 (tumble1)
				 0.006 (roll2)
				 0.100 (tumble2))
				(not (pickloc ?above)))
	)
	(:action stack12
		:parameters (?below ?above)
		:precondition (and (not (stacked)) (not (inserted)) (pickloc ?above) (stackloc ?below) (objtype0 ?below) (objtype3 ?above) (relation0 ?below ?above))
		:effect (and (probabilistic
				 0.000 (and (inserted) (instack ?above) (stackloc ?above) (not (stackloc ?below)))
				 0.041 (and (stacked) (inserted) (instack ?above) (stackloc ?above) (not (stackloc ?below)))
				 0.041 (roll1)
				 0.122 (tumble1)
				 0.000 (roll2)
				 0.796 (tumble2))
				(not (pickloc ?above)))
	)
	(:action stack13
		:parameters (?below ?above)
		:precondition (and (not (stacked)) (not (inserted)) (pickloc ?above) (stackloc ?below) (objtype1 ?below) (objtype3 ?above) (relation0 ?below ?above))
		:effect (and (probabilistic
				 0.015 (and (inserted) (instack ?above) (stackloc ?above) (not (stackloc ?below)))
				 0.985 (and (stacked) (inserted) (instack ?above) (stackloc ?above) (not (stackloc ?below)))
				 0.000 (roll1)
				 0.000 (tumble1)
				 0.000 (roll2)
				 0.000 (tumble2))
				(not (pickloc ?above)))
	)
	(:action stack14
		:parameters (?below ?above)
		:precondition (and (not (stacked)) (not (inserted)) (pickloc ?above) (stackloc ?below) (objtype2 ?below) (objtype3 ?above) (relation0 ?below ?above))
		:effect (and (probabilistic
				 0.006 (and (inserted) (instack ?above) (stackloc ?above) (not (stackloc ?below)))
				 0.781 (and (stacked) (inserted) (instack ?above) (stackloc ?above) (not (stackloc ?below)))
				 0.052 (roll1)
				 0.000 (tumble1)
				 0.013 (roll2)
				 0.148 (tumble2))
				(not (pickloc ?above)))
	)
	(:action stack15
		:parameters (?below ?above)
		:precondition (and (not (stacked)) (not (inserted)) (pickloc ?above) (stackloc ?below) (objtype3 ?below) (objtype3 ?above) (relation0 ?below ?above))
		:effect (and (probabilistic
				 0.000 (and (inserted) (instack ?above) (stackloc ?above) (not (stackloc ?below)))
				 0.000 (and (stacked) (inserted) (instack ?above) (stackloc ?above) (not (stackloc ?below)))
				 0.018 (roll1)
				 0.018 (tumble1)
				 0.000 (roll2)
				 0.964 (tumble2))
				(not (pickloc ?above)))
	)
	(:action stack16
		:parameters (?below ?above)
		:precondition (and (not (stacked)) (not (inserted)) (pickloc ?above) (stackloc ?below) (objtype0 ?below) (objtype0 ?above) (relation1 ?below ?above))
		:effect (and (probabilistic
				 0.000 (and (inserted) (instack ?above) (stackloc ?above) (not (stackloc ?below)))
				 0.000 (and (stacked) (inserted) (instack ?above) (stackloc ?above) (not (stackloc ?below)))
				 0.000 (roll1)
				 0.565 (tumble1)
				 0.000 (roll2)
				 0.435 (tumble2))
				(not (pickloc ?above)))
	)
	(:action stack17
		:parameters (?below ?above)
		:precondition (and (not (stacked)) (not (inserted)) (pickloc ?above) (stackloc ?below) (objtype0 ?below) (objtype2 ?above) (relation1 ?below ?above))
		:effect (and (probabilistic
				 0.000 (and (inserted) (instack ?above) (stackloc ?above) (not (stackloc ?below)))
				 0.000 (and (stacked) (inserted) (instack ?above) (stackloc ?above) (not (stackloc ?below)))
				 0.417 (roll1)
				 0.500 (tumble1)
				 0.000 (roll2)
				 0.083 (tumble2))
				(not (pickloc ?above)))
	)
	(:action stack18
		:parameters (?below ?above)
		:precondition (and (not (stacked)) (not (inserted)) (pickloc ?above) (stackloc ?below) (objtype0 ?below) (objtype1 ?above) (relation1 ?below ?above))
		:effect (and (probabilistic
				 0.350 (and (inserted) (instack ?above) (stackloc ?above) (not (stackloc ?below)))
				 0.000 (and (stacked) (inserted) (instack ?above) (stackloc ?above) (not (stackloc ?below)))
				 0.550 (roll1)
				 0.050 (tumble1)
				 0.000 (roll2)
				 0.050 (tumble2))
				(not (pickloc ?above)))
	)
	(:action stack19
		:parameters (?below ?above)
		:precondition (and (not (stacked)) (not (inserted)) (pickloc ?above) (stackloc ?below) (objtype0 ?below) (objtype3 ?above) (relation1 ?below ?above))
		:effect (and (probabilistic
				 0.000 (and (inserted) (instack ?above) (stackloc ?above) (not (stackloc ?below)))
				 0.000 (and (stacked) (inserted) (instack ?above) (stackloc ?above) (not (stackloc ?below)))
				 0.000 (roll1)
				 0.346 (tumble1)
				 0.000 (roll2)
				 0.654 (tumble2))
				(not (pickloc ?above)))
	)
	(:action stack20
		:parameters (?below ?above)
		:precondition (and (not (stacked)) (not (inserted)) (pickloc ?above) (stackloc ?below) (objtype1 ?below) (objtype0 ?above) (relation1 ?below ?above))
		:effect (and (probabilistic
				 0.680 (and (inserted) (instack ?above) (stackloc ?above) (not (stackloc ?below)))
				 0.200 (and (stacked) (inserted) (instack ?above) (stackloc ?above) (not (stackloc ?below)))
				 0.000 (roll1)
				 0.000 (tumble1)
				 0.000 (roll2)
				 0.120 (tumble2))
				(not (pickloc ?above)))
	)
	(:action stack21
		:parameters (?below ?above)
		:precondition (and (not (stacked)) (not (inserted)) (pickloc ?above) (stackloc ?below) (objtype1 ?below) (objtype1 ?above) (relation1 ?below ?above))
		:effect (and (probabilistic
				 0.667 (and (inserted) (instack ?above) (stackloc ?above) (not (stackloc ?below)))
				 0.121 (and (stacked) (inserted) (instack ?above) (stackloc ?above) (not (stackloc ?below)))
				 0.000 (roll1)
				 0.000 (tumble1)
				 0.000 (roll2)
				 0.212 (tumble2))
				(not (pickloc ?above)))
	)
	(:action stack22
		:parameters (?below ?above)
		:precondition (and (not (stacked)) (not (inserted)) (pickloc ?above) (stackloc ?below) (objtype1 ?below) (objtype2 ?above) (relation1 ?below ?above))
		:effect (and (probabilistic
				 0.844 (and (inserted) (instack ?above) (stackloc ?above) (not (stackloc ?below)))
				 0.067 (and (stacked) (inserted) (instack ?above) (stackloc ?above) (not (stackloc ?below)))
				 0.000 (roll1)
				 0.000 (tumble1)
				 0.000 (roll2)
				 0.089 (tumble2))
				(not (pickloc ?above)))
	)
	(:action stack23
		:parameters (?below ?above)
		:precondition (and (not (stacked)) (not (inserted)) (pickloc ?above) (stackloc ?below) (objtype1 ?below) (objtype3 ?above) (relation1 ?below ?above))
		:effect (and (probabilistic
				 0.812 (and (inserted) (instack ?above) (stackloc ?above) (not (stackloc ?below)))
				 0.188 (and (stacked) (inserted) (instack ?above) (stackloc ?above) (not (stackloc ?below)))
				 0.000 (roll1)
				 0.000 (tumble1)
				 0.000 (roll2)
				 0.000 (tumble2))
				(not (pickloc ?above)))
	)
	(:action stack24
		:parameters (?below ?above)
		:precondition (and (not (stacked)) (not (inserted)) (pickloc ?above) (stackloc ?below) (objtype2 ?below) (objtype0 ?above) (relation1 ?below ?above))
		:effect (and (probabilistic
				 0.000 (and (inserted) (instack ?above) (stackloc ?above) (not (stackloc ?below)))
				 0.379 (and (stacked) (inserted) (instack ?above) (stackloc ?above) (not (stackloc ?below)))
				 0.034 (roll1)
				 0.000 (tumble1)
				 0.000 (roll2)
				 0.586 (tumble2))
				(not (pickloc ?above)))
	)
	(:action stack25
		:parameters (?below ?above)
		:precondition (and (not (stacked)) (not (inserted)) (pickloc ?above) (stackloc ?below) (objtype2 ?below) (objtype1 ?above) (relation1 ?below ?above))
		:effect (and (probabilistic
				 0.774 (and (inserted) (instack ?above) (stackloc ?above) (not (stackloc ?below)))
				 0.226 (and (stacked) (inserted) (instack ?above) (stackloc ?above) (not (stackloc ?below)))
				 0.000 (roll1)
				 0.000 (tumble1)
				 0.000 (roll2)
				 0.000 (tumble2))
				(not (pickloc ?above)))
	)
	(:action stack26
		:parameters (?below ?above)
		:precondition (and (not (stacked)) (not (inserted)) (pickloc ?above) (stackloc ?below) (objtype2 ?below) (objtype2 ?above) (relation1 ?below ?above))
		:effect (and (probabilistic
				 0.000 (and (inserted) (instack ?above) (stackloc ?above) (not (stackloc ?below)))
				 0.733 (and (stacked) (inserted) (instack ?above) (stackloc ?above) (not (stackloc ?below)))
				 0.000 (roll1)
				 0.000 (tumble1)
				 0.000 (roll2)
				 0.267 (tumble2))
				(not (pickloc ?above)))
	)
	(:action stack27
		:parameters (?below ?above)
		:precondition (and (not (stacked)) (not (inserted)) (pickloc ?above) (stackloc ?below) (objtype2 ?below) (objtype3 ?above) (relation1 ?below ?above))
		:effect (and (probabilistic
				 0.067 (and (inserted) (instack ?above) (stackloc ?above) (not (stackloc ?below)))
				 0.488 (and (stacked) (inserted) (instack ?above) (stackloc ?above) (not (stackloc ?below)))
				 0.067 (roll1)
				 0.000 (tumble1)
				 0.000 (roll2)
				 0.378 (tumble2))
				(not (pickloc ?above)))
	)
	(:action stack28
		:parameters (?below ?above)
		:precondition (and (not (stacked)) (not (inserted)) (pickloc ?above) (stackloc ?below) (objtype3 ?below) (objtype0 ?above) (relation1 ?below ?above))
		:effect (and (probabilistic
				 0.000 (and (inserted) (instack ?above) (stackloc ?above) (not (stackloc ?below)))
				 0.000 (and (stacked) (inserted) (instack ?above) (stackloc ?above) (not (stackloc ?below)))
				 0.000 (roll1)
				 0.697 (tumble1)
				 0.000 (roll2)
				 0.303 (tumble2))
				(not (pickloc ?above)))
	)
	(:action stack29
		:parameters (?below ?above)
		:precondition (and (not (stacked)) (not (inserted)) (pickloc ?above) (stackloc ?below) (objtype3 ?below) (objtype1 ?above) (relation1 ?below ?above))
		:effect (and (probabilistic
				 0.000 (and (inserted) (instack ?above) (stackloc ?above) (not (stackloc ?below)))
				 0.000 (and (stacked) (inserted) (instack ?above) (stackloc ?above) (not (stackloc ?below)))
				 0.750 (roll1)
				 0.200 (tumble1)
				 0.050 (roll2)
				 0.000 (tumble2))
				(not (pickloc ?above)))
	)
	(:action stack30
		:parameters (?below ?above)
		:precondition (and (not (stacked)) (not (inserted)) (pickloc ?above) (stackloc ?below) (objtype3 ?below) (objtype2 ?above) (relation1 ?below ?above))
		:effect (and (probabilistic
				 0.000 (and (inserted) (instack ?above) (stackloc ?above) (not (stackloc ?below)))
				 0.000 (and (stacked) (inserted) (instack ?above) (stackloc ?above) (not (stackloc ?below)))
				 0.700 (roll1)
				 0.200 (tumble1)
				 0.000 (roll2)
				 0.100 (tumble2))
				(not (pickloc ?above)))
	)
	(:action stack31
		:parameters (?below ?above)
		:precondition (and (not (stacked)) (not (inserted)) (pickloc ?above) (stackloc ?below) (objtype3 ?below) (objtype3 ?above) (relation1 ?below ?above))
		:effect (and (probabilistic
				 0.000 (and (inserted) (instack ?above) (stackloc ?above) (not (stackloc ?below)))
				 0.000 (and (stacked) (inserted) (instack ?above) (stackloc ?above) (not (stackloc ?below)))
				 0.023 (roll1)
				 0.159 (tumble1)
				 0.000 (roll2)
				 0.818 (tumble2))
				(not (pickloc ?above)))
	)
	(:action increase-height1
		:precondition (and (stacked) (H0))
		:effect (and (not (H0)) (H1) (not (stacked)))
	)
	(:action increase-height2
		:precondition (and (stacked) (H1))
		:effect (and (not (H1)) (H2) (not (stacked)))
	)
	(:action increase-height3
		:precondition (and (stacked) (H2))
		:effect (and (not (H2)) (H3) (not (stacked)))
	)
	(:action increase-height4
		:precondition (and (stacked) (H3))
		:effect (and (not (H3)) (H4) (not (stacked)))
	)
	(:action increase-height5
		:precondition (and (stacked) (H4))
		:effect (and (not (H4)) (H5) (not (stacked)))
	)
	(:action increase-height6
		:precondition (and (stacked) (H5))
		:effect (and (not (H5)) (H6) (not (stacked)))
	)
	(:action increase-stack1
		:precondition (and (inserted) (S0))
		:effect (and (not (S0)) (S1) (not (inserted)))
	)
	(:action increase-stack2
		:precondition (and (inserted) (S1))
		:effect (and (not (S1)) (S2) (not (inserted)))
	)
	(:action increase-stack3
		:precondition (and (inserted) (S2))
		:effect (and (not (S2)) (S3) (not (inserted)))
	)
	(:action increase-stack4
		:precondition (and (inserted) (S3))
		:effect (and (not (S3)) (S4) (not (inserted)))
	)
	(:action increase-stack5
		:precondition (and (inserted) (S4))
		:effect (and (not (S4)) (S5) (not (inserted)))
	)
	(:action increase-stack6
		:precondition (and (inserted) (S5))
		:effect (and (not (S5)) (S6) (not (inserted)))
	)
	(:action makebase
		:parameters (?obj)
		:precondition (not (base))
		:effect (and (base) (stacked) (inserted) (not (pickloc ?obj)) (stackloc ?obj))
	)
)
