(define (domain stack)
	(:requirements :typing :negative-preconditions :probabilistic-effects :conditional-effects :disjunctive-preconditions)
	(:predicates
		(inserted) 
		(stacked) 
		(roll1) 
		(tumble1) 
		(roll2) 
		(tumble2) (base) 
		(pickloc ?x)
		(instack ?x)
		(stackloc ?x)
		(relation0 ?x ?y)
		(relation1 ?x ?y)
		(objtype0 ?x)
		(objtype1 ?x)
		(objtype2 ?x)
		(objtype3 ?x)
		(H0)
		(H1)
		(H2)
		(H3)
		(H4)
		(H5)
		(H6)
		(S0)
		(S1)
		(S2)
		(S3)
		(S4)
		(S5)
		(S6)
	)
	(:action stack0
		:parameters (?below ?above)
		:precondition (and (not (stacked)) (not (inserted)) (pickloc ?above) (stackloc ?below) (objtype0 ?below) (objtype0 ?above) (relation0 ?below ?above))
		:effect (and (probabilistic
				 0.012 (and (inserted) (instack ?above) (stackloc ?above) (not (stackloc ?below)))
				 0.088 (and (stacked) (inserted) (instack ?above) (stackloc ?above) (not (stackloc ?below)))
				 0.000 (roll1)
				 0.075 (tumble1)
				 0.000 (roll2)
				 0.825 (tumble2))
				(not (pickloc ?above)))
	)
	(:action stack1
		:parameters (?below ?above)
		:precondition (and (not (stacked)) (not (inserted)) (pickloc ?above) (stackloc ?below) (objtype0 ?below) (objtype2 ?above) (relation0 ?below ?above))
		:effect (and (probabilistic
				 0.006 (and (inserted) (instack ?above) (stackloc ?above) (not (stackloc ?below)))
				 0.214 (and (stacked) (inserted) (instack ?above) (stackloc ?above) (not (stackloc ?below)))
				 0.006 (roll1)
				 0.018 (tumble1)
				 0.000 (roll2)
				 0.756 (tumble2))
				(not (pickloc ?above)))
	)
	(:action stack2
		:parameters (?below ?above)
		:precondition (and (not (stacked)) (not (inserted)) (pickloc ?above) (stackloc ?below) (objtype0 ?below) (objtype1 ?above) (relation0 ?below ?above))
		:effect (and (probabilistic
				 0.013 (and (inserted) (instack ?above) (stackloc ?above) (not (stackloc ?below)))
				 0.267 (and (stacked) (inserted) (instack ?above) (stackloc ?above) (not (stackloc ?below)))
				 0.000 (roll1)
				 0.013 (tumble1)
				 0.000 (roll2)
				 0.707 (tumble2))
				(not (pickloc ?above)))
	)
	(:action stack3
		:parameters (?below ?above)
		:precondition (and (not (stacked)) (not (inserted)) (pickloc ?above) (stackloc ?below) (objtype0 ?below) (objtype3 ?above) (relation0 ?below ?above))
		:effect (and (probabilistic
				 0.000 (and (inserted) (instack ?above) (stackloc ?above) (not (stackloc ?below)))
				 0.000 (and (stacked) (inserted) (instack ?above) (stackloc ?above) (not (stackloc ?below)))
				 0.014 (roll1)
				 0.260 (tumble1)
				 0.000 (roll2)
				 0.726 (tumble2))
				(not (pickloc ?above)))
	)
	(:action stack4
		:parameters (?below ?above)
		:precondition (and (not (stacked)) (not (inserted)) (pickloc ?above) (stackloc ?below) (objtype1 ?below) (objtype0 ?above) (relation0 ?below ?above))
		:effect (and (probabilistic
				 0.000 (and (inserted) (instack ?above) (stackloc ?above) (not (stackloc ?below)))
				 0.038 (and (stacked) (inserted) (instack ?above) (stackloc ?above) (not (stackloc ?below)))
				 0.000 (roll1)
				 0.000 (tumble1)
				 0.950 (roll2)
				 0.012 (tumble2))
				(not (pickloc ?above)))
	)
	(:action stack5
		:parameters (?below ?above)
		:precondition (and (not (stacked)) (not (inserted)) (pickloc ?above) (stackloc ?below) (objtype1 ?below) (objtype2 ?above) (relation0 ?below ?above))
		:effect (and (probabilistic
				 0.006 (and (inserted) (instack ?above) (stackloc ?above) (not (stackloc ?below)))
				 0.988 (and (stacked) (inserted) (instack ?above) (stackloc ?above) (not (stackloc ?below)))
				 0.000 (roll1)
				 0.000 (tumble1)
				 0.000 (roll2)
				 0.006 (tumble2))
				(not (pickloc ?above)))
	)
	(:action stack6
		:parameters (?below ?above)
		:precondition (and (not (stacked)) (not (inserted)) (pickloc ?above) (stackloc ?below) (objtype1 ?below) (objtype1 ?above) (relation0 ?below ?above))
		:effect (and (probabilistic
				 0.029 (and (inserted) (instack ?above) (stackloc ?above) (not (stackloc ?below)))
				 0.956 (and (stacked) (inserted) (instack ?above) (stackloc ?above) (not (stackloc ?below)))
				 0.000 (roll1)
				 0.000 (tumble1)
				 0.000 (roll2)
				 0.015 (tumble2))
				(not (pickloc ?above)))
	)
	(:action stack7
		:parameters (?below ?above)
		:precondition (and (not (stacked)) (not (inserted)) (pickloc ?above) (stackloc ?below) (objtype1 ?below) (objtype3 ?above) (relation0 ?below ?above))
		:effect (and (probabilistic
				 0.000 (and (inserted) (instack ?above) (stackloc ?above) (not (stackloc ?below)))
				 0.000 (and (stacked) (inserted) (instack ?above) (stackloc ?above) (not (stackloc ?below)))
				 0.000 (roll1)
				 0.050 (tumble1)
				 0.950 (roll2)
				 0.000 (tumble2))
				(not (pickloc ?above)))
	)
	(:action stack8
		:parameters (?below ?above)
		:precondition (and (not (stacked)) (not (inserted)) (pickloc ?above) (stackloc ?below) (objtype2 ?below) (objtype0 ?above) (relation0 ?below ?above))
		:effect (and (probabilistic
				 0.042 (and (inserted) (instack ?above) (stackloc ?above) (not (stackloc ?below)))
				 0.048 (and (stacked) (inserted) (instack ?above) (stackloc ?above) (not (stackloc ?below)))
				 0.587 (roll1)
				 0.122 (tumble1)
				 0.005 (roll2)
				 0.196 (tumble2))
				(not (pickloc ?above)))
	)
	(:action stack9
		:parameters (?below ?above)
		:precondition (and (not (stacked)) (not (inserted)) (pickloc ?above) (stackloc ?below) (objtype2 ?below) (objtype2 ?above) (relation0 ?below ?above))
		:effect (and (probabilistic
				 0.000 (and (inserted) (instack ?above) (stackloc ?above) (not (stackloc ?below)))
				 0.984 (and (stacked) (inserted) (instack ?above) (stackloc ?above) (not (stackloc ?below)))
				 0.003 (roll1)
				 0.000 (tumble1)
				 0.000 (roll2)
				 0.013 (tumble2))
				(not (pickloc ?above)))
	)
	(:action stack10
		:parameters (?below ?above)
		:precondition (and (not (stacked)) (not (inserted)) (pickloc ?above) (stackloc ?below) (objtype2 ?below) (objtype1 ?above) (relation0 ?below ?above))
		:effect (and (probabilistic
				 0.007 (and (inserted) (instack ?above) (stackloc ?above) (not (stackloc ?below)))
				 0.967 (and (stacked) (inserted) (instack ?above) (stackloc ?above) (not (stackloc ?below)))
				 0.000 (roll1)
				 0.000 (tumble1)
				 0.000 (roll2)
				 0.026 (tumble2))
				(not (pickloc ?above)))
	)
	(:action stack11
		:parameters (?below ?above)
		:precondition (and (not (stacked)) (not (inserted)) (pickloc ?above) (stackloc ?below) (objtype2 ?below) (objtype3 ?above) (relation0 ?below ?above))
		:effect (and (probabilistic
				 0.022 (and (inserted) (instack ?above) (stackloc ?above) (not (stackloc ?below)))
				 0.000 (and (stacked) (inserted) (instack ?above) (stackloc ?above) (not (stackloc ?below)))
				 0.648 (roll1)
				 0.229 (tumble1)
				 0.006 (roll2)
				 0.095 (tumble2))
				(not (pickloc ?above)))
	)
	(:action stack12
		:parameters (?below ?above)
		:precondition (and (not (stacked)) (not (inserted)) (pickloc ?above) (stackloc ?below) (objtype3 ?below) (objtype0 ?above) (relation0 ?below ?above))
		:effect (and (probabilistic
				 0.000 (and (inserted) (instack ?above) (stackloc ?above) (not (stackloc ?below)))
				 0.042 (and (stacked) (inserted) (instack ?above) (stackloc ?above) (not (stackloc ?below)))
				 0.042 (roll1)
				 0.111 (tumble1)
				 0.000 (roll2)
				 0.805 (tumble2))
				(not (pickloc ?above)))
	)
	(:action stack13
		:parameters (?below ?above)
		:precondition (and (not (stacked)) (not (inserted)) (pickloc ?above) (stackloc ?below) (objtype3 ?below) (objtype2 ?above) (relation0 ?below ?above))
		:effect (and (probabilistic
				 0.006 (and (inserted) (instack ?above) (stackloc ?above) (not (stackloc ?below)))
				 0.791 (and (stacked) (inserted) (instack ?above) (stackloc ?above) (not (stackloc ?below)))
				 0.063 (roll1)
				 0.000 (tumble1)
				 0.013 (roll2)
				 0.127 (tumble2))
				(not (pickloc ?above)))
	)
	(:action stack14
		:parameters (?below ?above)
		:precondition (and (not (stacked)) (not (inserted)) (pickloc ?above) (stackloc ?below) (objtype3 ?below) (objtype1 ?above) (relation0 ?below ?above))
		:effect (and (probabilistic
				 0.028 (and (inserted) (instack ?above) (stackloc ?above) (not (stackloc ?below)))
				 0.972 (and (stacked) (inserted) (instack ?above) (stackloc ?above) (not (stackloc ?below)))
				 0.000 (roll1)
				 0.000 (tumble1)
				 0.000 (roll2)
				 0.000 (tumble2))
				(not (pickloc ?above)))
	)
	(:action stack15
		:parameters (?below ?above)
		:precondition (and (not (stacked)) (not (inserted)) (pickloc ?above) (stackloc ?below) (objtype3 ?below) (objtype3 ?above) (relation0 ?below ?above))
		:effect (and (probabilistic
				 0.000 (and (inserted) (instack ?above) (stackloc ?above) (not (stackloc ?below)))
				 0.000 (and (stacked) (inserted) (instack ?above) (stackloc ?above) (not (stackloc ?below)))
				 0.017 (roll1)
				 0.017 (tumble1)
				 0.000 (roll2)
				 0.966 (tumble2))
				(not (pickloc ?above)))
	)
	(:action stack16
		:parameters (?below ?above)
		:precondition (and (not (stacked)) (not (inserted)) (pickloc ?above) (stackloc ?below) (objtype0 ?below) (objtype0 ?above) (relation1 ?below ?above))
		:effect (and (probabilistic
				 0.000 (and (inserted) (instack ?above) (stackloc ?above) (not (stackloc ?below)))
				 0.050 (and (stacked) (inserted) (instack ?above) (stackloc ?above) (not (stackloc ?below)))
				 0.000 (roll1)
				 0.600 (tumble1)
				 0.000 (roll2)
				 0.350 (tumble2))
				(not (pickloc ?above)))
	)
	(:action stack17
		:parameters (?below ?above)
		:precondition (and (not (stacked)) (not (inserted)) (pickloc ?above) (stackloc ?below) (objtype1 ?below) (objtype0 ?above) (relation1 ?below ?above))
		:effect (and (probabilistic
				 0.350 (and (inserted) (instack ?above) (stackloc ?above) (not (stackloc ?below)))
				 0.000 (and (stacked) (inserted) (instack ?above) (stackloc ?above) (not (stackloc ?below)))
				 0.550 (roll1)
				 0.050 (tumble1)
				 0.000 (roll2)
				 0.050 (tumble2))
				(not (pickloc ?above)))
	)
	(:action stack18
		:parameters (?below ?above)
		:precondition (and (not (stacked)) (not (inserted)) (pickloc ?above) (stackloc ?below) (objtype2 ?below) (objtype0 ?above) (relation1 ?below ?above))
		:effect (and (probabilistic
				 0.091 (and (inserted) (instack ?above) (stackloc ?above) (not (stackloc ?below)))
				 0.000 (and (stacked) (inserted) (instack ?above) (stackloc ?above) (not (stackloc ?below)))
				 0.364 (roll1)
				 0.454 (tumble1)
				 0.000 (roll2)
				 0.091 (tumble2))
				(not (pickloc ?above)))
	)
	(:action stack19
		:parameters (?below ?above)
		:precondition (and (not (stacked)) (not (inserted)) (pickloc ?above) (stackloc ?below) (objtype3 ?below) (objtype0 ?above) (relation1 ?below ?above))
		:effect (and (probabilistic
				 0.000 (and (inserted) (instack ?above) (stackloc ?above) (not (stackloc ?below)))
				 0.000 (and (stacked) (inserted) (instack ?above) (stackloc ?above) (not (stackloc ?below)))
				 0.000 (roll1)
				 0.357 (tumble1)
				 0.000 (roll2)
				 0.643 (tumble2))
				(not (pickloc ?above)))
	)
	(:action stack20
		:parameters (?below ?above)
		:precondition (and (not (stacked)) (not (inserted)) (pickloc ?above) (stackloc ?below) (objtype0 ?below) (objtype1 ?above) (relation1 ?below ?above))
		:effect (and (probabilistic
				 0.680 (and (inserted) (instack ?above) (stackloc ?above) (not (stackloc ?below)))
				 0.200 (and (stacked) (inserted) (instack ?above) (stackloc ?above) (not (stackloc ?below)))
				 0.000 (roll1)
				 0.000 (tumble1)
				 0.000 (roll2)
				 0.120 (tumble2))
				(not (pickloc ?above)))
	)
	(:action stack21
		:parameters (?below ?above)
		:precondition (and (not (stacked)) (not (inserted)) (pickloc ?above) (stackloc ?below) (objtype1 ?below) (objtype1 ?above) (relation1 ?below ?above))
		:effect (and (probabilistic
				 0.656 (and (inserted) (instack ?above) (stackloc ?above) (not (stackloc ?below)))
				 0.156 (and (stacked) (inserted) (instack ?above) (stackloc ?above) (not (stackloc ?below)))
				 0.000 (roll1)
				 0.000 (tumble1)
				 0.000 (roll2)
				 0.188 (tumble2))
				(not (pickloc ?above)))
	)
	(:action stack22
		:parameters (?below ?above)
		:precondition (and (not (stacked)) (not (inserted)) (pickloc ?above) (stackloc ?below) (objtype2 ?below) (objtype1 ?above) (relation1 ?below ?above))
		:effect (and (probabilistic
				 0.796 (and (inserted) (instack ?above) (stackloc ?above) (not (stackloc ?below)))
				 0.102 (and (stacked) (inserted) (instack ?above) (stackloc ?above) (not (stackloc ?below)))
				 0.000 (roll1)
				 0.000 (tumble1)
				 0.000 (roll2)
				 0.102 (tumble2))
				(not (pickloc ?above)))
	)
	(:action stack23
		:parameters (?below ?above)
		:precondition (and (not (stacked)) (not (inserted)) (pickloc ?above) (stackloc ?below) (objtype3 ?below) (objtype1 ?above) (relation1 ?below ?above))
		:effect (and (probabilistic
				 0.862 (and (inserted) (instack ?above) (stackloc ?above) (not (stackloc ?below)))
				 0.138 (and (stacked) (inserted) (instack ?above) (stackloc ?above) (not (stackloc ?below)))
				 0.000 (roll1)
				 0.000 (tumble1)
				 0.000 (roll2)
				 0.000 (tumble2))
				(not (pickloc ?above)))
	)
	(:action stack24
		:parameters (?below ?above)
		:precondition (and (not (stacked)) (not (inserted)) (pickloc ?above) (stackloc ?below) (objtype0 ?below) (objtype2 ?above) (relation1 ?below ?above))
		:effect (and (probabilistic
				 0.000 (and (inserted) (instack ?above) (stackloc ?above) (not (stackloc ?below)))
				 0.406 (and (stacked) (inserted) (instack ?above) (stackloc ?above) (not (stackloc ?below)))
				 0.031 (roll1)
				 0.000 (tumble1)
				 0.000 (roll2)
				 0.562 (tumble2))
				(not (pickloc ?above)))
	)
	(:action stack25
		:parameters (?below ?above)
		:precondition (and (not (stacked)) (not (inserted)) (pickloc ?above) (stackloc ?below) (objtype2 ?below) (objtype2 ?above) (relation1 ?below ?above))
		:effect (and (probabilistic
				 0.059 (and (inserted) (instack ?above) (stackloc ?above) (not (stackloc ?below)))
				 0.765 (and (stacked) (inserted) (instack ?above) (stackloc ?above) (not (stackloc ?below)))
				 0.000 (roll1)
				 0.000 (tumble1)
				 0.000 (roll2)
				 0.176 (tumble2))
				(not (pickloc ?above)))
	)
	(:action stack26
		:parameters (?below ?above)
		:precondition (and (not (stacked)) (not (inserted)) (pickloc ?above) (stackloc ?below) (objtype1 ?below) (objtype2 ?above) (relation1 ?below ?above))
		:effect (and (probabilistic
				 0.706 (and (inserted) (instack ?above) (stackloc ?above) (not (stackloc ?below)))
				 0.294 (and (stacked) (inserted) (instack ?above) (stackloc ?above) (not (stackloc ?below)))
				 0.000 (roll1)
				 0.000 (tumble1)
				 0.000 (roll2)
				 0.000 (tumble2))
				(not (pickloc ?above)))
	)
	(:action stack27
		:parameters (?below ?above)
		:precondition (and (not (stacked)) (not (inserted)) (pickloc ?above) (stackloc ?below) (objtype3 ?below) (objtype2 ?above) (relation1 ?below ?above))
		:effect (and (probabilistic
				 0.071 (and (inserted) (instack ?above) (stackloc ?above) (not (stackloc ?below)))
				 0.429 (and (stacked) (inserted) (instack ?above) (stackloc ?above) (not (stackloc ?below)))
				 0.024 (roll1)
				 0.000 (tumble1)
				 0.000 (roll2)
				 0.476 (tumble2))
				(not (pickloc ?above)))
	)
	(:action stack28
		:parameters (?below ?above)
		:precondition (and (not (stacked)) (not (inserted)) (pickloc ?above) (stackloc ?below) (objtype0 ?below) (objtype3 ?above) (relation1 ?below ?above))
		:effect (and (probabilistic
				 0.000 (and (inserted) (instack ?above) (stackloc ?above) (not (stackloc ?below)))
				 0.000 (and (stacked) (inserted) (instack ?above) (stackloc ?above) (not (stackloc ?below)))
				 0.000 (roll1)
				 0.741 (tumble1)
				 0.000 (roll2)
				 0.259 (tumble2))
				(not (pickloc ?above)))
	)
	(:action stack29
		:parameters (?below ?above)
		:precondition (and (not (stacked)) (not (inserted)) (pickloc ?above) (stackloc ?below) (objtype1 ?below) (objtype3 ?above) (relation1 ?below ?above))
		:effect (and (probabilistic
				 0.000 (and (inserted) (instack ?above) (stackloc ?above) (not (stackloc ?below)))
				 0.000 (and (stacked) (inserted) (instack ?above) (stackloc ?above) (not (stackloc ?below)))
				 0.750 (roll1)
				 0.200 (tumble1)
				 0.050 (roll2)
				 0.000 (tumble2))
				(not (pickloc ?above)))
	)
	(:action stack30
		:parameters (?below ?above)
		:precondition (and (not (stacked)) (not (inserted)) (pickloc ?above) (stackloc ?below) (objtype2 ?below) (objtype3 ?above) (relation1 ?below ?above))
		:effect (and (probabilistic
				 0.000 (and (inserted) (instack ?above) (stackloc ?above) (not (stackloc ?below)))
				 0.000 (and (stacked) (inserted) (instack ?above) (stackloc ?above) (not (stackloc ?below)))
				 0.619 (roll1)
				 0.238 (tumble1)
				 0.000 (roll2)
				 0.143 (tumble2))
				(not (pickloc ?above)))
	)
	(:action stack31
		:parameters (?below ?above)
		:precondition (and (not (stacked)) (not (inserted)) (pickloc ?above) (stackloc ?below) (objtype3 ?below) (objtype3 ?above) (relation1 ?below ?above))
		:effect (and (probabilistic
				 0.000 (and (inserted) (instack ?above) (stackloc ?above) (not (stackloc ?below)))
				 0.000 (and (stacked) (inserted) (instack ?above) (stackloc ?above) (not (stackloc ?below)))
				 0.024 (roll1)
				 0.171 (tumble1)
				 0.000 (roll2)
				 0.805 (tumble2))
				(not (pickloc ?above)))
	)
	(:action increase-height1
		:precondition (and (stacked) (H0))
		:effect (and (not (H0)) (H1) (not (stacked)))
	)
	(:action increase-height2
		:precondition (and (stacked) (H1))
		:effect (and (not (H1)) (H2) (not (stacked)))
	)
	(:action increase-height3
		:precondition (and (stacked) (H2))
		:effect (and (not (H2)) (H3) (not (stacked)))
	)
	(:action increase-height4
		:precondition (and (stacked) (H3))
		:effect (and (not (H3)) (H4) (not (stacked)))
	)
	(:action increase-height5
		:precondition (and (stacked) (H4))
		:effect (and (not (H4)) (H5) (not (stacked)))
	)
	(:action increase-height6
		:precondition (and (stacked) (H5))
		:effect (and (not (H5)) (H6) (not (stacked)))
	)
	(:action increase-stack1
		:precondition (and (inserted) (S0))
		:effect (and (not (S0)) (S1) (not (inserted)))
	)
	(:action increase-stack2
		:precondition (and (inserted) (S1))
		:effect (and (not (S1)) (S2) (not (inserted)))
	)
	(:action increase-stack3
		:precondition (and (inserted) (S2))
		:effect (and (not (S2)) (S3) (not (inserted)))
	)
	(:action increase-stack4
		:precondition (and (inserted) (S3))
		:effect (and (not (S3)) (S4) (not (inserted)))
	)
	(:action increase-stack5
		:precondition (and (inserted) (S4))
		:effect (and (not (S4)) (S5) (not (inserted)))
	)
	(:action increase-stack6
		:precondition (and (inserted) (S5))
		:effect (and (not (S5)) (S6) (not (inserted)))
	)
	(:action makebase
		:parameters (?obj)
		:precondition (not (base))
		:effect (and (base) (stacked) (inserted) (not (pickloc ?obj)) (stackloc ?obj))
	)
)
(define (problem dom1) (:domain stack)
	(:objects O1 O2 O3 O4 O5)
	(:init
		(pickloc O1) (objtype0 O1)
		(pickloc O2) (objtype0 O2)
		(pickloc O3) (objtype2 O3)
		(pickloc O4) (objtype1 O4)
		(pickloc O5) (objtype3 O5)
		(relation0 O1 O2)
		(relation0 O1 O3)
		(relation0 O1 O4)
		(relation0 O1 O5)
		(relation0 O2 O1)
		(relation0 O2 O3)
		(relation0 O2 O4)
		(relation1 O2 O5)
		(relation0 O3 O1)
		(relation0 O3 O2)
		(relation0 O3 O4)
		(relation0 O3 O5)
		(relation0 O4 O1)
		(relation0 O4 O2)
		(relation0 O4 O3)
		(relation0 O4 O5)
		(relation0 O5 O1)
		(relation0 O5 O2)
		(relation0 O5 O3)
		(relation0 O5 O4)
		(H0)
		(S0)
	)
	(:goal (and (H1) (S1) (not (stacked)) (not (inserted))))
)
