(define (domain stack)
	(:requirements :typing :negative-preconditions :probabilistic-effects :conditional-effects :disjunctive-preconditions)
	(:predicates
		(roll1) 
		(inserted) 
		(roll2) 
		(obj1_moves_far_diag) 
		(both_move_together_X) 
		(both_move_together_diag) (base) 
		(pickloc ?x)
		(instack ?x)
		(stackloc ?x)
		(relation0 ?x ?y)
		(relation1 ?x ?y)
		(objtype0 ?x)
		(objtype1 ?x)
		(objtype2 ?x)
		(objtype3 ?x)
		(H0)
		(H1)
		(H2)
		(H3)
		(H4)
		(H5)
		(H6)
		(S0)
		(S1)
		(S2)
		(S3)
		(S4)
		(S5)
		(S6)
	)
	(:action stack0
		:parameters (?below ?above)
		:precondition (and (not (stacked)) (not (inserted)) (pickloc ?above) (stackloc ?below) (objtype0 ?below) (objtype0 ?above) (relation0 ?below ?above))
		:effect (and (probabilistic
				 0.000 (roll1)
				 0.500 (and (inserted) (instack ?above) (stackloc ?above) (not (stackloc ?below)))
				 0.500 (roll2)
				 0.000 (obj1_moves_far_diag)
				 0.000 (both_move_together_X)
				 0.000 (both_move_together_diag))
				(not (pickloc ?above)))
	)
	(:action stack1
		:parameters (?below ?above)
		:precondition (and (not (stacked)) (not (inserted)) (pickloc ?above) (stackloc ?below) (objtype0 ?below) (objtype1 ?above) (relation0 ?below ?above))
		:effect (and (probabilistic
				 0.000 (roll1)
				 0.961 (and (inserted) (instack ?above) (stackloc ?above) (not (stackloc ?below)))
				 0.039 (roll2)
				 0.000 (obj1_moves_far_diag)
				 0.000 (both_move_together_X)
				 0.000 (both_move_together_diag))
				(not (pickloc ?above)))
	)
	(:action stack2
		:parameters (?below ?above)
		:precondition (and (not (stacked)) (not (inserted)) (pickloc ?above) (stackloc ?below) (objtype0 ?below) (objtype0 ?above) (relation1 ?below ?above))
		:effect (and (probabilistic
				 0.000 (roll1)
				 0.759 (and (inserted) (instack ?above) (stackloc ?above) (not (stackloc ?below)))
				 0.152 (roll2)
				 0.089 (obj1_moves_far_diag)
				 0.000 (both_move_together_X)
				 0.000 (both_move_together_diag))
				(not (pickloc ?above)))
	)
	(:action stack3
		:parameters (?below ?above)
		:precondition (and (not (stacked)) (not (inserted)) (pickloc ?above) (stackloc ?below) (objtype0 ?below) (objtype1 ?above) (relation1 ?below ?above))
		:effect (and (probabilistic
				 0.000 (roll1)
				 0.522 (and (inserted) (instack ?above) (stackloc ?above) (not (stackloc ?below)))
				 0.398 (roll2)
				 0.080 (obj1_moves_far_diag)
				 0.000 (both_move_together_X)
				 0.000 (both_move_together_diag))
				(not (pickloc ?above)))
	)
	(:action stack4
		:parameters (?below ?above)
		:precondition (and (not (stacked)) (not (inserted)) (pickloc ?above) (stackloc ?below) (objtype1 ?below) (objtype0 ?above) (relation0 ?below ?above))
		:effect (and (probabilistic
				 0.000 (roll1)
				 0.851 (and (inserted) (instack ?above) (stackloc ?above) (not (stackloc ?below)))
				 0.149 (roll2)
				 0.000 (obj1_moves_far_diag)
				 0.000 (both_move_together_X)
				 0.000 (both_move_together_diag))
				(not (pickloc ?above)))
	)
	(:action stack5
		:parameters (?below ?above)
		:precondition (and (not (stacked)) (not (inserted)) (pickloc ?above) (stackloc ?below) (objtype1 ?below) (objtype0 ?above) (relation1 ?below ?above))
		:effect (and (probabilistic
				 0.010 (roll1)
				 0.990 (and (inserted) (instack ?above) (stackloc ?above) (not (stackloc ?below)))
				 0.000 (roll2)
				 0.000 (obj1_moves_far_diag)
				 0.000 (both_move_together_X)
				 0.000 (both_move_together_diag))
				(not (pickloc ?above)))
	)
	(:action stack6
		:parameters (?below ?above)
		:precondition (and (not (stacked)) (not (inserted)) (pickloc ?above) (stackloc ?below) (objtype1 ?below) (objtype1 ?above) (relation0 ?below ?above))
		:effect (and (probabilistic
				 0.006 (roll1)
				 0.962 (and (inserted) (instack ?above) (stackloc ?above) (not (stackloc ?below)))
				 0.023 (roll2)
				 0.009 (obj1_moves_far_diag)
				 0.000 (both_move_together_X)
				 0.000 (both_move_together_diag))
				(not (pickloc ?above)))
	)
	(:action stack7
		:parameters (?below ?above)
		:precondition (and (not (stacked)) (not (inserted)) (pickloc ?above) (stackloc ?below) (objtype1 ?below) (objtype1 ?above) (relation1 ?below ?above))
		:effect (and (probabilistic
				 0.011 (roll1)
				 0.957 (and (inserted) (instack ?above) (stackloc ?above) (not (stackloc ?below)))
				 0.011 (roll2)
				 0.021 (obj1_moves_far_diag)
				 0.000 (both_move_together_X)
				 0.000 (both_move_together_diag))
				(not (pickloc ?above)))
	)
	(:action stack8
		:parameters (?below ?above)
		:precondition (and (not (stacked)) (not (inserted)) (pickloc ?above) (stackloc ?below) (objtype0 ?below) (objtype2 ?above) (relation0 ?below ?above))
		:effect (and (probabilistic
				 0.000 (roll1)
				 1.000 (and (inserted) (instack ?above) (stackloc ?above) (not (stackloc ?below)))
				 0.000 (roll2)
				 0.000 (obj1_moves_far_diag)
				 0.000 (both_move_together_X)
				 0.000 (both_move_together_diag))
				(not (pickloc ?above)))
	)
	(:action stack9
		:parameters (?below ?above)
		:precondition (and (not (stacked)) (not (inserted)) (pickloc ?above) (stackloc ?below) (objtype0 ?below) (objtype2 ?above) (relation1 ?below ?above))
		:effect (and (probabilistic
				 0.000 (roll1)
				 0.647 (and (inserted) (instack ?above) (stackloc ?above) (not (stackloc ?below)))
				 0.318 (roll2)
				 0.035 (obj1_moves_far_diag)
				 0.000 (both_move_together_X)
				 0.000 (both_move_together_diag))
				(not (pickloc ?above)))
	)
	(:action stack10
		:parameters (?below ?above)
		:precondition (and (not (stacked)) (not (inserted)) (pickloc ?above) (stackloc ?below) (objtype1 ?below) (objtype2 ?above) (relation0 ?below ?above))
		:effect (and (probabilistic
				 0.006 (roll1)
				 0.740 (and (inserted) (instack ?above) (stackloc ?above) (not (stackloc ?below)))
				 0.052 (roll2)
				 0.182 (obj1_moves_far_diag)
				 0.019 (both_move_together_X)
				 0.000 (both_move_together_diag))
				(not (pickloc ?above)))
	)
	(:action stack11
		:parameters (?below ?above)
		:precondition (and (not (stacked)) (not (inserted)) (pickloc ?above) (stackloc ?below) (objtype1 ?below) (objtype2 ?above) (relation1 ?below ?above))
		:effect (and (probabilistic
				 0.000 (roll1)
				 0.636 (and (inserted) (instack ?above) (stackloc ?above) (not (stackloc ?below)))
				 0.052 (roll2)
				 0.299 (obj1_moves_far_diag)
				 0.013 (both_move_together_X)
				 0.000 (both_move_together_diag))
				(not (pickloc ?above)))
	)
	(:action stack12
		:parameters (?below ?above)
		:precondition (and (not (stacked)) (not (inserted)) (pickloc ?above) (stackloc ?below) (objtype0 ?below) (objtype3 ?above) (relation0 ?below ?above))
		:effect (and (probabilistic
				 0.160 (roll1)
				 0.120 (and (inserted) (instack ?above) (stackloc ?above) (not (stackloc ?below)))
				 0.040 (roll2)
				 0.640 (obj1_moves_far_diag)
				 0.000 (both_move_together_X)
				 0.040 (both_move_together_diag))
				(not (pickloc ?above)))
	)
	(:action stack13
		:parameters (?below ?above)
		:precondition (and (not (stacked)) (not (inserted)) (pickloc ?above) (stackloc ?below) (objtype0 ?below) (objtype3 ?above) (relation1 ?below ?above))
		:effect (and (probabilistic
				 0.000 (roll1)
				 0.321 (and (inserted) (instack ?above) (stackloc ?above) (not (stackloc ?below)))
				 0.268 (roll2)
				 0.411 (obj1_moves_far_diag)
				 0.000 (both_move_together_X)
				 0.000 (both_move_together_diag))
				(not (pickloc ?above)))
	)
	(:action stack14
		:parameters (?below ?above)
		:precondition (and (not (stacked)) (not (inserted)) (pickloc ?above) (stackloc ?below) (objtype1 ?below) (objtype3 ?above) (relation0 ?below ?above))
		:effect (and (probabilistic
				 0.077 (roll1)
				 0.204 (and (inserted) (instack ?above) (stackloc ?above) (not (stackloc ?below)))
				 0.014 (roll2)
				 0.683 (obj1_moves_far_diag)
				 0.007 (both_move_together_X)
				 0.014 (both_move_together_diag))
				(not (pickloc ?above)))
	)
	(:action stack15
		:parameters (?below ?above)
		:precondition (and (not (stacked)) (not (inserted)) (pickloc ?above) (stackloc ?below) (objtype1 ?below) (objtype3 ?above) (relation1 ?below ?above))
		:effect (and (probabilistic
				 0.000 (roll1)
				 0.213 (and (inserted) (instack ?above) (stackloc ?above) (not (stackloc ?below)))
				 0.021 (roll2)
				 0.766 (obj1_moves_far_diag)
				 0.000 (both_move_together_X)
				 0.000 (both_move_together_diag))
				(not (pickloc ?above)))
	)
	(:action stack16
		:parameters (?below ?above)
		:precondition (and (not (stacked)) (not (inserted)) (pickloc ?above) (stackloc ?below) (objtype2 ?below) (objtype0 ?above) (relation0 ?below ?above))
		:effect (and (probabilistic
				 0.000 (roll1)
				 0.020 (and (inserted) (instack ?above) (stackloc ?above) (not (stackloc ?below)))
				 0.160 (roll2)
				 0.000 (obj1_moves_far_diag)
				 0.760 (both_move_together_X)
				 0.060 (both_move_together_diag))
				(not (pickloc ?above)))
	)
	(:action stack17
		:parameters (?below ?above)
		:precondition (and (not (stacked)) (not (inserted)) (pickloc ?above) (stackloc ?below) (objtype3 ?below) (objtype0 ?above) (relation0 ?below ?above))
		:effect (and (probabilistic
				 0.000 (roll1)
				 0.060 (and (inserted) (instack ?above) (stackloc ?above) (not (stackloc ?below)))
				 0.100 (roll2)
				 0.040 (obj1_moves_far_diag)
				 0.780 (both_move_together_X)
				 0.020 (both_move_together_diag))
				(not (pickloc ?above)))
	)
	(:action stack18
		:parameters (?below ?above)
		:precondition (and (not (stacked)) (not (inserted)) (pickloc ?above) (stackloc ?below) (objtype2 ?below) (objtype0 ?above) (relation1 ?below ?above))
		:effect (and (probabilistic
				 0.000 (roll1)
				 0.000 (and (inserted) (instack ?above) (stackloc ?above) (not (stackloc ?below)))
				 0.000 (roll2)
				 0.000 (obj1_moves_far_diag)
				 0.918 (both_move_together_X)
				 0.082 (both_move_together_diag))
				(not (pickloc ?above)))
	)
	(:action stack19
		:parameters (?below ?above)
		:precondition (and (not (stacked)) (not (inserted)) (pickloc ?above) (stackloc ?below) (objtype3 ?below) (objtype0 ?above) (relation1 ?below ?above))
		:effect (and (probabilistic
				 0.000 (roll1)
				 0.000 (and (inserted) (instack ?above) (stackloc ?above) (not (stackloc ?below)))
				 0.000 (roll2)
				 0.000 (obj1_moves_far_diag)
				 1.000 (both_move_together_X)
				 0.000 (both_move_together_diag))
				(not (pickloc ?above)))
	)
	(:action stack20
		:parameters (?below ?above)
		:precondition (and (not (stacked)) (not (inserted)) (pickloc ?above) (stackloc ?below) (objtype2 ?below) (objtype1 ?above) (relation0 ?below ?above))
		:effect (and (probabilistic
				 0.024 (roll1)
				 0.000 (and (inserted) (instack ?above) (stackloc ?above) (not (stackloc ?below)))
				 0.329 (roll2)
				 0.076 (obj1_moves_far_diag)
				 0.324 (both_move_together_X)
				 0.247 (both_move_together_diag))
				(not (pickloc ?above)))
	)
	(:action stack21
		:parameters (?below ?above)
		:precondition (and (not (stacked)) (not (inserted)) (pickloc ?above) (stackloc ?below) (objtype2 ?below) (objtype1 ?above) (relation1 ?below ?above))
		:effect (and (probabilistic
				 0.049 (roll1)
				 0.000 (and (inserted) (instack ?above) (stackloc ?above) (not (stackloc ?below)))
				 0.327 (roll2)
				 0.115 (obj1_moves_far_diag)
				 0.279 (both_move_together_X)
				 0.230 (both_move_together_diag))
				(not (pickloc ?above)))
	)
	(:action stack22
		:parameters (?below ?above)
		:precondition (and (not (stacked)) (not (inserted)) (pickloc ?above) (stackloc ?below) (objtype3 ?below) (objtype1 ?above) (relation0 ?below ?above))
		:effect (and (probabilistic
				 0.007 (roll1)
				 0.054 (and (inserted) (instack ?above) (stackloc ?above) (not (stackloc ?below)))
				 0.348 (roll2)
				 0.188 (obj1_moves_far_diag)
				 0.329 (both_move_together_X)
				 0.074 (both_move_together_diag))
				(not (pickloc ?above)))
	)
	(:action stack23
		:parameters (?below ?above)
		:precondition (and (not (stacked)) (not (inserted)) (pickloc ?above) (stackloc ?below) (objtype3 ?below) (objtype1 ?above) (relation1 ?below ?above))
		:effect (and (probabilistic
				 0.025 (roll1)
				 0.025 (and (inserted) (instack ?above) (stackloc ?above) (not (stackloc ?below)))
				 0.275 (roll2)
				 0.200 (obj1_moves_far_diag)
				 0.125 (both_move_together_X)
				 0.350 (both_move_together_diag))
				(not (pickloc ?above)))
	)
	(:action stack24
		:parameters (?below ?above)
		:precondition (and (not (stacked)) (not (inserted)) (pickloc ?above) (stackloc ?below) (objtype2 ?below) (objtype2 ?above) (relation0 ?below ?above))
		:effect (and (probabilistic
				 0.000 (roll1)
				 0.000 (and (inserted) (instack ?above) (stackloc ?above) (not (stackloc ?below)))
				 0.000 (roll2)
				 0.852 (obj1_moves_far_diag)
				 0.074 (both_move_together_X)
				 0.074 (both_move_together_diag))
				(not (pickloc ?above)))
	)
	(:action stack25
		:parameters (?below ?above)
		:precondition (and (not (stacked)) (not (inserted)) (pickloc ?above) (stackloc ?below) (objtype3 ?below) (objtype2 ?above) (relation0 ?below ?above))
		:effect (and (probabilistic
				 0.000 (roll1)
				 0.060 (and (inserted) (instack ?above) (stackloc ?above) (not (stackloc ?below)))
				 0.015 (roll2)
				 0.775 (obj1_moves_far_diag)
				 0.090 (both_move_together_X)
				 0.060 (both_move_together_diag))
				(not (pickloc ?above)))
	)
	(:action stack26
		:parameters (?below ?above)
		:precondition (and (not (stacked)) (not (inserted)) (pickloc ?above) (stackloc ?below) (objtype2 ?below) (objtype3 ?above) (relation0 ?below ?above))
		:effect (and (probabilistic
				 0.119 (roll1)
				 0.015 (and (inserted) (instack ?above) (stackloc ?above) (not (stackloc ?below)))
				 0.015 (roll2)
				 0.582 (obj1_moves_far_diag)
				 0.045 (both_move_together_X)
				 0.224 (both_move_together_diag))
				(not (pickloc ?above)))
	)
	(:action stack27
		:parameters (?below ?above)
		:precondition (and (not (stacked)) (not (inserted)) (pickloc ?above) (stackloc ?below) (objtype3 ?below) (objtype3 ?above) (relation0 ?below ?above))
		:effect (and (probabilistic
				 0.127 (roll1)
				 0.063 (and (inserted) (instack ?above) (stackloc ?above) (not (stackloc ?below)))
				 0.000 (roll2)
				 0.730 (obj1_moves_far_diag)
				 0.016 (both_move_together_X)
				 0.063 (both_move_together_diag))
				(not (pickloc ?above)))
	)
	(:action stack28
		:parameters (?below ?above)
		:precondition (and (not (stacked)) (not (inserted)) (pickloc ?above) (stackloc ?below) (objtype2 ?below) (objtype2 ?above) (relation1 ?below ?above))
		:effect (and (probabilistic
				 0.000 (roll1)
				 0.000 (and (inserted) (instack ?above) (stackloc ?above) (not (stackloc ?below)))
				 0.000 (roll2)
				 0.660 (obj1_moves_far_diag)
				 0.132 (both_move_together_X)
				 0.208 (both_move_together_diag))
				(not (pickloc ?above)))
	)
	(:action stack29
		:parameters (?below ?above)
		:precondition (and (not (stacked)) (not (inserted)) (pickloc ?above) (stackloc ?below) (objtype3 ?below) (objtype2 ?above) (relation1 ?below ?above))
		:effect (and (probabilistic
				 0.000 (roll1)
				 0.000 (and (inserted) (instack ?above) (stackloc ?above) (not (stackloc ?below)))
				 0.031 (roll2)
				 0.188 (obj1_moves_far_diag)
				 0.375 (both_move_together_X)
				 0.406 (both_move_together_diag))
				(not (pickloc ?above)))
	)
	(:action stack30
		:parameters (?below ?above)
		:precondition (and (not (stacked)) (not (inserted)) (pickloc ?above) (stackloc ?below) (objtype2 ?below) (objtype3 ?above) (relation1 ?below ?above))
		:effect (and (probabilistic
				 0.031 (roll1)
				 0.000 (and (inserted) (instack ?above) (stackloc ?above) (not (stackloc ?below)))
				 0.000 (roll2)
				 0.281 (obj1_moves_far_diag)
				 0.000 (both_move_together_X)
				 0.688 (both_move_together_diag))
				(not (pickloc ?above)))
	)
	(:action stack31
		:parameters (?below ?above)
		:precondition (and (not (stacked)) (not (inserted)) (pickloc ?above) (stackloc ?below) (objtype3 ?below) (objtype3 ?above) (relation1 ?below ?above))
		:effect (and (probabilistic
				 0.000 (roll1)
				 0.111 (and (inserted) (instack ?above) (stackloc ?above) (not (stackloc ?below)))
				 0.000 (roll2)
				 0.389 (obj1_moves_far_diag)
				 0.000 (both_move_together_X)
				 0.500 (both_move_together_diag))
				(not (pickloc ?above)))
	)
	(:action increase-height1
		:precondition (and (stacked) (H0))
		:effect (and (not (H0)) (H1) (not (stacked)))
	)
	(:action increase-height2
		:precondition (and (stacked) (H1))
		:effect (and (not (H1)) (H2) (not (stacked)))
	)
	(:action increase-height3
		:precondition (and (stacked) (H2))
		:effect (and (not (H2)) (H3) (not (stacked)))
	)
	(:action increase-height4
		:precondition (and (stacked) (H3))
		:effect (and (not (H3)) (H4) (not (stacked)))
	)
	(:action increase-height5
		:precondition (and (stacked) (H4))
		:effect (and (not (H4)) (H5) (not (stacked)))
	)
	(:action increase-height6
		:precondition (and (stacked) (H5))
		:effect (and (not (H5)) (H6) (not (stacked)))
	)
	(:action increase-stack1
		:precondition (and (inserted) (S0))
		:effect (and (not (S0)) (S1) (not (inserted)))
	)
	(:action increase-stack2
		:precondition (and (inserted) (S1))
		:effect (and (not (S1)) (S2) (not (inserted)))
	)
	(:action increase-stack3
		:precondition (and (inserted) (S2))
		:effect (and (not (S2)) (S3) (not (inserted)))
	)
	(:action increase-stack4
		:precondition (and (inserted) (S3))
		:effect (and (not (S3)) (S4) (not (inserted)))
	)
	(:action increase-stack5
		:precondition (and (inserted) (S4))
		:effect (and (not (S4)) (S5) (not (inserted)))
	)
	(:action increase-stack6
		:precondition (and (inserted) (S5))
		:effect (and (not (S5)) (S6) (not (inserted)))
	)
	(:action makebase
		:parameters (?obj)
		:precondition (not (base))
		:effect (and (base) (stacked) (inserted) (not (pickloc ?obj)) (stackloc ?obj))
	)
)
